Improved engine performance and flight dynamics
flybywiresim/a32nx pull request #1295
Opened 2020-10-13 19:50 UTC by MisterChocker

Fixes #1255 #1204 

## Summary of Changes

- Engine (redesigned performance table)
  - Increased low N1 performance
  - Decreased high N1 performance
-  Aerodynamics
   - Flaps
     - Increased lift coef
_prevents early stalling of the aircraft_
_improves the overall feeling of the aircraft in flight_
     - Decreased drag coef
_deceleration on approach now slower_
     - Increased pitch momentum
_pitch now changes noticeable when flaps position changes_
   - Speedbrakes / Spoiler
     - Decreased drag coef
    - Landing gear
      - Increased drag coef
   - Elevator
     - Increased momentum coef
_makes aircraft (more) responsive_

## Screenshots (if necessary)

Shows change to the engine performance parameters
![image](https://user-images.githubusercontent.com/1857322/95888802-d925af80-0d81-11eb-92db-92ac1a32f3d8.png)

## References

https://www.youtube.com/watch?v=cv41hm4JEB8&feature=youtu.be&t=100
https://www.youtube.com/watch?v=FODhSJucbK0
https://www.youtube.com/watch?v=rhI5XGwlnaI

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

2020-10-14 00:26 UTC, donstim commented
See my comments on an earlier version of the modification here: https://github.com/flybywiresim/a32nx/issues/1204#issuecomment-708079418
Thank you for adding the change to the spoiler drag coefficient!

2020-10-14 01:05 UTC, joniatus commented
This works beautifully as described. Thank you 1000x better

2020-10-14 01:19 UTC, MisterChocker commented
I am currently working on an further improved engine parameter table.
I don't know how long this will take me tho.

2020-10-14 01:34 UTC, NathanInnes requested changes

2020-10-14 01:34 UTC, NathanInnes commented on A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/engines.cfg
> +
remove new line
```suggestion
```

2020-10-14 04:20 UTC, starvingjavi commented
Name: Javi#2557
Date of testing:  13/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1295 

Testing technique: Spawn at gate and did a full flight
Steps you've made to test the Pull Request:

Spawn C&D
Continue flight as normal
Check for engine thrust
Check flight model during all phases of flight

Overall Rating: Really Good
Conclusions of the testing: Works as described

- Engine
Works as described in PR

- Aerodynamics
Flaps and pitch attitude throughout flaps works as described on PR

2020-10-14 07:56 UTC, Lucky38i commented
please remove any changes you made to manifest.json and layout.json. The CI will automatically produce these

2020-10-14 10:42 UTC, nobodyn0se commented
I tested this PR, great work. 
Note: I'm not with QA.

Date of testing: 13 Oct, 2020
Sim Version: 1.9.5

T/O weight: 67500kg
Departure: FACT 
Arrival: FAPE

Low N1 performance is realistic. I taxied in idle thrust with no issues. Lift generated by flaps is much better. 
Initial climb at 3500 fpm FLEX 65, acceleration was realistic. After climb thrust reached target speed of 250kts, the rate of climb was 2800 fpm to maintain 250 (the IRL video shows ~3200fpm), that continued till FL140 beyond which the climb rate slowed down to 1200-1500 fpm range. 

Above FL280 though, the climb rate slowed down to 800fpm till FL310 where I initially leveled off to burn some fuel. 
The aircraft struggled to climb above FL310, it did not go above 400fpm. I had to use TO/GA which sustained a 600fpm climb to FL330. 
During cruise, the N1 thrust was at 91.5% for M0.78 with a 45kts tailwind. According to Airbus' cruise perf charts, at that weight it should be around 81% N1 for M0.78 

Descent performance was stunning, had to use the spoilers to slow down sometimes. Approach was realistic with addition of flaps requiring pitch changes just like the IRL video. 

Overview: Realistic acceleration/deceleration. Great low N1 performance. High N1 performance might have to be tweaked.

2020-10-14 11:22 UTC, MisterChocker commented on A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/engines.cfg
> +
yes will do.

2020-10-14 11:22 UTC, MisterChocker commented
> please remove any changes you made to manifest.json and layout.json. The CI will automatically produce these

Will do.

2020-10-14 11:27 UTC, MisterChocker commented
> Low N1 performance is realistic. I taxied in idle thrust with no issues. Lift generated by flaps is much better.
> Initial climb at 3500 fpm FLEX 65, acceleration was realistic. After climb thrust reached target speed of 250kts, the rate of climb was 2800 fpm to maintain 250 (the IRL video shows ~3200fpm), that continued till FL140 beyond which the climb rate slowed down to 1200-1500 fpm range.

Do you know the N1 you had during climb?

> Above FL280 though, the climb rate slowed down to 800fpm till FL310 where I initially leveled off to burn some fuel.
> The aircraft struggled to climb above FL310, it did not go above 400fpm. I had to use TO/GA which sustained a 600fpm climb to FL330.
> During cruise, the N1 thrust was at 91.5% for M0.78 with a 45kts tailwind. According to Airbus' cruise perf charts, at that weight it should be around 81% N1 for M0.78

Will look into that as well. Could you please send (or link) me the cruise perf charts, that would be nice.

> Descent performance was stunning, had to use the spoilers to slow down sometimes. Approach was realistic with addition of flaps requiring pitch changes just like the IRL video.

> Overview: Realistic acceleration/deceleration. Great low N1 performance. High N1 performance might have to be tweaked.
I will do some work for the high N1 performance.

2020-10-14 11:57 UTC, nobodyn0se commented
> Do you know the N1 you had during climb? 

@MisterChocker Climb N1 was 88.6%

Here's the cruise performance chart. Credits to user: donbikes who sent it, I hope it's fine to upload it here. 
![A320NeoPerf](https://user-images.githubusercontent.com/48710616/95985510-4ef15000-0e42-11eb-8b35-e6049d52f94e.jpg)

2020-10-14 12:03 UTC, MisterChocker commented
@nobodyn0se big thanks. Hell yeah I like the imperial system for weights... still not using metric ffs.

2020-10-14 12:41 UTC, vladal91 commented
Name: sphectrum#6484
Date of testing: 14/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1295

Testing technique: Gate start/cold and dark, full flight
Steps you've made to test the Pull Request: Every procedure from cold and dark to shutdown after arrival

Tested comparing to latest master during a full flight with a manually programmed MCDU. 

Overall Rating: Good, needs some more tweaks
Conclusions of the testing: Works as described, but FF at CRZ (FL360) is around 2000l/h per engine, N1 of 82.2% seems ok as well. 
Lacks performance above FL270, climb rate is below 500fpm, after FL320 even 200-300fpm. 
Low N1 performance is great, which can be seen during taxiing on idle thrust and during descent. 
Modified coefficient of drag for flaps, speed brake etc is much more realistic, as well as lift and stall speed improvements visible on approach and final. Amazing work overall. 

Engine
Works as described in PR

Aerodynamics
Flaps and pitch attitude throughout flaps works as described on PR

2020-10-14 14:23 UTC, sphectrum commented
Discord: sphectrum#6484
Date of testing: 14/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1295

Testing technique: Gate start/cold and dark, full flight
Steps you've made to test the Pull Request: Every procedure from cold and dark to shutdown after arrival

Tested comparing to latest master during a full flight with a manually programmed MCDU.

Overall Rating: Good, needs some more tweaks
Conclusions of the testing: Works as described, but FF at CRZ (FL360) is around 2000l/h per engine, N1 of 82.2% seems ok as well.
Lacks performance above FL270, climb rate is below 500fpm, after FL320 even 200-300fpm.
Low N1 performance is great, which can be seen during taxiing on idle thrust and during descent.
Modified coefficient of drag for flaps, speed brake etc is much more realistic, as well as lift and stall speed improvements visible on approach and final. Amazing work overall.

2020-10-14 17:04 UTC, donstim commented
Some more charts that should be of some help. I wish I could give a proper attribution. All I remember is they were supplied by a pilot on the Discord channel. Sorry, these are in metric units, and the cruise altitude performance appears to differ a bit from the chart above.

For the maximum altitude chart, I'm not sure what criteria Airbus uses to determine the maximum altitude. Common criteria are either a 100 fpm or 300 fpm rate-of-climb capability remaining with climb thrust or 0 fpm rate-of-climb with cruise thrust.
![Screenshot (38)](https://user-images.githubusercontent.com/70166617/96021624-8f31dd80-0e04-11eb-9725-c391755de1fa.png)
![Screenshot (37)](https://user-images.githubusercontent.com/70166617/96021647-9527be80-0e04-11eb-994c-28d0c3bcb41d.png)
![Screenshot (39)](https://user-images.githubusercontent.com/70166617/96021653-98bb4580-0e04-11eb-945b-e61929e60865.png)

2020-10-14 17:24 UTC, donstim commented
![Screenshot (41)](https://user-images.githubusercontent.com/70166617/96023506-63fcbd80-0e07-11eb-9f2b-5edfbd7854e9.png)
Since the lower speed, lower altitude performance associated with takeoff and initial climb looks pretty good at this point with your thrust mod, I assume you are considering retaining that and only increasing the thrust for higher speeds/altitudes. Since the table has a dependency on Mach, you could probably fashion a curve similar to what you did for N1, where you keep your thrust below a certain Mach and then either blend it back to what it was at higher Machs or maybe even increase it if necessary.

The attached chart may help with determining what Mach number to "blend it back in" or increase it. Since it's probably good up to about 250 KIAS and 5-10,000 feet, maybe retain what you have up to about Mach 0.4? Then around Mach 0.6 it needs to be getting back to what it was or start to increase.

Also, for lower N1s like you would use for descent, I don't think you want to change what you have (at all Mach numbers). Only for higher N1 like would be used for cruise or climb.

2020-10-14 17:24 UTC, MisterChocker commented
@donstim big thanks! btw metric system is better ^^

2020-10-14 19:54 UTC, MisterChocker commented
> Since the table has a dependency on Mach, you could probably fashion a curve similar to what you did for N1, where you keep your thrust below a certain Mach and then either blend it back to what it was at higher Machs or maybe even increase it if necessary.

Can you please explain to me what you mean? I don't understand. And yes it is tricky atm via the N1 to tweak high alt climb speeds etc without rocketing out of the airport.

2020-10-14 20:22 UTC, donstim commented
> > Since the table has a dependency on Mach, you could probably fashion a curve similar to what you did for N1, where you keep your thrust below a certain Mach and then either blend it back to what it was at higher Machs or maybe even increase it if necessary.
> 
> Can you please explain to me what you mean? I don't understand. And yes it is tricky atm via the N1 to tweak high alt climb speeds etc without rocketing out of the airport.

Sure, do you understand how the table is formatted? I assume you do, but just in case...there are sets of 11 numbers separated by commas. The first 11 numbers are the Mach numbers in the table. Actually, the very first number is meaningless. The next 10 are the Mach numbers - 0 through 0.9 by 0.1. For each subsequent group of 11 numbers, the first number is the N1 for that group of Mach numbers. The next ten numbers are the thrust factors for the 10 Mach numbers (0 Mach through 0.9 Mach by 0.1).

So, my thought is to leave the thrust factors for the low N1s (maybe up though 60 or 70?) for all Mach numbers the way you have them. For the higher N1s (above 60 or 70), at Mach numbers of about 0.4 or lower, also no change. But for the higher N1s at higher Mach numbers, increase the thrust factor such that for Machs of 0.7 and above maybe increase the thrust factor above what was in the table before you started. It would probably be best to plot it against Mach number for each of these higher N1s so that this is done smoothly.

Does that make sense?

2020-10-14 20:38 UTC, MisterChocker commented
@donstim but you do talk about this table right? n1_and_mach_on_thrust_table.
Yeah it makes sense, now I got a bit confused there xD
And by increasing the numbers further back (.6, .7, .8, .9) I would assume that it ups the engine's performance at the given mach.

2020-10-14 21:17 UTC, donstim commented
Yes, exactly. I have just taken an initial cut at it by doing the following: At N1s of 70 and above, I made the following changes:
At Mach 0.5 -- Took the average of the thrust factor from your file and the current master
At Mach 0.6 - Used the current master thrust factor
At Mach 0.7 - Used the current master thrust factor increased by 3% (i.e., multiplied it by 1.03)
At Mach 0.8 - Used the current master thrust factor increased by 5% (i.e., multiplied it by 1.05)
At Mach 0.9 - Used the current master thrust factor increased by 5% (i.e., multiplied it by 1.05)

This is just an initial cut - I haven't flown it yet.
I assume these changes to the Thrust-N1 will have an effect on fuel flow, which will have to be dealt with later.
[engines.zip](https://github.com/flybywiresim/a32nx/files/5380921/engines.zip)

2020-10-14 21:26 UTC, MisterChocker commented
Sounds great! I will try this approach and lets see how crazy we need to crank these numbers up xD

2020-10-14 22:49 UTC, donstim commented
Flying now. My first impression is that I definitely overdid it with the higher Mach/higher N1 values. Going to revert back to the original values (before either of our mods) for Mach 0.6 to 0.9 - no 3% or 5% boost and see how that looks.

2020-10-14 23:41 UTC, MisterChocker commented
I have done some more tweaking to the engine performance table.
I still need work on the climb rate.

2020-10-15 00:10 UTC, MisterChocker commented
@donstim I noticed that ECAM shenaniganz too.
I will work on the N1 at cruise and thrust / climb rate tomorrow.

2020-10-15 01:04 UTC, donstim commented
Another chart of interest...
![Screenshot (51)](https://user-images.githubusercontent.com/70166617/96061305-be1d7300-0e47-11eb-847d-d1d02e81ec52.png)

2020-10-15 06:09 UTC, Benjozork commented
@MisterChocker if you are still working on the PR please make it draft.

2020-10-15 06:48 UTC, Benjozork commented
Also, someone has contacted me on discord saying they have been doing engine work for a while now and are concerned about this work being done in isolation.

Are you already present in the Discord server ? I cannot see you there and as such it is causing coordination problems.

I know both of you mean well, but it would be amazing if you two could talk in #engines on Discord and figure out a way to put your efforts together !

2020-10-15 09:45 UTC, MisterChocker commented
@Benjozork I will check the engine discord. Before I started with this I was searching for an issue like that. Since I did not found one I assumed no one was working on that task and I opened an Issue and started working.
I also don't see any Issues in this as we can now share our knowledge.
And how do I make it draft?

2020-10-15 10:03 UTC, MisterChocker commented
This is the current N1 at M0.0. Next step is to figure out an reasonable inclination for M. Below N1 60 caution is needed when increasing M.1 to .3. (This will have huge impact on decent rates)
Whereas above N1 85 will have huge impacts on climb rate.
Also performance on cruise will be between 75 and 85.
![image](https://user-images.githubusercontent.com/1857322/96108193-9678ea00-0edd-11eb-9100-b1a929fd4cc8.png)

2020-10-15 10:11 UTC, MisterChocker commented
@donstim I don't know either.

2020-10-15 14:06 UTC, MisterChocker commented
> ![Screenshot (51)](https://user-images.githubusercontent.com/70166617/96061305-be1d7300-0e47-11eb-847d-d1d02e81ec52.png)

This chart shows max climb thrust... Lads the current version skyrockets at 91% N1 which is waaay to high.
So assuming some of the above charts are obsolete and don't contain information about the LEAP engine, the computers need to be adjusted so that they match the real N1 for TO and CLB.

2020-10-15 14:15 UTC, Benjozork commented
@MisterChocker please provide the discord username you have in our discord server, I'll make sure you get permissions.

Or ping me, someperson#4953

2020-10-15 18:46 UTC, nobodyn0se commented
@MisterChocker I tried the latest commits (15 Oct) climb performance is better. With a GW of 64000kg, VS was around 1500fpm from FL300 - FL330, then 1200fpm till FL370. 
Cruise N1 was 73.8% to 75.3% with a tailwind of 35kts.

2020-10-15 19:17 UTC, MisterChocker commented
@nobodyn0se another commit will come now and then I will PR.
This commit will adjust performances during the entire flight.
From what I tested results are looking insanely good.
I should also note that I have adjusted the thrust per N1 % to further match real life.
In advance I have adjusted the engines performances to work after possible/needed FADAC update.

Further N1 on Approach will match real life on about 40 to 45%.
Take-Off and derated take off performances are possible (performance wise).
Climb performance is reworked.
Fuel burn during cruise may be lower or higher (as a result of fine tuning some parameters)

2020-10-15 19:19 UTC, donstim commented
> @MisterChocker I tried the latest commits (15 Oct) climb performance is better. With a GW of 64000kg, VS was around 1500fpm from FL300 - FL330, then 1200fpm till FL370.
> Cruise N1 was 73.8% to 75.3% with a tailwind of 35kts.

Still looks like too much thrust -- rate of climb still too high and cruise N1 too low
![Uploading Screenshot (55).png…]()

2020-10-15 19:44 UTC, MisterChocker commented
@donstim TOGA on LEAP is N1% 84.

2020-10-15 20:06 UTC, donstim commented
@MisterChocker There isn't just one value for TOGA N1. It varies with altitude, temperature, and bleed condition. See chart.
![Screenshot (57)](https://user-images.githubusercontent.com/70166617/96180400-3ab35e80-0ee7-11eb-82f2-09b7e28890e0.png)

2020-10-15 20:20 UTC, MisterChocker commented
@donstim yes u are right, but currently the airbus decides to use too high N1 % in general an N1 93% TOGA take off would not be possible at most airports because of ALT and/or TEMP. However we are getting N1 TOGA 90+% where as we should only get 84% like EDDM. And when the chart is applied correctly the thrust in the sim should be correct.

2020-10-15 20:37 UTC, donstim commented
Agree that 93% N1 TOGA is too high unless you're taking off out of Lhasa in Tibet or something!  84% is fine for Munich at around 10-12 deg C, but should be higher than that in Denver or at hotter temps for example. Is variation of thrust rating N1 with temp, alt, and bleed condition not possible in MSFS?

Not sure what you mean by "when the chart is applied correctly the thrust in the sim should be correct."

Thrust rating is a different issue than the N1-thrust relationship that you have been working on. For operation at the ratings (TOGA/FLEX, CLB, MCT), displayed N1 should be at the rating, then thrust for climb rate/takeoff acceleration/etc is from N1-thrust. When under speed control like in cruise, then the thrust to hold that speed will be related to N1 by N1-thrust and that N1 will be shown in the display.

2020-10-15 20:47 UTC, MisterChocker commented
> Not sure what you mean by "when the chart is applied correctly the thrust in the sim should be correct."

I meant operating within N1 limits for various stages.

2020-10-16 04:52 UTC, donstim commented
Did you increase ground idle thrust further than you had done originally? It may have just been me and my one test, but it seemed like I had to be on the brakes frequently to maintain a reasonable taxi speed. Test done at KSEA.

Overall, I think this will be a nice improvement for most people. Compared to the book, though, I found it a bit over-powered. Climb rate was higher than book, cruise N1 was low with fuel flow high, and I could get to over 41,000 feet with some residual climb capability at M0.78 at around 70 tonnes when the max cruise altitude should be about 38,4000 ft at that weight, altitude, and speed. But how close are we trying to get?

Screenshots below of initial climb (should have been at 300 knots instead of 250 for those altitudes, darn it), and some cruise conditions after taking off at around 60 tonnes. Last couple where you can see the weight are around 70 tonnes, including the one showing the airplane above 41,000 feet.

It was a bit hard to do the altitude and climb capability tests. The darn autopilot kept increasing speed beyond the selected speed, so I ended up having to turn it off and fly pitch myself so I could hold the right speed.
![Screenshot (75)](https://user-images.githubusercontent.com/70166617/96214560-9229ec80-0f30-11eb-99b7-f7f281e1201d.png)
![Screenshot (76)](https://user-images.githubusercontent.com/70166617/96214575-9b1abe00-0f30-11eb-82cd-caf7a5ea6f3f.png)
![Screenshot (77)](https://user-images.githubusercontent.com/70166617/96214582-9fdf7200-0f30-11eb-95eb-ba883e6aed9f.png)
![Screenshot (78)](https://user-images.githubusercontent.com/70166617/96214596-a66de980-0f30-11eb-90f8-abbc3416d9cd.png)
![Screenshot (79)](https://user-images.githubusercontent.com/70166617/96214608-ad94f780-0f30-11eb-8cf1-1a39d5b3d984.png)
![Screenshot (80)](https://user-images.githubusercontent.com/70166617/96214619-b5549c00-0f30-11eb-97c6-7d84f9dfc5e0.png)
![Screenshot (81)](https://user-images.githubusercontent.com/70166617/96214629-bab1e680-0f30-11eb-9ad3-3defe9442327.png)
![Screenshot (82)](https://user-images.githubusercontent.com/70166617/96214638-c00f3100-0f30-11eb-9123-4c250aa2b5c9.png)

2020-10-16 08:30 UTC, nobodyn0se commented
I flew the same flight with the newest commit, this time with a GW of 62000kg, CG 33.6%MAC (close to last flight's 33.81%). FL100-FL230 @ 2500-3200 fpm. 
FL230 - FL330 @ 2100 - 2800 fpm. FL330 - FL370 @ 1500 - 1900 fpm. 
CLB N1 commanded/engine operating thrust at 91.4% throughout climb phase. 
CRZ N1 in range 68.7% to 70.4% with 52kts tailwind. 
Cruise TAT : -21C

2020-10-16 13:16 UTC, MisterChocker commented
@donstim @nobodyn0se Thanks for testing! I have already worked on the taxiing issue. Now working on climb and cruise performance.

2020-10-16 16:58 UTC, MisterChocker commented
Please wait with testing until next commit.

2020-10-16 18:29 UTC, nobodyn0se commented
Roger, on standby.

2020-10-16 20:33 UTC, MisterChocker commented
Okay open for test now. I have squeezed every little bit out my performance table.

2020-10-16 23:56 UTC, donstim commented
I'm still needing frequent brake application to check taxi speed. Not being a pilot, I can't comment on whether that is realistic or not.

Climb rates through 25,000 feet covered by the climb rate table above still looked too high. Cruise altitude limit at 70,000 kg was pretty darn good. Had a lot of trouble with cruise checks (as well as climb and descent rates) due to the autopilot/autothrottle as well as the PFD airspeed display. Either the Mach-CAS conversion is just flat wrong, or the updating of the calc is too slow.  For example, at 29000 feet, at M0.78, it should be 302 KCAS (from the cruise table above or any online calculator), but MSFS wanted 308 KCAS (as I remember, screen shot below). For climb and descent (in the Mach regime at least), besides the bugged speed being wrong for that Mach, the autopilot climbed at a 10 knot faster speed and descended at a 10 knot slower speed.

All cruise points were done with autopilot in heading and altitude hold, autothrust off. Cruise ceiling was checked with autopilot off. Most tests around 60,000 kg, last few at 70,000 kg

Climb rate through 6000 feet
![Screenshot (101)](https://user-images.githubusercontent.com/70166617/96322873-b12b8b80-0fcf-11eb-871c-036f0ccc60c1.png)
7000:
![Screenshot (102)](https://user-images.githubusercontent.com/70166617/96322892-c2749800-0fcf-11eb-9f44-4c6a15f47cc2.png)
9000:
![Screenshot (103)](https://user-images.githubusercontent.com/70166617/96322913-d02a1d80-0fcf-11eb-9409-1d825b306aed.png)
25000:
![Screenshot (106)](https://user-images.githubusercontent.com/70166617/96322944-ec2dbf00-0fcf-11eb-99b8-82f8f5e7b42d.png)
At 29,000 feet, M0.78 should be 302 KCAS. Instead MSFS thinks 302 KCAS is M0.764:
![Screenshot (107)](https://user-images.githubusercontent.com/70166617/96322993-1c755d80-0fd0-11eb-930f-dce40e0bfc8d.png)
Cruise check at 35,000 feet, M0.78, 69,5000 kg:
![Screenshot (116)](https://user-images.githubusercontent.com/70166617/96323071-7bd36d80-0fd0-11eb-8b24-b06748c784de.png)

2020-10-17 00:23 UTC, MisterChocker commented
@donstim hmm yeah the vs are too high because of the low GW.
Without FADEC no change dealing with it.
To be honest the current N1s during take off and climb are actually not within limits, but I sadly have no control over that so I had to find a compromise and the result can be seen.
Climb rates should look better with GW closer to 70t.

2020-10-17 00:25 UTC, joniatus commented
Fuel flow seems much lower than previous iteration

2020-10-17 00:25 UTC, MisterChocker commented
At least engine N1 and fuel flow seems good xD Haven't tested below FL370 xD

2020-10-17 00:28 UTC, MisterChocker commented
@joniatus for reference see this [chart for cruise](https://user-images.githubusercontent.com/70166617/96021647-9527be80-0e04-11eb-994c-28d0c3bcb41d.png)

2020-10-17 00:34 UTC, joniatus commented
Oh yeah I have no idea what's right it wrong just pointing it out.  Thanks for doing this tho, it was soo needed!

2020-10-17 02:47 UTC, eagle7907 commented
IRL A320 pilot here.  The taxi thrust seems a bit too much.  With default load and fuel, it taxis like an empty A319.  Also I got overtemped engines as high as 920 degrees during climb below 10000ft.  Normally they would be 700-800 degrees for LEAP engines.  Also the actual thrust seems to be a bit high as well.  Yes, the N1 looked normal, but what the airplane was doing seemed like a rocket ship.

2020-10-17 03:09 UTC, danbw9 commented
Just some quick comments here, before I test this even more tomorrow and report back in detail. As IRL pilot and flown ceo IAE, CFM and NEO PW, I can say that the taxi speed you get with power on idle thrust is way too high (even for IAE ceo engines) as is mentioned above...

CLB performance is great and a lot more realistic but it still climbs at CRZ speed but I saw another PR for that - changing the flight phase speeds.

On final I was setting a normal speed that would work before the PR and when selecting Vapp or just below (typically do to get 2.5-3 nose pitch up), it would pitch up to 5 degrees so i would have to increase by 5-8 knots to get the correct pitch. Then every time I would end up floating. So that needs to be worked on. How it behaved before was a lot better apart from the aileron control freeze in ground effect.

2020-10-17 16:32 UTC, FlyingCarpet7 commented
I can give a few comments as well, as a Leap driver.
Taxi thrust on idle is a bit high, but not way to high. At lower weights you do not need break away thrust to get moving, at higher weights you do on a flat surface. but then idle is sufficient to get up to taxi speed. When not so heavy, specially after landing, you often have to break numerous times during taxi to stand, to get speed below 30 kts. 

Made a flight at TOW 71 tons.
Initially takeoff acceleration and climbout seemed ok. During final climb it seemed to be a bit under powered.

**Climb:**

![Climb perf](https://user-images.githubusercontent.com/71129337/96347719-e0133180-10a3-11eb-94e7-45cee729ae61.png)

![clb perf 2](https://user-images.githubusercontent.com/71129337/96347743-fe792d00-10a3-11eb-8b8a-0599ecc23707.png)

I would like to se a few hundreds more on vertical speed at this stage.

**During cruise:**

![CRZ perf](https://user-images.githubusercontent.com/71129337/96347807-4e57f400-10a4-11eb-845b-ec958b1f1dc2.png)

Using a in flight performance calculator I get the following values with 71 tons, speed .78, FL370, ISA:
FF 1028 KG/H/ENG (all eng 2056)
N1 83.1 %
CAS 252 

The **attitude** is to high of course. Normal cruise attitude would be ~2,5-3 deg up.
Same goes with approach attitude.

**Spoilers** is still to effective. I would say it should be almost half as effective as it is now.
(In the 320 with AP engage it will give you maximum half spoiler deflection, but that is a side note)

![SPEED BRK](https://user-images.githubusercontent.com/71129337/96348028-32ede880-10a6-11eb-843f-f56bdad055dc.png)

2020-10-17 16:32 UTC, nobodyn0se commented
Cruise performance is impressive. Flew with a GW of 58000kg, climbed to FL330 with 1500-1900fpm at higher FLs. 
With a CG of 33%, the CRZ N1 was around 78.3% to 79.4% which is close to 78.7% according to the cruise performance table above.
Will try taxiing with higher GW to see how fast the aircraft accelerates on idle thrust.

2020-10-17 19:20 UTC, CBGonzalez commented
I did some tests based on the cruise table above: for 68000kg, FL370 the numbers are pretty good (I get N1 around 82 - 83, fuel flow around 952.5 kg/h/engine.
For other levels / weights not so close (probably more related to the flight model than engines though): 76000, FL 310 get  a good N1 (around80 -81) ff though way lower than table: 916kg/h/engine. Again maybe the flight model (drag, attitude etc).
Also did a ISA10 takeoff fromsea level up to FL390, 66000kg, 250/300/0.78. It only used 760 kg fuel (I expected close to double that based on some A320 tables I have, probably CEO not NEO). 
Just to let you know, not complaining, I appreciate the results!
Btw, we really need some way to automate these tests, so boooring! :-)

2020-10-17 19:52 UTC, Watsi01 commented
Hi @MisterChocker , I don't know if this is important, regarding your PR. But did you see that wpine215 added new Asobo original files?

https://github.com/flybywiresim/a32nx/commit/b26cf27c24d55f7fd9a9577e790653c4f38c9b85 

The third one (target_performance.cfg) could be interesting for you...

2020-10-17 21:09 UTC, MisterChocker commented
thanks for all your testing, but we ran into a problem..

Because we have no working FADEC, the airplane does not "balance" the thurst e.g. on Take-off or climb.
GW 71 tons: climb speeds are looking good and also lacking performance FL300+
GW 65 tons: TO and climb speeds are waaaaaay to high.
I am really sorry but at the current state with no fadec I simply can not balance this issue.
So we will have A way to much thrust or B not enough thrust.
As you are all RL pilots you may have noticed that the N1 % exceeds limits most the time. Again I can not do anything against this since we don't have a working FADEC (at least not yet). 

### List of changes I have already done and will come with next commit:

- Engine performance:
  - On ground:
I have further reduced idle thrust for taxiing
- Aerodynamic:
  - In cruise:
I have increased the lift coef for cruise flight, but this also influences general lift.
If this parameter will be increased any further then now, pitch on landing/approach is too low and climb speeds are higher)
  - Approach:
Reworked config for FLAPS
 - Spoilers:
I have reduced the spoiler affects

### List of whats not working correctly
Displayed speeds calculated by the MCDU are too high. e.g. VApp for 59.5t was 149 or 151 instead of 124+5. Same for other weights. (for reference see chart below)
Also S and F speeds seem to be buggy.

Chart for Operating Speeds
![image](https://cdn.discordapp.com/attachments/749050295606050896/767081784265408584/IMG_20201017_194854.jpg)

2020-10-17 21:11 UTC, MisterChocker commented
> Hi @MisterChocker , I don't know if this is important, regarding your PR. But did you see that wpine215 added new Asobo original files?
> 
> [b26cf27](https://github.com/flybywiresim/a32nx/commit/b26cf27c24d55f7fd9a9577e790653c4f38c9b85)
> 
> The third one (target_performance.cfg) could be interesting for you...

oh hell no.. I have been working on the last version which I will push all day long, lets hope there is no interference.
But thanks for letting me know!

2020-10-18 00:37 UTC, donstim commented
> Hi @MisterChocker , I don't know if this is important, regarding your PR. But did you see that wpine215 added new Asobo original files?
> 
> [b26cf27](https://github.com/flybywiresim/a32nx/commit/b26cf27c24d55f7fd9a9577e790653c4f38c9b85)
> 
> The third one (target_performance.cfg) could be interesting for you...

Just to put everyone's mind to rest, I don't think that should matter at all. First, it's just copying over what's already in the vanilla A320 version, so it was already being applied to the mod. Second, according to the SDK, that file should have no influence on flight behavior. It just allows a comparison between expected (target) performance and computed performance. It puts both sets of data in a csv file that can be put into Excel for easy comparison.

2020-10-18 01:22 UTC, donstim commented
> Displayed speeds calculated by the MCDU are too high. e.g. VApp for 59.5t was 149 or 151 instead of 124+5. Same for other weights. (for reference see chart below)
> Also S and F speeds seem to be buggy.
> 
> Chart VLS
> ![image](https://camo.githubusercontent.com/a83a0b6e9b24fb44f7db9308e3e437082367e3eb/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3734393035303239353630363035303839362f3736373134383035303534333431313232302f756e6b6e6f776e2e706e67)

I wonder where the MCDU speeds come from? I assume they're Asobo's, but are they in a table somewhere or are they computed?  I checked the "target performance.cfg" file, which lists a "full flap/full weight poweron stall speed" of 114.29 and a "max gross weight" of 174165. That max gw is 79 tonnes, which, using your chart, gives a VLS of about 142. With VLS = (other than when limited by VMC) = 1.23 1-g stall speed, the calculated VLS would be 114.29 x 1.23 or 141, so that seems to match up (assuming their nomenclature of "poweron stall speed" is interpreted to mean 1-g power off stall speed in this case).

What happens if you try landing at the "right" speeds?  Would you need to increase the lift coefficient even further, that is, is it currently about right for the too-high MCDU computed speeds?

I found another issue that was opened a long time ago on the incorreed MCDU speeds. (https://github.com/flybywiresim/a32nx/issues/210) It doesn't appear to have gone anywhere. I am going to comment on it and provide them the VLS chart that they seem to be lacking.

2020-10-18 08:22 UTC, Watsi01 commented
> 
> I wonder where the MCDU speeds come from? I assume they're Asobo's, but are they in a table somewhere or are they computed? I checked the "target performance.cfg" file, which lists a "full flap/full weight poweron stall speed" of 114.29 and a "max gross weight" of 174165. That max gw is 79 tonnes, which, using your chart, gives a VLS of about 142. With VLS = (other than when limited by VMC) = 1.23 1-g stall speed, the calculated VLS would be 114.29 x 1.23 or 141, so that seems to match up (assuming their nomenclature of "poweron stall speed" is interpreted to mean 1-g power off stall speed in this case).
> 
> What happens if you try landing at the "right" speeds? Would you need to increase the lift coefficient even further, that is, is it currently about right for the too-high MCDU computed speeds?
> 
> I found another issue that was opened a long time ago on the incorreed MCDU speeds. (#210) It doesn't appear to have gone anywhere. I am going to comment on it and provide them the VLS chart that they seem to be lacking.

@donstim As a far as I know they are calculated in FMC A32NX_FMCMainDisplay.js and A320_Neo_CDU_MainDisplay.js (both html_ui\pages\vcockpit\instruments\airliners\A320neo\...). The calculations in A320_Neo_CDU_MainDisplay.js seem to override anything in A32NX_FMCMainDisplay.js. I took a look at the flap speeds and Vapp. But not deep enough to understand what's been done there.

2020-10-18 08:25 UTC, 2hwk commented
Discord: 2Cas#1022
Date of testing: 18/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1295

Testing technique: Multiple Cold and Dark started Flights
Steps you've made to test the Pull Request: Cold and dark start to landing and arrival at gate. No ground services. 

Overall Rating: Good
Conclusions of the testing: Works as described.
Low N1 performance now seems correct. Rest may need work as above, am not a pilot.

2020-10-18 11:52 UTC, MisterChocker commented
@donstim 
> What happens if you try landing at the "right" speeds? Would you need to increase the lift coefficient even further, that is, is it currently about right for the too-high MCDU computed speeds?

When using the right speeds at landing pitch is about 2 to 3.5 degree.
Using mcdu calculated speeds pitch is close to 0 or negative.

2020-10-18 13:05 UTC, Watsi01 commented
@MisterChocker Lowering thes VLS value could be done easy. But I read somewhere that the vanilla flight model stalls way to early? This could be bad, if we change these values to more realistic ones.

2020-10-18 13:10 UTC, MisterChocker commented
@Watsi01 yes, but not in this pr

2020-10-18 13:11 UTC, Watsi01 commented
> @Watsi01 yes, but not in this pr

Yeah, I know. Would make a new PR if this change is wanted.

2020-10-18 13:12 UTC, MisterChocker commented
> Yeah, I know. Would make a new PR if this change is wanted.

I believe it's necessary. Let's wait and see what the pilots say.

2020-10-18 13:15 UTC, MisterChocker commented
@Watsi01 Also as a reminder, the model in pr stalls after the first dashed line (don't know how its called) [see image for refernce](https://cdn.discordapp.com/attachments/749050295606050896/766994187408506880/unknown.png)

2020-10-18 13:19 UTC, Watsi01 commented
> 
> 
> @Watsi01 Also as a reminder, this model stalls after the first dashed line (don't know how its called) [see image for refernce](https://cdn.discordapp.com/attachments/749050295606050896/766994187408506880/unknown.png)
> (I know its supposed to stall in the solid red range but still a huge improvement, but I will work on this for a later build)

That helps, when fiddling around with the speeds. Thanks.

2020-10-18 13:25 UTC, MisterChocker commented
Basically the actual speeds can be used and are needed :p

2020-10-18 14:28 UTC, FlyingCarpet7 commented
So correct speeds and stall early or to high unrealistic speeds...
Probably a new PR and try to solve both speeds and stall characteristics?
Of course we are missing things on the speed tape as well. Between VLS and alpha max there should be alpha prot.

2020-10-18 15:19 UTC, Watsi01 commented
> 
> 
> So correct speeds and stall early or to high unrealistic speeds...
> Probably a new PR and try to solve both speeds and stall characteristics?
> Of course we are missing things on the speed tape as well. Between VLS and alpha max there should be alpha prot.

@FlyingCarpet7 Yes, I'm in contact with MisterChocker. I'll make some changes and tests with the vanilla flight model. If this doesn't work out, we have to wait until MisterChockers' PR is merged. Then it should work.

2020-10-19 06:05 UTC, donstim commented
> @Watsi01 Also as a reminder, this model stalls after the first dashed line (don't know how its called) [see image for refernce](https://cdn.discordapp.com/attachments/749050295606050896/766994187408506880/unknown.png)
> (I know its supposed to stall in the solid red range but still a huge improvement, but I will work on this for a later build)

In normal law, it shouldn't stall at all. VLS is the top of the amber band and with A/THR connected, the airplane should not go below this speed, even if a slower target speed is selected (unlike as shown in my screenshot where was simply flying a managed speed approach with autopilot/autothrust on:
![Screenshot (155)](https://user-images.githubusercontent.com/70166617/96406328-0dd7a380-1194-11eb-8dc7-b260471b9a2c.png)

You can go slower if you disengage autothrust, but unless you maintain pressure on the sidestick, it shouldn't go below the yellow-and-black barber pole (alpha prot). If backpressure is maintained and speed is reduced below alpha prot, alpha floor protection is triggered with automatic engagement of autothrust and application of TOGA thrust. Before this happens, though, there will be an aural "speed, speed" warning. If full back stick is maintained, alpha max might be reached, but even then there is still some maneuvering capability. It is still above the stall AOA, so if those wing drops on landing are due to stall, that's just flat wrong.

I assume someone is able to decipher whatever is being used to generate the current amber, yellow-and-black, and red bands on the PFD speed tape and adjust them?  We have VLS info, but does someone have info for where the tops of the yellow-and black and red bands should be located for all of the different flap positions?

2020-10-19 12:56 UTC, MisterChocker commented
@donstim I assume the AOA lift table or parameters in the cfg are totally bs then :(
So real life info about that would be massively helpful altho this might be a TODO for the overall flight model redo.

2020-10-19 18:03 UTC, St54Kevin commented
Just did a short test flight together with #1389 speed tweaks. It went very well. Waaaay better and believable than default. Engine performance is veeeery nice. On ground as expected and also climb (20min till FL340 is veeery real). we already spoke about other tweaks in discord (mainly pitch adjustments, In flight Idle too low). Good base I think

2020-10-19 20:36 UTC, ChruutvoLuzi commented
(Note: i am not an official qa tester but still want to test and help out :D)
Name: ChruutvoLuzi | SD-PB.ch#8902
Date of testing: 19/10/2020
Version of the sim: 1.9.5.0
PR Tested: #1295

Testing technique: Full Flight with OFP from SimBrief+Navigraph

Steps made to test the Pull Request:

Loaded C&D
Entered FP from ESSA to ENBR on CRZ FL360
Flew the entire flight

Overall Rating: Good
Conclusions of the testing: Aircraft lift coefs feels much more "believable". The Aircraft rotates very well now and climbs good to decent throughout the climb phase. Pitch on Cruise looked fine. Airbrakes are now occasionally needed in order to slow the plane down and sink. Only negative point i have is the Vls that is too high (GW 60t Vls=142(MCDU auto entry) and pitch was at ~-2).However, i know you guys are already working on it) Stall characteristics are better now (doesnt stall and bank anymore above 130kts with flaps full while flaring).
Gj Guys

2020-10-19 20:44 UTC, MisterChocker commented
@ChruutvoLuzi You are right, we are testing S, F, VApp and VLS right now.

2020-10-19 22:01 UTC, Benjozork commented
@MisterChocker now that the new VSpeeds PR is merged, would it be relevant to rebase this one on those changes ? I am able to do that for you if you do not know how.

2020-10-19 22:14 UTC, MisterChocker commented
> @MisterChocker now that the new VSpeeds PR is merged, would it be relevant to rebase this one on those changes so that it can be tested while taking those into account ? I am able to do that for you if you do not know how.

Already did ;)

2020-10-20 17:19 UTC, henrikx commented
Just did a test with the newest master and this merged. Still had #1173, however it was not that severe and I was able to recover and still land. Still had to apply full right aileron though.

2020-10-20 17:21 UTC, FlyingCarpet7 commented
Hi!
I tested climb performance and compared to real performance calculator. Climb rate and times are very accurate! Fuel used does not work I guess? The attitude both in CRZ and AAPP seems reasonable.
Se my table below and compare numbers.
![CLB Performance](https://user-images.githubusercontent.com/71129337/96621708-40ef7380-1309-11eb-9bf7-d13acc35fffb.png)

2020-10-20 18:59 UTC, Watsi01 commented
@FlyingCarpet7 This looks good, I think.

2020-10-20 19:03 UTC, MisterChocker commented
@FlyingCarpet7 thanks for this nice comparison!
Yes N1% is wrong, we have no control over that.
And S, F, VApp und VLS are actually done, but I have to solve an issue first before I can commit.
Also CDU and PDF will then show the same speeds ^^
Fuel flow seems odd hmm.

2020-10-20 20:52 UTC, Oberstumfuher commented
And you need to adjust your fuel consumption, because at the moment you are spending more than 50KG per minute, often it reaches 60KG, the correct thing is to stay around 35, 37KG per minute on cruise.

2020-10-20 21:18 UTC, donstim commented
Just looking at @FlyingCarpet7 's results, it looks like the fuel flow in the mod is currently tailored to match at cruise altitudes, which isn't all bad. The spot check at FL390 ain't that bad. The climb from FL350 to 370 only uses 10 (is that kg or lbs) less than the calculator shows and from FL300 to 350 is only off by 60. It is worse at lower altitudes, but does that matter as much? Also, did you start your test on the runway, or is some startup and taxi fuel included, which might affect the comparisons?

@Oberstumfuher Are you sure you are using the PR mod version?

2020-10-20 21:23 UTC, MisterChocker commented
Thanks @donstim, as I have already said before this is the best result so far (because this is a compromise, an exact engine model will follow)

2020-10-20 21:37 UTC, Oberstumfuher commented
> Just looking at @FlyingCarpet7 's results, it looks like the fuel flow in the mod is currently tailored to match at cruise altitudes, which isn't all bad. The spot check at FL390 ain't that bad. The climb from FL350 to 370 only uses 10 (is that kg or lbs) less than the calculator shows and from FL300 to 350 is only off by 60. It is worse at lower altitudes, but does that matter as much? Also, did you start your test on the runway, or is some startup and taxi fuel included, which might affect the comparisons?
> 
> @Oberstumfuher Are you sure you are using the PR mod version?

With FL390 spending 58KG don't you think too much ?? as I said earlier, on "cruise", I was supposed to be spending about 35, 33 KG per minute

2020-10-20 21:58 UTC, donstim commented
> > Just looking at @FlyingCarpet7 's results, it looks like the fuel flow in the mod is currently tailored to match at cruise altitudes, which isn't all bad. The spot check at FL390 ain't that bad. The climb from FL350 to 370 only uses 10 (is that kg or lbs) less than the calculator shows and from FL300 to 350 is only off by 60. It is worse at lower altitudes, but does that matter as much? Also, did you start your test on the runway, or is some startup and taxi fuel included, which might affect the comparisons?
> > @Oberstumfuher Are you sure you are using the PR mod version?
> 
> With FL390 spending 58KG don't you think too much ?? as I said earlier, on "cruise", I was supposed to be spending about 35, 33 KG per minute

@FlyingCarpet7 's results are nowhere near 58 kg/min. He got 920 kg/hr/engine, which is 31 kg/min for the airplane. That's why I asked if you were using the latest PR version.

2020-10-20 22:10 UTC, Oberstumfuher commented
> > > Apenas olhando para @FlyingCarpet7 resultados, parece que o fluxo de combustível no mod é atualmente adaptado para corresponder em altitudes de cruzeiro, o que não é tão ruim. A verificação na HORA NA FL390 não é tão ruim. A subida de FL350 para 370 usa apenas 10 (é que kg ou lbs) menos do que a calculadora mostra e de FL300 para 350 só está fora por 60. É pior em altitudes mais baixas, mas isso importa tanto? Além disso, você começou seu teste na pista, ou alguma startup e combustível de táxi está incluído, o que pode afetar as comparações?  @Oberstumfuher Tem certeza que está usando a versão PR mod?
> > 
> > 
> > Com fl390 gastando 58KG você não pensa muito ?? como eu disse anteriormente, em "cruzeiro", eu deveria estar gastando cerca de 35, 33 KG por minuto
> 
> @FlyingCarpet7 Os resultados não estão nem perto de 58 kg/min. Ele tem 920 kg/h/motor, que é 31 kg/min para o avião. É por isso que eu perguntei se você estava usando a versão mais recente pr.

I already tried the DEV version, this one, and now I have version 0.4.0, one thing I can say categorically, neither of the two versions the autopilot is centered with the track, it is always left or right, and sometimes outside runway, not to mention that the landing is like a meteorite falling on asphalt, rsssss. When MSFS was in version 1.7.42, I think it was that, before 1.8, A3nx was perfect, 100% functional autopilot, after they updated the game it was never good.

2020-10-20 22:35 UTC, FlyingCarpet7 commented
@donstim 
I started on the runway.
Fuelburn during the initial part of the climb matters a lot. There is where you spend the most of your fuel if you have a shorter flight.
I got the feeling that the fuelflow is not using up the correct amount of fuel..used indication seems to match what’s in the tanks, but it should be less fuel left in there...how is the sim calculating fuel used right now? Anyone that can find that calculation?

2020-10-20 23:00 UTC, MisterChocker commented
Speeds for approach are now calculated accordingly to [VLS](https://camo.githubusercontent.com/a83a0b6e9b24fb44f7db9308e3e437082367e3eb/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3734393035303239353630363035303839362f3736373134383035303534333431313232302f756e6b6e6f776e2e706e67) and [OPERARING SPEEDS](https://camo.githubusercontent.com/8d5dcd34a6f9554a6a9b253e47b12ed0a0b5a082/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3734393035303239353630363035303839362f3736373135303331323831363930323134342f756e6b6e6f776e2e706e67).

2020-10-21 00:00 UTC, nonocaptain commented
Hello and thank you for your amazing work it is really a change on the flight model !! I noticed that the A.FLOOR protection is extremely high on take-off forcing to reach at least 160 knt or even 180 is this normal? on the previous version it seemed weaker

2020-10-21 00:25 UTC, MisterChocker commented
> Hello and thank you for your amazing work it is really a change on the flight model !! I noticed that the A.FLOOR protection is extremely high on take-off ( tested with conf 1+f GW 65.5t) forcing to reach at least 160 knt or even 180 is this normal? on the previous version it seemed weaker

I am working on this right now since the speeds have changed.
Also F-Speed on approach is currently within or below ALPHA PROT.

2020-10-21 06:01 UTC, donstim commented
> @donstim
> I started on the runway.
> Fuelburn during the initial part of the climb matters a lot. There is where you spend the most of your fuel if you have a shorter flight.
> I got the feeling that the fuelflow is not using up the correct amount of fuel..used indication seems to match what’s in the tanks, but it should be less fuel left in there...how is the sim calculating fuel used right now? Anyone that can find that calculation?

I guess I need to explain my comment about cruise vs initial climb fuel further. Considering what seems to be available to us at this time for this sim and this PR, I would much rather match cruise fuel flow than initial climb fuel flow. Because it seems to be one or the other. Undless @MisterChocker  has some further tricks up his sleeve, based on comments on the Discord channel about the engine model, it does not seem possible right now to match very far off of **one** condition. There seem to be two fuel flow variables he is changing, and I have not been able to find any explanation in the SDK for exactly how they are used. Neither the normal fuel flow vs N2 table, nor the TSFC value seem to have any effect in the modern flight model.

As for the fuel used calculation, I think it appears to be correct. I flew your conditions and took screen shots of each altitude so I have fuel flow, the time, and the fuel used values for each. At TOGA thrust, the fuel flow value was 1234 kg/hr, which went down to around 1100 with climb thrust rising to about 1200 again near FL390.  So, it varied from about 18-20 kg/min/eng throughout the climb, which is pretty much what you showed.  Obviously, it should be higher, but I don't think it should be done at the expense of sacrificing cruise fuel flow accuracy.

2020-10-21 06:22 UTC, theersink commented
> @donstim
> I started on the runway.
> Fuelburn during the initial part of the climb matters a lot. There is where you spend the most of your fuel if you have a shorter flight.
> I got the feeling that the fuelflow is not using up the correct amount of fuel..used indication seems to match what’s in the tanks, but it should be less fuel left in there...how is the sim calculating fuel used right now? Anyone that can find that calculation?

I noticed this too. Right now according to average fuel used max range with full tanks would be almost 5000mi/10hrs. This is based on average fuel used during 3 flights. Noticed the climb fuelburn was low, climbing out of Orlando to 34000ft only burned about 1000kg

Flightmodel feels really good all around but the fuel usage is low even though the indicated FF in sim is within range. 

fuel_flow_scalar in engines.cfg can be adjusted to increase total fuel usage but this scales FF indicated as well and is used across all FF scenarios so your total range and fuel used is on track but your individual phases it puts out of sync with real world values. I have hunted around for other setting directly controlling fuel usage and could not find anything other than this.

2020-10-21 10:52 UTC, MisterChocker commented
@theersink adjusting FF has impact on engine thrust.

2020-10-21 18:22 UTC, ohnoitsBlarry commented
> fuel_flow_scalar in engines.cfg can be adjusted to increase total fuel usage **but this scales FF indicated as well** and is used across all FF scenarios so your total range and fuel used is on track but your individual phases it puts out of sync with real world values. I have hunted around for other setting directly controlling fuel usage and could not find anything other than this.

Is fuel flow defined entirely in the engines.cfg, or do we have any ground to work on with JS? Because implementing altitude-based fuel flow factors should be difficult within the confines of a .cfg file. Or maybe is there a way to externally define global variables to be used in FS' config files?

2020-10-21 19:04 UTC, MisterChocker commented
> Is fuel flow defined entirely in the engines.cfg, or do we have any ground to work on with JS? Because implementing altitude-based fuel flow factors should be difficult within the confines of a .cfg file. Or maybe is there a way to externally define global variables to be used in FS' config files?

@ohnoitsBlarry to my knowledge it is impossible to have fuel flow for different conditions (at the moment). 
Please see engine channel in our discord for further info.

2020-10-21 21:09 UTC, MisterChocker commented
So guys you can now test this version and hopefully after testing we are green for merge.
Thanks to all of you guys! You helped us massively with all the testing and suggestions, it truly had/has an huge impact to the quality of development.

I have done some work on the Alpha Protection by arranging two values in the fm cfg file.
Unfortunately on quick rotation on take off you will be within the Alpha Prot and I don't see a way to prevent this.
(well 5 knots higher vr and v2 would help for sure)
In my opinion this is an issue for the future flight model.
In terms of fuel flow not reacting to conditions, we will have to wait for the new engine model to solve this.

It is not me being lazy, it's impossible right now until we have our own FADED.

2020-10-21 22:20 UTC, aviationenthusiast commented
Great work! I noticed something weird though. Is the aircraft supposed to taxi forward even if on reverse thrust like this? Even at 31%+ reverse thrust it still moves forward from a complete stop.
https://vimeo.com/470775764

2020-10-21 23:02 UTC, MisterChocker commented
@aviationenthusiast never had it before, even backed up for testing with reverses. Hmm...

2020-10-22 04:18 UTC, theersink commented
> So guys you can now test this version and hopefully after testing we are green for merge.
> 
> I have done some work on the Alpha Protection by arranging two values in the fm cfg file.
> Unfortunately on quick rotation on take off you will be within the Alpha Prot and I don't see a way to prevent this.
> (well 5 knots higher vr and v2 would help for sure)
> In my opinion this is an issue for the future flight model.
> In terms of fuel flow not reacting to conditions, we will have to wait for the new engine model to solve this.
> 
> It is not me being lazy, it's impossible right now until we have our own FADED.
> 
> Thanks to all of you guys! You helped us massively with all the testing and suggestions, it truly had/has an huge impact to the quality of development.

So I did do some testing as another thread we were discussing fuel_flow_scaler in #1166. I do not think that this setting in any way affects thrust values at all. I ran 1 test with it set on 0.01 and loaded up full fuel and max payload, 200lbs under MTOW. That setting should have severely limited my power to the point of not being able to do much but I was able to TO and climb and all engine parameters were within your PR  specs except Fuel Flow which at full climb showed 12 (again fuel_flow_scaler is at 0.01). 

Ran it twice just to be sure but that setting only appears to be linked to total fuel usage/range and scales the indicated FF without touching the power curve so this could be used optionally, right now it is an either or. Correct range (Still tweaking to find best scaler setting but I think it may be 1.462) OR correct indicated FF. 

Anyhow just wanted to share this, it may help for the mod in the future. 

Awesome job on this. How it should have been from launch. You sir are a steely eyed missile man.

2020-10-22 04:53 UTC, aviationenthusiast commented
> 
> 
> @aviationenthusiast never had it before, even backed up for testing with reverses. Hmm...
> Well that looks odd, but we discovered that the reverse thrust translation from input is not correctly implemented in the current sim ^^. Idle reverse therefore might be lower then it should be and now u just roll down a slope.
> 
> CFM56 idle reverse is N1 ~31%. (Correct me if I am wrong, that's what I remember)

Is there a way to correct that behaviour?:/

2020-10-22 06:49 UTC, theersink commented
> Great work! I noticed something weird though. Is the aircraft supposed to taxi forward even if on reverse thrust like this? Even at 31%+ reverse thrust it still moves forward from a complete stop.
> https://vimeo.com/470775764

I am not getting this behaviour. I have done about 6 flights or so and the reversers work perfectly. Just to be sure I taxied around KDEN on reversers. It may be a control config issue or something is off on you install. I was unable to replicate this.

2020-10-22 07:36 UTC, lve0200 commented
> So guys you can now test this version
How can _**I**_ test, when it is not merged??

![image](https://user-images.githubusercontent.com/47894777/96839844-ffb2ad00-1449-11eb-821c-1dc7e2f6f979.png)

2020-10-22 10:21 UTC, MisterChocker commented
> ## How to download the PR for QA
> Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
> The build.py will have already been run with the latest changes, so no need to rerun it once you download the zip.
> 
> 1. Make sure you are signed in to GitHub
> 2. Click on the **Checks** tab on the PR
> 3. On the right side, slick on the **Artifacts** drop down and click the **A32NX** link

@lve0200

2020-10-22 10:23 UTC, MisterChocker commented
> > @aviationenthusiast never had it before, even backed up for testing with reverses. Hmm...
> > Well that looks odd, but we discovered that the reverse thrust translation from input is not correctly implemented in the current sim ^^. Idle reverse therefore might be lower then it should be and now u just roll down a slope.
> > CFM56 idle reverse is N1 ~31%. (Correct me if I am wrong, that's what I remember)
> 
> Is there a way to correct that behaviour?:/

@aviationenthusiast yes, code our own FADEC, right now we are doing all sorts of research to do so.

2020-10-22 12:31 UTC, St54Kevin commented
Did a quick test flight. Things I noticed:
- Managed speed for climb after takeoff was S speed again. Should be 250 or a speed constraint with CLB detent. My SID didnt have a constraint
- Vapp calculation was wrong initally. I had 60T GW and landing on runway 23 with wind 230/16 selected. Vapp in MCDU was 140, Vls 126. Later on final it corrected itself to 131, which was correct. But it should be there from the beginning.
- Speed and Thrust wise, everything else was very nice

2020-10-22 14:34 UTC, danbw9 commented
To add to my previous comment and also those of others, I have been flying with the PR a couple times now and it handles very nicely. 

As @St54Kevin mentioned above, the Vapp speed seems to change along the approach (could be to do with current configuration? changing flap settings), and the suggested VAPP worked pretty well for a 2.5 degrees NU attitude on final. Having mostly flown A321 I cannot speak for how accurate the Vapp speeds are, they just seem low to me. VLS and VAPP should have the difference of 5 knots which the MCDU shows correctly but the PFD speed tape does not reflect this. See attached images. 

Will try with different payloads, ones that are perhaps more accurate to real world - and see how it handles. The default payload is not very high so the idle thrust taxi speed actually makes sense if that is left untouched. 

![Screenshot (381)](https://user-images.githubusercontent.com/1753445/96886808-3ad1d200-1484-11eb-9819-900a31e6c446.png)

![Screenshot (380)](https://user-images.githubusercontent.com/1753445/96886833-432a0d00-1484-11eb-9a08-42b5c9fb62d6.png)

2020-10-22 14:58 UTC, St54Kevin commented
@danbw9 On your Screenshots you are in speed selected mode, not in managed. Of course there is no Vapp Spees then

2020-10-22 15:10 UTC, St54Kevin commented
For me this one is good to be merged.

2020-10-22 15:13 UTC, danbw9 commented
@St54Kevin Look at the VAPP speed from MCDU. That will not change if I am in selected speed??

2020-10-22 15:18 UTC, St54Kevin commented
> @St54Kevin Look at the VAPP speed from MCDU. That will not change if I am in selected speed??

Oh I thought you meant the speed tape. No that will of course not change. Why should it?

2020-10-22 15:59 UTC, MisterChocker commented
> I think you missed my point....indicated VLS on speed tape is 111 knots and so with that logic, VAPP should be 116 knots. but MCDU says 125 (and VLS 120)

Again, the speed tape does not reflect the real world, since this flight model is not accurate.

2020-10-22 16:05 UTC, MisterChocker commented
@St54Kevin
> * Managed speed for climb after takeoff was S speed again. Should be 250 or a speed constraint with CLB detent. My SID didnt have a constraint

Don't know why, did not touched it.

> * Vapp calculation was wrong initally. I had 60T GW and landing on runway 23 with wind 230/16 selected. Vapp in MCDU was 140, Vls 126. Later on final it corrected itself to 131, which was correct. But it should be there from the beginning.

I have seen that as well as on approach when FLAPS 3 are selected that managed speed will increase by a few knots and VLS and VApp in mcdu are different. (This is only when on FLAPS 3).

2020-10-22 16:06 UTC, St54Kevin commented
> @St54Kevin Look at the VAPP speed from MCDU. That will not change if I am in selected speed??
> 
> I think you missed my point....indicated VLS on speed tape is 111 knots and so with that logic, VAPP should be 116 knots. but MCDU says 125 (and VLS 120)

Oh you referring to the yellow VLS band. Now I get it :D yes that should match you are right. And I don't see the point why the MCDU Vapp should change in selected speed mode.

@MisterChocker Isnt the VLS in the speedtape linked to the calculated VLS in the MCDU?

2020-10-22 16:25 UTC, MisterChocker commented
> Isnt the VLS in the speedtape linked to the calculated VLS in the MCDU?

@St54Kevin currently it's not. The VLS in the speedtape is calculated with simvars, the MCDU uses real tables.

2020-10-22 19:46 UTC, Benjozork commented
LGTM, minor issues that will be fixed with flight model and my personal optimization of PFD elements

2020-10-22 19:46 UTC, merged

2020-10-23 14:37 UTC, dc1ps2 commented
After I updated the A32NX#1295 version, the entire throttle response is very strange. When idling (F1), it will push forward? Unless I reverse the throttle, I can stop. I feel that the throttle position is confused.

2020-10-23 14:46 UTC, lve0200 commented
I think, I remember from old FS9/Phoenix times, that one had to give a little bit throttle to overcome the initial inertia, but then it kept rolling @ idle.

2020-10-23 14:52 UTC, MisterChocker commented
@dc1ps2 0% throttle does not mean 0% acceleration. It does not work like a car.

2020-10-23 23:06 UTC, dc1ps2 commented
> @dc1ps2 0% throttle does not mean 0% acceleration. It does not work like a car. Actually when driving automatic transmission, the car will engage the clutch and start rolling, when the pressure on the brake paddle is lowered.

So now if I want to stop completely, what should I do?

2020-10-23 23:09 UTC, Lessar277 commented
Hit the brakes, then engage the parking brake

2020-10-24 05:15 UTC, St54Kevin commented
> > @dc1ps2 0% throttle does not mean 0% acceleration. It does not work like a car. Actually when driving automatic transmission, the car will engage the clutch and start rolling, when the pressure on the brake paddle is lowered.
> 
> So now if I want to stop completely, what should I do?
> 

It's the same IRL. The plane accelerates with idle. If you have a light aircraft you have to brake a lot while taxiing

2020-10-25 01:08 UTC, Lessar277 commented
@MisterChocker Not sure if I should log a bug for this or not (not a real pilot, no clue how the a/c should behave in this situation): at high temperatures, TO/GA thrust oscillates wildly. See: https://streamable.com/uga58q

The above clip was taken at 37 celsius OAT. For that temperature, FLEX solved the issue for me and stopped the oscillations. However, going up to 45 degrees OAT, FLEX behaves the same as TO/GA. From what I noticed, thrust is reduced in order to keep EGT out of the red. FLEX seemed to have a higher tolerance to red EGT than TO/GA for some reason.

This happened to me regardless of wether I spawned on the runway or cold&dark. Above location is Paro with live weather (I initially thought altitude was the reason), but it's reproducible everywhere, as long as you set temperature from the weather menu.

2020-10-25 10:45 UTC, MisterChocker commented
@Lessar277 we need a FADEC in order to sort that and we are working on that as well.

2020-10-31 22:26 UTC, ElSrJuez commented
I think fuel consumption is still rather high, considering the supposed ~3500nm range for the Neo.
Today I am seeing between 44 and even 80 KG/min @ FL380 on v.0.4.1, more often than not its around **60KG/min**.
This is even higher than v.0.4.0?
![image](https://user-images.githubusercontent.com/44654300/97791211-46b94480-1ba6-11eb-951e-0c4cf2819038.png)

2020-10-31 22:51 UTC, MisterChocker commented
Well then the new MFS update broke something. Wouldn't actually surprise me...

2020-10-31 23:01 UTC, Benjozork commented
@ElSrJuez this change is not present in 0.4.0.

2020-10-31 23:05 UTC, ElSrJuez commented
> @ElSrJuez this change is not present in 0.4.0.



> @ElSrJuez this change is not present in 0.4.0.

Roger that, [I asked on Discord ](https://discord.com/channels/738864299392630914/740722295009706034/772191276132466709l) and was left under the impression that all commits to master were included in 0.4.1.

Anyway, I kind of figured that later... this is planned for 0.5, no?

2020-11-08 21:32 UTC, ElSrJuez commented
Fuel consumption is roughly halved (~30 KG/min) on the current Dev (8-Nov).