[MCDU] V1/VR/V2 logic
flybywiresim/a32nx pull request #1786
Opened 2020-11-07 11:14 UTC by paul92ilm

Fixes #1774 

## Summary of Changes

- Add V1/VR/V2 Disagree logic and message
- Fix minimum range for V1/VR/V2

## Screenshots (if necessary)

![image](https://user-images.githubusercontent.com/9373163/98439412-07cd4680-20f2-11eb-86f8-0e8095597bb0.png)

## References

V1/VR/V2 Logic
![image](https://user-images.githubusercontent.com/9373163/98439531-bf625880-20f2-11eb-95fe-061f35ba5fcb.png)

V1/VR/V2 Disagree message 
![image](https://user-images.githubusercontent.com/9373163/98439439-2af7f600-20f2-11eb-8627-1af7e11c3d92.png)

V1/VR/V2 range
![image](https://user-images.githubusercontent.com/9373163/98439458-4105b680-20f2-11eb-9219-dad0dda8b32e.png)
![image](https://user-images.githubusercontent.com/9373163/98439469-5084ff80-20f2-11eb-848b-bb78291c41d9.png)

## Additional context

Discord username (if different from GitHub): Lussion

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2020-11-07 14:41 UTC, lukecologne commented
The ECAM warning seems to be <ins>T.O.</ins> V1/VR/V2 DISAGREE instead of <ins>CONFIG</ins> T.O. V1/VR/V2 DISAGREE. Source: 
![grafik](https://user-images.githubusercontent.com/39596827/98444034-ab791f80-210f-11eb-9fcc-f66e6c13731d.png)

2020-11-07 14:54 UTC, paul92ilm commented
You're right, i'm fixing it

2020-11-07 15:03 UTC, paul92ilm commented
Fixed
![image](https://user-images.githubusercontent.com/9373163/98444581-b97c6f80-2112-11eb-9a7f-319f8af5b96a.png)

2020-11-07 18:02 UTC, lukecologne commented
The warning should be only one line, not two

2020-11-07 19:05 UTC, paul92ilm commented
![image](https://user-images.githubusercontent.com/9373163/98449519-864ad800-2134-11eb-9de7-32b714c07c78.png)
![image](https://user-images.githubusercontent.com/9373163/98449523-8b0f8c00-2134-11eb-912a-693a025f4f09.png)
Fixed, thanks for your feedback

2020-11-08 00:02 UTC, Benjozork requested changes

2020-11-08 00:02 UTC, Benjozork commented on .github/CHANGELOG.md
> +1. [CDU] Added ability to clear MDA/DH, added input logic for both MDA/DH - @paul92ilm (Lussion)
Changelog lines start with action verbs, "Fix" and "Add" are fine.

2020-11-08 01:01 UTC, Benjozork approved these changes

2020-11-08 01:01 UTC, Benjozork commented
LGTM

2020-11-08 09:52 UTC, beheh commented
Are you sure that the the entry is actually rejected into the MCDU? I see your code does not write the corresponding simvar if the condition does not match, showing just the error message and discarding the input. How would the T.O. check / ECAM message even be triggered if you cannot insert mismatching v speeds?

I would also imagine that a rejected entry leads to a cumbersome situation when updating V speeds - imagine pilots first doing the math for an intersection departure and entering something like 132 134 134, and then switching to full length departure redoing their calculations leading to 135 140 140. They would be unable to enter the 135 as the VR and V2 are smaller and would have to clear them first (is that even possible) or do them in reverse order.

You may want confirmation from a real pilot or at least someone with access to a professional simulator what exactly happens to the entry in the scratchpad.

2020-11-08 11:27 UTC, paul92ilm commented
If TO data change, the "CHECK TAKE OFF DATA" message appears.
It allows to change V1/VR/V2 as follow without any problems (new issue on this point ?)
![image](https://user-images.githubusercontent.com/9373163/98463602-a1f9c100-21bc-11eb-8bb8-1055d6b4e8cb.png)

Here we deals with security so i'm not surprised about a double check.
ECAM check also allow to check UPLINK TO DATA I think
There is nothing in references saying values have to be kept or not

2020-11-08 11:48 UTC, beheh commented
Sure, that screen is appropriate if the runway changes, but not if (for example) it starts to rain and the pilots decide to rerun the V speeds for the new runway conditions (which may also result in a new flex temperature).

This is not a big deal, but it seems ambiguous enough in the documentation that now we're adding it we might as well get a reference from a real aircraft/professional simulator rather than guessing one way or the other. I can easily see either way be correct, but we don't have to guess.

2020-11-08 12:32 UTC, atcopilot commented
> ![grafik](https://user-images.githubusercontent.com/39596827/98444034-ab791f80-210f-11eb-9fcc-f66e6c13731d.png)
From the image provided by @lukecologne, it looks like the "T.O. V1/VR/V2 DISAGREE" ECAM failure message should automatically appear after 1st engine start until reaching 80 kt on take off roll. So, if a V speed is inserted on MCDU during this period and does not satisfy the condition V1 <= Vr <= V2, then the ECAM message should appear as well as the MCDU message. The pilot is able clear the ECAM message, but it should reappear after executing a T.O. Config test.

2020-11-08 12:43 UTC, paul92ilm commented
Well, not so easy.. In phase 2 you have to push T.O Config but not in phase 3 (full page bellow)
![image](https://user-images.githubusercontent.com/9373163/98465159-9790f480-21c7-11eb-9672-e1ee867e5a60.png)

ECAM logic message is not linked to the MCDU logic, so I agree with @beheh and wait for a pilot feedback

2020-11-08 12:47 UTC, atcopilot commented
> Well, not so easy.. In phase 2 you have to push T.O Config but not in phase 3 (full page bellow)
> ECAM logic message is not linked to the MCDU logic, so I agree with @beheh and wait for a pilot feedback

You are right. Thanks for the full page.

2020-11-09 15:56 UTC, HugoTro commented
Category: QA Tester
Name: Hugo #3307
Date of testing: Current date 09/11/2020
Version of the sim: 1.10.8.0
PR Tested: #1786 
Object of test: V1,V2,V3 disagree logic on the MCDU

Testing technique: Cold & dark
Steps you've made to test the Pull Request:
1. Spawned in cold & dark at gate 37 at LFMN
2. Verified that we cannot enter V speeds if V1<VR<V2 


Issues : I can enter the same speeds for V1, Vr, and V2, which i tested with 90 knots
Overall Rating: Good
Conclusions of the testing: good PR !

2020-11-09 19:25 UTC, paul92ilm commented
> Category: QA Tester
> Name: Hugo #3307
> Date of testing: Current date 09/11/2020
> Version of the sim: 1.10.8.0
> PR Tested: #1786
> Object of test: V1,V2,V3 disagree logic on the MCDU
> 
> Testing technique: Cold & dark
> Steps you've made to test the Pull Request:
> 
> 1. Spawned in cold & dark at gate 37 at LFMN
> 2. Verified that we cannot enter V speeds if V1<VR<V2
> 
> Issues : I can enter the same speeds for V1, Vr, and V2, which i tested with 90 knots
> Overall Rating: Good
> Conclusions of the testing: good PR !

![image](https://user-images.githubusercontent.com/9373163/98586784-85977a80-22c9-11eb-9cbc-77cf8715a68a.png)
Same V1, VR, V2 is allowed so everything normal

2020-11-09 19:52 UTC, HugoTro commented
Ok cool i didn't see that 😃

2020-11-10 11:31 UTC, beheh commented
Good news: norab (real pilot) from Discord found this after [a short discussion](https://discord.com/channels/738864299392630914/754851312306487326/775671983231991859) ([Source, page 3](https://safetyfirst.airbus.com/app/themes/mh_newsdesk/documents/archives/the-take-off-securing-function.pdf)):

![image](https://user-images.githubusercontent.com/929769/98668381-1a44bb80-2350-11eb-8667-0fa526e9a64a.png)

While that isn't 100% the Honeywell documentation we usually use, I believe it's good enough of a reference to at least go by it for now until we find something better.

2020-11-10 11:58 UTC, beheh commented
The [document from the previous post](https://safetyfirst.airbus.com/app/themes/mh_newsdesk/documents/archives/the-take-off-securing-function.pdf) is highly interesting - it describes additional consistency checks for V Speeds. These are not technically in scope, but could be picked up either here or in a future PR:

![image](https://user-images.githubusercontent.com/929769/98671337-63970a00-2354-11eb-9ff1-a4c1dfc853a5.png)

2020-11-10 17:58 UTC, paul92ilm commented
Thanks @beheh, really interesting, I will change the code to keep values

Really ambiguous for the modified value but I think too that the message is displayed only when all 3 values have been filled

2020-11-12 20:27 UTC, ChruutvoLuzi commented
Category: MCDU
Name: Discord User ChruutvoLuzi | SD-PB.ch#8902
Date of testing: Current date 12.11.2020
Version of the sim: 1.10.11.0
PR Tested: #1786 
Object of test: (VSpeeds Disagree Logic

Testing technique: Try out
Steps you've made to test the Pull Request:
1.  Spawned cold and dark
2.  Turned on the aircraft
3.  entered wrong VSpeeds
4. tested T.O Config Test Button in a few conditions (Taxi, Takeoff)

Flight notes (If required):

Issues (If Any): None
Overall Rating: Works as described
Conclusions of the testing: Noticed no issues. The warning is amber and triggers the master warning as described.

2020-11-12 21:22 UTC, FlightSimmer7700 commented
Category: QA Tester
Name: FlightSimmer7700#3468
Date of testing: Current date #12/11/20
Version of the sim: Latest
PR Tested: #1786 
Object of test: V Speeds

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned at Jersey
2. Put in normal V speeds which worked as expected
3. Put in "incorrect" V speeds, Acted as described above
4.Incorrect v speeds comes up on the MCDU and upper ECAM when TO config button pressed

Flight notes (If required): 

Issues (If Any): none
Overall Rating: Good
Conclusions of the testing: Looks all good!

2020-11-13 08:38 UTC, merged