Change slats, wing and flaps shapes
flybywiresim/a32nx pull request #1809
Opened 2020-11-08 17:28 UTC by paul92ilm

Fixes #1803 

## Summary of Changes

- Improve slats, wing and flaps design on upper ECAM 

## Screenshots (if necessary)

#### Before
![image](https://user-images.githubusercontent.com/9373163/98471845-57456c80-21ef-11eb-8be0-6d982af47a7c.png)
![image](https://user-images.githubusercontent.com/9373163/98471881-8e1b8280-21ef-11eb-9ad3-1bfc12fd714d.png)

#### After
![image](https://user-images.githubusercontent.com/9373163/98471943-ea7ea200-21ef-11eb-907c-b66c7b2ce4ea.png)
![image](https://user-images.githubusercontent.com/9373163/98471922-c622c580-21ef-11eb-8916-36a5f28ced98.png)

## References

![image](https://user-images.githubusercontent.com/9373163/98471824-341abd00-21ef-11eb-9510-3dc6ecb49a92.png)
![image](https://user-images.githubusercontent.com/9373163/98471836-38df7100-21ef-11eb-9233-ad637b044e02.png)

## Additional context

Discord username (if different from GitHub): Lussion

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2020-11-08 18:13 UTC, aviationenthusiast commented
> ![image](https://user-images.githubusercontent.com/9373163/98471922-c622c580-21ef-11eb-8916-36a5f28ced98.png)

does the grey quadrilateral in the middle disappear like the second image in references?

2020-11-08 18:20 UTC, paul92ilm commented
Not yet, I'm working on the slats and flaps dots before.
Will work on the wing/grey shape after

2020-11-08 19:04 UTC, atcopilot commented
> > ![image](https://user-images.githubusercontent.com/9373163/98471922-c622c580-21ef-11eb-8916-36a5f28ced98.png)
> 
> does the grey quadrilateral in the middle disappear like the second image in references?

It does not disappear. It looks like so but it was just the camera inability to show all colours correctly.
Original reference
https://youtu.be/aAvQXMbiodw
Look at 00:20

2020-11-08 19:40 UTC, paul92ilm commented
> > > ![image](https://user-images.githubusercontent.com/9373163/98471922-c622c580-21ef-11eb-8916-36a5f28ced98.png)
> > 
> > 
> > does the grey quadrilateral in the middle disappear like the second image in references?
> 
> It does not disappear. It looks like so but it was just the camera inability to show all colours correctly.
> Original reference
> https://youtu.be/aAvQXMbiodw
> Look at 00:20

👍 
So it's ready for reviews and tests

2020-11-08 20:52 UTC, stevex77 commented
Tested with following results:

FLAPS RETRACTED:
![F0](https://user-images.githubusercontent.com/51388935/98483745-37bc3d00-220b-11eb-8ace-daa228255e0a.png)

FLAPS 0 >>> 1+F:
![F0+](https://user-images.githubusercontent.com/51388935/98483757-4c003a00-220b-11eb-9edf-5e2975acf3ca.png)

FLAPS 1+F:
![F1](https://user-images.githubusercontent.com/51388935/98483787-5c181980-220b-11eb-9b62-1fb69f56e3c8.png)

FLAPS 1+F >>> 2:
![F1+](https://user-images.githubusercontent.com/51388935/98483809-76ea8e00-220b-11eb-8837-30de42cad892.png)

FLAPS 2:
![F2](https://user-images.githubusercontent.com/51388935/98483815-810c8c80-220b-11eb-9b31-7d209ba5a2be.png)

FLAPS 2 >>> 3:
![F2+](https://user-images.githubusercontent.com/51388935/98483826-8ff33f00-220b-11eb-8106-67b083c7a73f.png)

FLAPS 3:
![F3](https://user-images.githubusercontent.com/51388935/98483834-9b466a80-220b-11eb-9a96-4c75955b90bc.png)

FLAPS 3 >>> FULL:
![F3+](https://user-images.githubusercontent.com/51388935/98483839-a8fbf000-220b-11eb-969b-bb0994137e75.png)

FLAPS FULL:
![FF](https://user-images.githubusercontent.com/51388935/98483849-b618df00-220b-11eb-8f28-3512cd6132c9.png)

FLAPS FULL >>> 3:
![FF-](https://user-images.githubusercontent.com/51388935/98483866-c5982800-220b-11eb-87cb-6675ff45c059.png)

FLAPS 3 >>> 2:
![F3-](https://user-images.githubusercontent.com/51388935/98483877-dcd71580-220b-11eb-8894-62b232fff24d.png)

FLAPS 1+F >>> RETRACTED:
![F1-](https://user-images.githubusercontent.com/51388935/98483888-f2e4d600-220b-11eb-8e13-609bfd418b94.png)

---

Reference (retracted):
![FREF](https://user-images.githubusercontent.com/51388935/98483906-160f8580-220c-11eb-8158-c9a3460097d6.png)

Result: Great work!

2020-11-08 21:05 UTC, stevex77 commented
I believe that this gray quadrilateral should remain there.
I adjusted the exposure of reference video and it's clearly visible:

![FLAPS](https://user-images.githubusercontent.com/51388935/98484248-67207900-220e-11eb-94d3-841b4bbe1251.png)

So from my POV this is implemented correctly. :)

2020-11-09 01:57 UTC, lukecologne commented
According to the FCOM, the selected (but not reached) slat/flap position should have a blue diamond below the normal white diamond, instead of the current blue flaps indicator. Do you want to implement that as well, and if yes, also in this PR? It's OK if you don't want to. References: 
![grafik](https://user-images.githubusercontent.com/39596827/98492122-26892580-2237-11eb-833f-ffe529e38e7f.png)
![grafik](https://user-images.githubusercontent.com/39596827/98492136-2f79f700-2237-11eb-85b6-d93459e834b2.png)
https://youtu.be/g32B8_5TbdQ?t=80

2020-11-09 06:11 UTC, paul92ilm commented
Will work on it

2020-11-09 10:19 UTC, stevex77 commented
Have found this video, but it's not NEO excactly. But should be the same for NEO when comparing video to FCOM snip @lukecologne attached.

I also noticed that "lever position" indication (5) should possibly be CYAN when flas / slats in transit based on bot the video and FCOM snip.

https://www.youtube.com/watch?v=TgETvlt3QjY

2020-11-09 13:13 UTC, Benjozork commented
@stevex77, it seems like you don't have the QA template - can you give me your discord username so I can have the QA role given to you ? you seem to help out a lot

2020-11-09 13:55 UTC, stevex77 commented
@Benjozork sure, my discord is SteveX77 [Z+0!]#1407
Already assigned to QA TESTERS group there.
And yes, QA template will be usefull. :)

2020-11-09 22:34 UTC, paul92ilm commented
Cyan indicator replaced
![image](https://user-images.githubusercontent.com/9373163/98604482-06fc0680-22e4-11eb-9f7d-6d3aa991af75.png)

2020-11-09 22:53 UTC, lukecologne requested changes
Looks very nice, just a few small issues

2020-11-09 22:53 UTC, lukecologne commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +        _cx = _cx + _xOffset;
It's not a good idea to re-assign function parameters. You should create a new const instead.

2020-11-09 22:53 UTC, lukecologne commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +        _cx = _cx + _xOffset;
Same as above

2020-11-09 23:03 UTC, paul92ilm commented
Final result
![image](https://user-images.githubusercontent.com/9373163/98606712-09605f80-22e8-11eb-971f-f112fd8e6113.png)

2020-11-09 23:10 UTC, lukecologne approved these changes
Alright, tested and looks good. If you don't want to add anything else, then it is good to go.

2020-11-09 23:26 UTC, merged

2020-11-09 23:29 UTC, paul92ilm commented
> Alright, tested and looks good. If you don't want to add anything else, then it is good to go.

Points (1), (2) and (5) of your reference seems fully implemented. I will work on the 2 others for degraded configuration in an other PR.
So looks good to me to merge at this step

2020-11-09 23:34 UTC, lukecologne commented
I don't think you need to worry about the rest, since they seem to rely on hydraulics or faults, both of which currently isn't implemented. You could take a look again once we start modeling these