[CDU] Add check for destination data
flybywiresim/a32nx pull request #2009
Opened 2020-11-18 23:57 UTC by MisterChocker

## Summary of Changes

Added check for destination data according to the references.

## Screenshots (if necessary)

![image](https://user-images.githubusercontent.com/1857322/99602617-1543d400-2a02-11eb-8873-ea7a4b2b317d.png)

## References

![image](https://user-images.githubusercontent.com/1857322/99602535-ed547080-2a01-11eb-9fba-39fa5f49eaa1.png)

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2020-11-19 00:02 UTC, Benjozork approved these changes
LGTM

2020-11-19 04:22 UTC, danbw9 commented
Category: QA Test
Name: danbw9#7028
Date of testing: Current date 19/11/2020
Version of the sim: 1.10.11.0
PR Tested: #2009 
Object of test: Checking out the added scratchpad message for - 'ENTER DEST DATA' in MCDU

Testing technique: Complete normal flight and look for expected behaviour

Steps you've made to test the Pull Request:

- Start up from C&D from LEBL to LSZH - normal flight but not entering any data into APP PERF page.
- At approximate 180 miles waiting for message. Pops up around 160 miles to go (estimate on ND) - but only after I initiated a DES in managed mode. 
- message keeps re appearing until all fields are filled out

Curious to see what other QA testers find out, otherwise I will check it out tomorrow, as this was a testing report after one flight. 

Issues (If Any): Small issue - not sure if directly related to this PR. Described below - v
Overall Rating: Good
Conclusions of the testing: Nice addition. I had a little issue with the scratchpad logic behaviour with when I am in the PERF page and the 'ENTER DEST DATA' scratchpad message is displayed. I clear it. Enter a value in scratchpad for any of QNH/TEMP/MAG WND. Put it into the appropriate field. 'ENTER DEST DATA' message appears again. Clear it. and the value I manually put in reappears. Tried it several times and had the same issue. I looked in docs and could not find an answer. The 180 miles to go to DEST - is it based on F-PLAN track miles or when directly from aircraft position to DEST airport is 180 miles? Great work as always @MisterChocker

2020-11-19 12:22 UTC, MisterChocker commented
I fixed the bad scratchpad behavior on message clear, used the correct variable for distance to destination and I slightly increased the timeout between each check now 15 seconds.
By clearing the message, a new one will show up on top of your scratchpad inputs. (I found that a bit annoying)
By not clearing the message, it will be hidden by any input to the scratchpad (except clr) and maintains hidden until scratchpad is emtpy.

2020-11-19 13:31 UTC, MisterChocker commented
Okay should be good to test again.

2020-11-21 10:45 UTC, InhumanReactions commented
Category: QA Tester
Name: InhumanReactions#7129
Date of testing: Current date 21/11/20
Version of the sim: 1.10.11.0
PR Tested: #2009
Object of test: Add check for destination data

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned in C&D at ENVA for a full flight to EGLL.
2. Took off as usual. No problems encountered.
3. Started my descent and the ENTER DEST DATA came up as expected.
4. Cleared the message and it came back up as expected. 
5.Message automatically cleared when all APPR info was inputted into the MCDU.

Flight notes (If required): 

Issues (If Any): I didn't experience any issues at all. The ENTER DEST DATA came back even after I cleared it (Which I assume is supposed to happen) which is great. It went away after everything was filled in which was perfect.
Overall Rating: Good
Conclusions of the testing: This is a great PR. The message worked as expected and it is really useful to us pilots as it reminds you incase you forget. I didn't encounter any issues. Great work!

2020-11-22 18:34 UTC, lukecologne requested changes

2020-11-22 18:34 UTC, lukecologne commented on A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
> +elevator_effectiveness = 0.1
This doesn't look like it belongs here

2020-11-22 18:34 UTC, lukecologne commented on A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
> +roll_stability = 3.25
Same here

2020-11-22 18:39 UTC, MisterChocker commented on A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
> +elevator_effectiveness = 0.1
removed changes

2020-11-22 18:39 UTC, MisterChocker commented on A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/flight_model.cfg
> +roll_stability = 3.25
removed changes

2020-11-22 18:39 UTC, lukecologne approved these changes

2020-11-23 06:00 UTC, merged