changed colors to use presets
flybywiresim/a32nx pull request #2127
Opened 2020-11-29 10:55 UTC by MisterChocker

Fixes #[issue_no]

## Summary of Changes

some housekeeping

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2020-11-29 11:34 UTC, beheh requested changes
Added a source for about the colors used for scratchpad messages.

2020-11-29 11:34 UTC, beheh commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
> +            this.addTypeTwoMessage("ENTER DEST DATA", "yellow", () => {}, () => {
This should be amber ("red"), not yellow:
```suggestion
            this.addTypeTwoMessage("ENTER DEST DATA", "red", () => {}, () => {
```

Documentation:

![image](https://user-images.githubusercontent.com/929769/100540607-8f642c00-323e-11eb-9ad9-4dca462aa521.png)

2020-11-29 11:34 UTC, beheh commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
> +                    this.addTypeTwoMessage("GPS PRIMARY LOST", "yellow", () => {
See another review comment above. Messages are never yellow.

```suggestion
                    this.addTypeTwoMessage("GPS PRIMARY LOST", "red", () => {
```

2020-11-29 16:41 UTC, MisterChocker commented
There is really/should be no visual difference except for the yellow messages now being amber.

2020-11-29 17:06 UTC, MisterChocker commented
waiting for #2121 to solve conflicts because of changes to color handling of message system.

2020-12-01 14:41 UTC, Benjozork approved these changes
LGTM

2020-12-01 14:42 UTC, Benjozork commented
For QA: Check that MCDU pages have the right colors, and that yellow messages now appear amber.

2020-12-01 15:45 UTC, Noxleee commented
Category: QA Tester
Name: Noxlee #7727
Date of testing: Current date 1/12/2020
Version of the sim: 1.11.6.0
PR Tested: #2127 
Object of test: Colors of MCDU

Testing technique: Test all MCDU Pages at Gate
Steps you've made to test the Pull Request:
1. Load up AC at Gate with flight plan prefilled (from menu)
2. Checked former yellow messages - Now amber
3. Checked all pages for Cyan (I went through (EVERY!) Page of the MCDU) -> Can't find any issue / deviation
4. Checked green on PERF PAGE TO RWY FIELD -> Runway is now green
5. Checked green on PROG PAGE ECON CRZ -> ECON CRZ is now green
6. Checked missing sub row on airways page -> Filled complete Page, VIA and TO on every Row
7. Checked new flight phases to PROG PAGE -> No idea how to check this, but CRZ Flight level showed only after at take-off (Set TO thrust), do not know if there were made changes


Overall Rating: Good
Conclusions of the testing: I checked everything and did not find any issue but am not sure with the 7th check. I could not find any red in the MCDU. If there should be something red, I did not see it, or it was not red.

2020-12-01 15:52 UTC, MisterChocker commented
Sounds great except for the CRZ FL on PROG PAGE, the behavior described by you is the behavior before I made the changes to it.
So you could actually go ahead, pull the latest version of this pr and see if this changed. (It should)

2020-12-01 15:56 UTC, Noxleee commented
Okay, I will pull the latest version, test it and update my report later today!

2020-12-01 16:24 UTC, Noxleee commented
> 
> 
> Category: QA Tester
> Name: Noxlee #7727
> Date of testing: Current date 1/12/2020
> Version of the sim: 1.11.6.0
> PR Tested: #2127
> Object of test: Colors of MCDU
> 
> Testing technique: Test all MCDU Pages at Gate
> Steps you've made to test the Pull Request:
> 
>     1. Load up AC at Gate with flight plan prefilled (from menu)
> 
>     2. Checked former yellow messages - Now amber
> 
>     3. Checked all pages for Cyan (I went through (EVERY!) Page of the MCDU) -> Can't find any issue / deviation
> 
>     4. Checked green on PERF PAGE TO RWY FIELD -> Runway is now green
> 
>     5. Checked green on PROG PAGE ECON CRZ -> ECON CRZ is now green
> 
>     6. Checked missing sub row on airways page -> Filled complete Page, VIA and TO on every Row
> 
>     7. Checked new flight phases to PROG PAGE -> No idea how to check this, but CRZ Flight level showed only after at take-off (Set TO thrust), do not know if there were made changes
> 
> 
> Overall Rating: Good
> Conclusions of the testing: I checked everything and did not find any issue but am not sure with the 7th check. I could not find any red in the MCDU. If there should be something red, I did not see it, or it was not red.

Here is the update:
7. Checked new flight phases to PROG PAGE -> CRZ flight level showed during pre-flight and taxi.

Overall Rating: Good
Conclusions of the testing: I tested the updated PR again, but only point 7. Now it is working correctly.
LGTM!

2020-12-01 16:26 UTC, Benjozork commented
Should be good

2020-12-01 17:40 UTC, merged