Update README.md
flybywiresim/a32nx pull request #2240
Opened 2020-12-05 15:36 UTC by Benjozork

## Summary of Changes

This adds information about what aircraft configuration is currently being simulated.

Discord username (if different from GitHub): someperson#4953

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2020-12-05 21:07 UTC, wpine215 commented on README.md
> + Engine     LEAP 1-A26
Should be LEAP 1A-26 iirc

2020-12-07 06:55 UTC, NathanInnes approved these changes
LGTM

2020-12-08 01:34 UTC, davwheat requested changes

2020-12-08 01:34 UTC, davwheat commented on README.md
> +Note that those parameters might be incosistent / might change while the project evolves towards a more stable form.
```suggestion
Please note that this configuration may change in the future as the A32NX project evolves and changes.
```

2020-12-08 01:34 UTC, davwheat commented on README.md
> + Model      A320-251N
Should we use a table for this instead?

2020-12-08 03:45 UTC, Benjozork commented on README.md
> + Model      A320-251N
Sure.

2020-12-08 05:02 UTC, merged