F-PLN page visual rework
flybywiresim/a32nx pull request #2245
Opened 2020-12-05 22:02 UTC by Lollo999

## Summary of Changes
This PR is a follow up to the FPLN scroll fix, 
Made some changes to the F-PLN page to be more accurate to the real one:
1> FIXED : scroll skipping the "END OF F-PLN" line when scrolling 
2> FIXED : "SPD/ALT" indication is now fixed on top, making it easier to read the data
3> FIXED : Destination airport line is now fixed on the bottom of the page (if ERASE/INSRT line is not present)
4> ADDED : unit of measure [NM] on the last row waypoint distance from previous point.
5> FIXED : text size and color in the first and last point (DEP/DEST)
6> FIXED:  "From" text should only be present if the wp the aircraft is flying from is in the first row of the page
7> FIXED: now also the departure and arrival wp in the flight plan change color when the plan is being edited 
8> minor edits and code clean up

## Screenshots (if necessary)
BEFORE:
![test_post_fix](https://user-images.githubusercontent.com/36545051/101266168-bd6cd300-374c-11eb-8d2a-7277eeb53fa6.gif)

AFTER:

![Microsoft Flight Simulator 2020 12 04 - 10 40 49 01_Trim (2)](https://user-images.githubusercontent.com/36545051/101266114-54855b00-374c-11eb-99a4-3249432da769.gif)

## References
online videos, Honeywell manual, and also compared by visual clues to the FSL one for some details. I did my best to make it as close as possible to the real one using the already present code base. Any feedback is very appreciated.

## Additional context
Tested in a couple of flights and using different PCs, no issues found so far related to this update

Discord username (if different from GitHub): Lorenzo Pinna#9154

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2020-12-06 13:01 UTC, MisterChocker commented
Why does you before not show the magenta asterix? Thats already implemented

2020-12-07 01:24 UTC, MisterChocker requested changes

2020-12-07 01:24 UTC, MisterChocker commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
> +                                if (i == rowsCount - 1 || j >= holdRows.length) {
```suggestion
                                if (i === rowsCount - 1 || j >= holdRows.length) {
```

2020-12-07 06:54 UTC, NathanInnes commented
Add changelog if you got time

2020-12-08 01:55 UTC, davwheat requested changes

2020-12-08 01:55 UTC, davwheat commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
> +                        rows[2 * i] = [(index === 0 && offset == 0) ? "FROM" : airwayName, ((index >= activeIndex || waypoint.ident === "(DECEL)") && i != 0 ? dstnc : i === 0 ? "SPD/ALT" : ""), i ===
```suggestion
                        rows[2 * i] = [(index === 0 && offset === 0) ? "FROM" : airwayName, ((index >= activeIndex || waypoint.ident === "(DECEL)") && i !== 0 ? dstnc : i === 0 ? "SPD/ALT" : ""), i === 0 ? (isFlying ? "UTC" : "TIME") : ""];
```

2020-12-08 07:01 UTC, Lollo999 commented
> Why does your before not show the magenta asterix? Thats already implemented. #2070
> The scroll thing is already implemented. #2069
> Or did you made changes to that?

My bad, the clip is from the #2069 i made before this, #2070 was merged soon after so i forgot to remake those videos, i think the most accurate way to see this working is in game, since is the only way to know exactly if the behaviour is correct

2020-12-08 08:40 UTC, closed without merging

2020-12-09 18:05 UTC, NathanInnes commented
Did you mean to close the PR?