Added additional check for predicted altitude
flybywiresim/a32nx pull request #2267
Opened 2020-12-07 01:09 UTC by Saschl

Fixes #2261

## Summary of Changes

Added an additional check to prevent that altitude predicitions  override non-departure waypoints. Need to test it properly and verify the behaviour, therefore a draft. 
## Screenshots (if necessary)
Will add

Discord username (if different from GitHub): saschl#9432

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2020-12-07 01:14 UTC, Saschl commented
I'll also try some cleanup if possible. The else/if blocks look somewhat redundant

2020-12-07 01:20 UTC, MisterChocker requested changes

2020-12-07 01:20 UTC, MisterChocker commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
> +                        const isDepartureWayPoint = routeFirstWaypointIndex > 1 && mcdu.flightPlanManager.getDepartureWaypoints().indexOf(waypointsWithDiscontinuities[index]) != -1;
```suggestion
                        const isDepartureWayPoint = routeFirstWaypointIndex > 1 && mcdu.flightPlanManager.getDepartureWaypoints().indexOf(waypointsWithDiscontinuities[index]) !== -1;
```

2020-12-07 01:22 UTC, MisterChocker commented
I hope these pr are not overlapping/conflicting #2245

2020-12-07 01:57 UTC, Saschl commented
> I hope these pr are not overlapping/conflicting #2245

Dang I didn't look at this before. But at the first glance, it doesn't seem to change the logic regarding altitude constraints. As it's already Ready to test I'll wait and test after the merge again.

2020-12-08 23:29 UTC, beheh commented
Does this also fix #928? If so, let's get it added to the PR description (with another "fixes #928").

2020-12-09 00:54 UTC, Saschl commented
> Does this also fix #928? If so, let's get it added to the PR description (with another "fixes #928").

Looks like the same isse. I'll updated the description

2020-12-09 11:56 UTC, Noxleee commented
Category: QA Tester
Name: Noxlee #7727
Date of testing: Current date 09/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2267
Object of test: Flight plan

Testing technique: Test Flight -EDDK/14L F330 PODIP8F PODIP Y867 WRB N850 ESTAD L23 HAM P605 GESKA
Z711 MONAK MONAK2A EKCH/04R
Steps you've made to test the Pull Request:
1. Programmed FMC
2. Check Flight Plan first waypoint which is BADGO:
![grafik](https://user-images.githubusercontent.com/71323011/101625688-12923880-3a1c-11eb-9d58-3f136ca61503.png)
3. Checked first waypoint after dep.:
![grafik](https://user-images.githubusercontent.com/71323011/101626692-9dbffe00-3a1d-11eb-82ea-d3fec6ca7f2f.png)

Flightnotes:
The Last waypoint, which is the Runway 04R at EKCH has FL330. Is this also related to this PR?
![grafik](https://user-images.githubusercontent.com/71323011/101625957-7fa5ce00-3a1c-11eb-8e73-200508040153.png)

Issues: Found the one in the flight notes, but maybe not related to the PR 
Overall Rating: If the Issue is not related to the PR - Good, otherwise to be improved

2020-12-09 14:20 UTC, Saschl commented
I think I didn’t change anything in that direction but I’ll verify the behaviour with the current dev version. Do you know by any chance what the value should actually be for the rw waypoint? Runway elevation maybe?

2020-12-09 14:22 UTC, MisterChocker commented
> Runway elevation maybe

It might be runway threshold elevation

2020-12-09 22:00 UTC, Saschl commented
The waypoint shouldn't have the cruise altitude anymore. It now behaves like the current dev version. I tried to improve by setting the runway elevation but in the end I guess it would interfere with the complete rewrite of the predictions that is also in progress.

2020-12-12 10:19 UTC, BritishAvgeek commented
> Category: QA Tester
> Name: Noxlee #7727
> Date of testing: Current date 09/12/2020
> Version of the sim: 1.11.7.0
> PR Tested: #2267
> Object of test: Flight plan
> 
> Testing technique: Test Flight -EDDK/14L F330 PODIP8F PODIP Y867 WRB N850 ESTAD L23 HAM P605 GESKA
> Z711 MONAK MONAK2A EKCH/04R
> Steps you've made to test the Pull Request:
> 
> 1. Programmed FMC
> 2. Check Flight Plan first waypoint which is BADGO:
>    ![grafik](https://user-images.githubusercontent.com/71323011/101625688-12923880-3a1c-11eb-9d58-3f136ca61503.png)
> 3. Checked first waypoint after dep.:
>    ![grafik](https://user-images.githubusercontent.com/71323011/101626692-9dbffe00-3a1d-11eb-82ea-d3fec6ca7f2f.png)
> 
> Flightnotes:
> The Last waypoint, which is the Runway 04R at EKCH has FL330. Is this also related to this PR?
> ![grafik](https://user-images.githubusercontent.com/71323011/101625957-7fa5ce00-3a1c-11eb-8e73-200508040153.png)
> 
> Issues: Found the one in the flight notes, but maybe not related to the PR
> Overall Rating: If the Issue is not related to the PR - Good, otherwise to be improved

That's been an issue for months now nothing to do with this guy's PR... The airports regularly have the cruise alt displayed as a bug in the sim for some reason

2020-12-16 22:39 UTC, wpine215 approved these changes

2020-12-16 22:39 UTC, merged