Flight model update and full landing flaps to 40
flybywiresim/a32nx pull request #2271
Opened 2020-12-07 06:44 UTC by donstim

Fixes #2247  and #2248 

## Summary of Changes

## References

## Additional context

Discord username (if different from GitHub):donbikes#4084

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2020-12-07 07:25 UTC, donstim commented
Alright, I see the hour or more I spent filling in the template section for summary of changes, reference documents, and additional content just disappeared into thin air. So, I will try to recreate it here.

Summary of Changes:
1. Changes the vertical tail area and span to match the real airplane and the rudder effectiveness and max angle scalar, all in the flight_model.cfg file,  to provide more realistic crosswind takeoff and landing capability.
2. Changes the legacy flight model parameters in the flight_model.cfg file to be consistent with the modern flight model.
3. Changes the CONF FULL flap deflection angle from 35 degrees to 40 degrees.
4. Changes the ECAM symbol for the CONF FULL configuration to show a flap deflection of 40 degrees (to be added by @MisterChocker )

References:
![Screenshot (359)](https://user-images.githubusercontent.com/70166617/101319589-15700c00-3817-11eb-8624-0a71e05949c4.png)
![Screenshot (362)](https://user-images.githubusercontent.com/70166617/101319606-1c971a00-3817-11eb-91a4-e6db5a6807a2.png)

Additional Context:
1. Although there is an engine issue that limits the NEO crosswind takeoff capability to 35 knots, for the purpose of testing this PR, use a 38 knot crosswind for both takeoff and landing. (The engine issue isn't simulated, and we are interested in the airplane's actual capability.) Gusts are included in that 38 knots, so you can turn the gusts off, but I used the default gust value in the same direction as the crosswind when developing the flight model changes.

2. Taking off and landing in high crosswinds is not a simple task. I recommend starting with lighter crosswinds and gradually working your way up to the maximum crosswind value. Practice, practice, practice! Light weights are most critical - I used 110,000 lb (50 T) in developing the flight model changes.

3. For takeoff, the first task is to stay on the runway, and if not close to the centerline, at least away from the edges. The rudder is not very effective at low speeds, and its effectiveness increases with speed. Try not to under control at first and over control later -- it's easy to get into a PIO if you're not careful. The second task is to transition somewhat gracefully into flight. Try to keep your wings leve with small aileron inputs as you near rotation.

4. For landing, the tasks are to decrab and align with the runway just before landing, and then to stay near the centerline on rollout. From the A320neo FlightCrew Training Manual:

![Screenshot (364)](https://user-images.githubusercontent.com/70166617/101320667-ff634b00-3818-11eb-89f3-0a399b673dd3.png)

5. Keep in mind that the rudder should only be used (in normal situations) for crosswind takeoff and landings, engine failures, and other large thrust asymmetries. Rudder is automatically applied for turn coordination.

6. The results these changes supply are likely to be affected by the type and model of rudder control being used (e.g., rudder pedals vs twist type joysticks, etc.) and the sensitivity settings and dead zones for the particular controller. I used CH Products Pro Rudder Pedals in developing these changes.

7.  It is my understanding that the autopilot uses the legacy flight model parameters. That is one reason for the changes to make these parameters match the modern flight model. Hopefully, the changes will improve, or at least not worsen in any way, the flight dynamics of the autopilot.

2020-12-07 09:19 UTC, beheh commented
By changing your description from `Fixes #2247 and #2248` to `Fixes #2247 and fixes #2248` you can ensure that both issues are closed when this is merged (otherwise only the first is closed).

2020-12-07 13:38 UTC, MisterChocker requested changes

2020-12-07 13:38 UTC, MisterChocker commented on .github/CHANGELOG.md
> +1. [FLIGHTMODEL]  Changed full landing flap deflection from 35 degrees to 40 degrees - @donstim - (donbikes#4084)
```suggestion
1. [FLIGHTMODEL] Changed full landing flap deflection from 35 degrees to 40 degrees - @donstim - (donbikes#4084)
```

2020-12-08 13:41 UTC, Lazarus320 commented
Category: QA Tester
Name: Lazarus#4286
Date of testing: Current date 8/12/2020
Version of the sim: 1.11.6.0
PR Tested: #2271 
Object of test: Crosswind takeoff and landing capability, flaps degree.  

Testing technique: Wind was set to 38 degrees, weight was 110,000 lbs as well, dry conditions for both takeoff and landing. 
Steps you've made to test the Pull Request:
1. FLaps 40 degree from external view (visually there is no change but on the bottom right corner you can see it changed to 35 to 40) 
![image (2)](https://user-images.githubusercontent.com/74972083/101490888-f3ed5c80-399d-11eb-90b3-2f0d6e574136.jpg)


2. Takeoff: https://youtu.be/Bb2k8qa3qIE  
3. Landing: https://youtu.be/LY7KU5LNatE


Flight notes (If required): Hardware used: Logitech Extreme 3d PRO 

Issues (If Any): N/A
Overall Rating: Good
Conclusions of the testing: Overall everything felt better, I haven't done much crosswind landing or takeoffs due to the addressed behavior but now it feels a lot better and more stable than before, great job!

2020-12-08 15:40 UTC, BritishAvgeek commented
Category: QA Tester
Name: Lazarus#4286
Date of testing: Current date 8/12/2020
Version of the sim: 1.11.6.0
PR Tested: #2271
Object of test: Crosswind takeoff and landing capability, flaps degree.

Testing technique: EGCC - Departure, right hand circuit with wind 310/38kts - full crosswind 90 degrees to the runway with 55.68T TOW
Steps you've made to test the Pull Request:
1. Departed EGCC with the wind set to 310/38kts... great behaviour on rotation with the aircraft crabbing into wind during rotation and requiring aileron to counter wing dip
2. Right hand circuit and then made my way to the ILS 23R
3. Final Approach - checked Flaps 40, all good
4. Manual Control of the aircraft from about 5-6nm out to see how it behaved as AP was handling the ILS approach perfectly fine with the 38kt crosswind
5. Landing, correction to counter crab on touch down all good though it feels quite slippery as if I've landed on ice... I had full left rudder to keep it on the centre line at one point



Flight notes (If required): Hardware used: Thrustmaster T-Flight HOTAS X Full Flight Kit

Issues (If Any): N/A
Overall Rating: Good
Conclusions of the testing: The way the aircraft behaved certainly was improved and seemed more natural - with it crabbing into wind during takeoff nicely. Though the controls will need resetting for me to find the new best deadzones/sensitivities with the changes as the rudder input became very harsh randomly... I ran 3 circuits with mixed results with differing settings though the aircraft was definitely better than before having flown into airports in the sim with strong live Wx crosswinds previously including a 30kt into Dublin so was comparing against that too. Great work

2020-12-09 20:26 UTC, kberg93 reviewed
Category: QA Tester
Name: Kberg#0666
Date of testing: Current date 12/09/2020
Version of the sim: 1.11.7.0
PR Tested: #2271 
Object of test: Flight model update and full landing flaps to 40 (Crosswind takeoffs and landings)

Testing technique: Take offs and landings in 38kt wind with gusts.

Steps you've made to test the Pull Request: 
1. Take off manually take a round and come back for touch and goes did 6 touch and goes.
2. Then i did 4 takeoffs with landings.

Flight notes (If required): Everything was done flying manual, only autothrottle were used during my test.

Issues (If Any): 

Overall Rating: Good feeling and consistent.

Hardware used: TM Warthog (HOTAS) and MFG Crosswinds v2.

Conclusions of the testing: The rudder feeling was good and i felt it behaved good, the take offs and landings were consistently good without any scetchy or weird behaviour.
Would probably be nice to see what a A320 pilot feels with this PR vs the real deal to get some input maybe?
From my side it felt consistent and good at least. :)

2020-12-10 04:41 UTC, merged