Add batch file for easy build
flybywiresim/a32nx pull request #2275
Opened 2020-12-07 13:38 UTC by Kimbyeoungjang

Fixes #2274

## Summary of Changes

Add batch file for easy build, update, etc... for user

## Screenshots (if necessary)

![image](https://user-images.githubusercontent.com/23118756/101357471-d2786c00-38dc-11eb-89e9-1b221046b557.png)

## References

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2020-12-07 13:38 UTC, Kimbyeoungjang commented
please ignore upper commit

2020-12-08 01:46 UTC, davwheat requested changes

2020-12-08 01:46 UTC, davwheat commented on installer.cmd
> +goto conatct)
```suggestion
goto contact)

```

2020-12-08 01:46 UTC, davwheat commented on installer.cmd
> +echo                Do you wanna install Docker?
Should we be more formal here?

(i.e. `wanna` -> `want to`)

2020-12-08 01:46 UTC, davwheat commented on .github/CHANGELOG.md
> +1. [BAT] Add Batchfile for easy development and build - @Kimbyeongjang (김병장#7165)
```suggestion
1. [BAT] Add batch file to automate download and building A32NX from source for non-experienced users - @Kimbyeongjang (김병장#7165)
```

2020-12-08 01:46 UTC, davwheat commented on installer.cmd
> +if "%docker%"=="Y" start "" https://www.docker.com/get-started & goto exit
You can use this to check case-insensitively. That way you don't need to check against `y` and `Y`.

```batch
if /i "%docker%"=="y"
```

2020-12-08 01:46 UTC, davwheat commented on installer.cmd
> +if "%docker%"=="n" goto exit
What if the user inputs `x`? Won't the script just continue executing downwards? We should ask for input again.

(This applies to the other error sections too)

```suggestion
if "%docker%"=="n" (goto exit)
else goto dockerERROR
```

2020-12-08 01:46 UTC, davwheat commented on installer.cmd
> +@echo off
We should put `@echo off` before the title command, otherwise the command is printed to the cmd window.

2020-12-08 01:59 UTC, Kimbyeoungjang commented
thx for review @davwheat. i fix all that review :)

2020-12-08 02:07 UTC, davwheat requested changes

2020-12-08 02:07 UTC, davwheat commented on installer.cmd
> +    exit /B
```suggestion
    exit
```

No need for `/B` as we're [not setting an error code](https://ss64.com/nt/exit.html).

2020-12-08 02:07 UTC, davwheat commented on installer.cmd
> +if "%docker%"=="y" (
You need the `/i` here to handle uppercase (e.g. `Y`) too. Learn more here: https://ss64.com/nt/if.html

This also applies further down.

```suggestion
if /i "%docker%"=="y" (
```

2020-12-23 19:49 UTC, Highflyer2010 commented
what is this actually for?

2020-12-24 01:04 UTC, Kimbyeoungjang commented
> what is this actually for?

First time, i just build this batch file for non-experienced user about coding.
But there is already dev build installer, so this is going to trashbin i think XD

2020-12-28 07:08 UTC, Highflyer2010 commented
> 
> 
> > what is this actually for?
> 
> First time, i just build this batch file for non-experienced user about coding.
> But there is already dev build installer, so this is going to trashbin i think XD

ah now i get it. With us having the installer i don't think it's really needed now

2020-12-28 07:30 UTC, Kimbyeoungjang commented
> > > what is this actually for?
> > 
> > 
> > First time, i just build this batch file for non-experienced user about coding.
> > But there is already dev build installer, so this is going to trashbin i think XD
> 
> ah now i get it. With us having the installer i don't think it's really needed now

Yes i think. Closed pr.

2020-12-28 07:30 UTC, closed without merging