[CDU] Improve visuals of CDU Pages
flybywiresim/a32nx pull request #2475
Opened 2020-12-17 00:28 UTC by MisterChocker

## Summary of Changes

### FMGC Pages
- [ ] DIR
- [ ] PROG
- PERF will skipped
- [ ] INIT-A
- [ ] INIT-B
- [ ] DATA
- [ ] F-PLN
- [ ] RAD NAV
- [ ] FUEL PRED
- LAT REV already done
- [ ] VERT REV

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub): DerL30N#3751

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2020-12-17 08:14 UTC, wpine215 commented
Looks like the stored waypoint text above the "DELETE ALL" field is too close - is there any way to adjust the margins/padding a bit so it's consistent with everything else?

2020-12-17 08:46 UTC, MisterChocker commented
> Looks like the stored waypoint text above the "DELETE ALL" field is too close - is there any way to adjust the margins/padding a bit so it's consistent with everything else?

tbh, no clue why it's even the way it is, seems buggy. But managed to fix it, just pls don't look how I fixed it xD

2020-12-17 14:13 UTC, Noxleee commented
Category: QA Tester
Name: Noxlee #7727
Date of testing: Current date 17/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2475 
Object of test: MCDU Pages

Testing technique: Checked pages mentioned in the PR description
Steps you've made to test the Pull Request:
1. Load AC
2. Checked Pages before Programming FMC
3. Checked Pages after Programming FMC
4. Test route:  EDDL/23L DODE9T DODEN Y852 EDISA Y173 PABLA T715 RIGVI LUME8K LFSB/15 (Did not flown)

Notes: 

- On the DATA page, there are a few menu points without function 
-> recommendation: grey colour like other not working functions in the mcdu

Issues:
- Flight plan: SID/STAR is recognised as UNDEFINED
->SID: 
![grafik](https://user-images.githubusercontent.com/71323011/102497469-f7a57100-4078-11eb-9a16-efffbbb44592.png)
->STAR:
![grafik](https://user-images.githubusercontent.com/71323011/102497308-c331b500-4078-11eb-80c0-182e3d04a2da.png)

- Departure Runway and STAR stay yellow after insert, same on Arrival page:
-> DEP:
![grafik](https://user-images.githubusercontent.com/71323011/102497375-da70a280-4078-11eb-9753-b38db6ed3e7d.png)
-> ARR:
![grafik](https://user-images.githubusercontent.com/71323011/102497410-e78d9180-4078-11eb-866b-75440fb8245e.png)



Overall Rating: To be improved
Conclusions of the testing: Found two Issues described above and made one recommendation in the notes. All other pages are looking good so far nothing seems to be misaligned.

2020-12-18 18:04 UTC, MisterChocker commented
Waiting for #2263

2020-12-20 06:59 UTC, wpine215 commented
> 
> 
> Category: QA Tester
> Name: Noxlee #7727
> Date of testing: Current date 17/12/2020
> Version of the sim: 1.11.7.0
> PR Tested: #2475
> Object of test: MCDU Pages
> 
> Testing technique: Checked pages mentioned in the PR description
> Steps you've made to test the Pull Request:
> 
>     1. Load AC
> 
>     2. Checked Pages before Programming FMC
> 
>     3. Checked Pages after Programming FMC
> 
>     4. Test route:  EDDL/23L DODE9T DODEN Y852 EDISA Y173 PABLA T715 RIGVI LUME8K LFSB/15 (Did not flown)
> 
> 
> Notes:
> 
>     * On the DATA page, there are a few menu points without function
>       -> recommendation: grey colour like other not working functions in the mcdu
> 
> 
> Issues:
> 
>     * Flight plan: SID/STAR is recognised as UNDEFINED (Stock database -> no navigraph)
>       ->SID:
>       ![grafik](https://user-images.githubusercontent.com/71323011/102497469-f7a57100-4078-11eb-9a16-efffbbb44592.png)
>       ->STAR:
>       ![grafik](https://user-images.githubusercontent.com/71323011/102497308-c331b500-4078-11eb-80c0-182e3d04a2da.png)
> 
>     * Departure Runway and STAR stay yellow after insert, same on Arrival page:
>       -> DEP:
>       ![grafik](https://user-images.githubusercontent.com/71323011/102497375-da70a280-4078-11eb-9753-b38db6ed3e7d.png)
>       -> ARR:
>       ![grafik](https://user-images.githubusercontent.com/71323011/102497410-e78d9180-4078-11eb-866b-75440fb8245e.png)
> 
> 
> Overall Rating: To be improved
> Conclusions of the testing: Found two Issues described above and made one recommendation in the notes. All other pages are looking good so far nothing seems to be misaligned.

Can you confirm the issues you mentioned don't exist when using the current development version without this PR?

2020-12-20 10:45 UTC, Noxleee commented
I tested the current dev. version. No issues there. Seems like the PR tries to find a name for the SID and STAR but can't find it.

2020-12-20 14:49 UTC, myselfaaryan requested changes

2020-12-20 16:33 UTC, MisterChocker commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_IdentPage.js
> +            ["A320-251N"],
thx for the heads up, fyi all changes I did where done with Honeywell manual.

2020-12-21 10:01 UTC, wpine215 approved these changes

2020-12-21 10:08 UTC, merged

2020-12-21 14:50 UTC, Aarondodd88 commented
Awesome! Has anyone noticed how "NEON" the font colours are on the mcdu?.  FFA320 the only way i can match the same colours is by turning the brightness 100%. These colours used seem to match the font colour in the TolissA320. FBWA320 No brightness changes the font colour on the mcdu, so always have such a bright "NEON" font colour. The font may be the correct colour but for some reason it becomes to fluorescent

2020-12-21 15:30 UTC, MisterChocker commented
No changes to color definition in this pr. Only text alignment corrections and some small other text changes.