perf: remove useless checks for other aircraft
flybywiresim/a32nx pull request #2517
Opened 2020-12-18 23:14 UTC by Benjozork

## Summary of Changes

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2020-12-18 23:28 UTC, MisterChocker requested changes

2020-12-18 23:28 UTC, MisterChocker commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
> +            this.isInMetric = true;
```suggestion
            this.weightConversion = parseFloat(NXDataStore.get("CONFIG_USING_METRIC_UNIT", "1"));
```

2020-12-18 23:28 UTC, MisterChocker commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
> +            const leftConsumption = SimVar.GetSimVarValue("GENERAL ENG FUEL USED SINCE START:1", "KG");
```suggestion
            const leftConsumption = SimVar.GetSimVarValue("GENERAL ENG FUEL USED SINCE START:1", "KG") * this.conversionUnit;
```

2020-12-18 23:28 UTC, MisterChocker commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
> +            const rightConsumption = SimVar.GetSimVarValue("GENERAL ENG FUEL USED SINCE START:2", "KG");
```suggestion
            const rightConsumption = SimVar.GetSimVarValue("GENERAL ENG FUEL USED SINCE START:2", "KG") * this.conversionUnit;
```

2020-12-18 23:31 UTC, MisterChocker requested changes
To make use of your changeable unit system

2020-12-18 23:31 UTC, MisterChocker commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
> +            this.isInMetric = true;
remove this if agreeing with the other changes

2020-12-18 23:31 UTC, MisterChocker commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
> +            this.unitFactor = SimVar.GetSimVarValue("FUEL WEIGHT PER GALLON", "kilogram");
```suggestion
            this.unitFactor = SimVar.GetSimVarValue("FUEL WEIGHT PER GALLON", "kilogram") * parseFloat(NXDataStore.get("CONFIG_USING_METRIC_UNIT", "1"));
```

2020-12-18 23:31 UTC, MisterChocker commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
> +            const leftConsumption = SimVar.GetSimVarValue("GENERAL ENG FUEL USED SINCE START:1", "KG");
```suggestion
            const leftConsumption = SimVar.GetSimVarValue("GENERAL ENG FUEL USED SINCE START:1", "KG") * this.unitFactor;
```

2020-12-18 23:31 UTC, MisterChocker commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_LowerECAM_CRZ.js
> +            const rightConsumption = SimVar.GetSimVarValue("GENERAL ENG FUEL USED SINCE START:2", "KG");
```suggestion
            const rightConsumption = SimVar.GetSimVarValue("GENERAL ENG FUEL USED SINCE START:2", "KG") * this.unitfactor;
```

2021-01-12 22:58 UTC, Benjozork commented
This does not improve performance by a lot, #2976 does.

2021-01-12 22:58 UTC, closed without merging