[CDU] Fix airways showing as undefined
flybywiresim/a32nx pull request #2589
Opened 2020-12-21 21:29 UTC by pareil6

Fixes #2585.

## Summary of Changes
Fixes airways field in FPLN page showing as 'undefined' when between two waypoints without a connecting airway. Issue occurred where any two waypoints both had an undefined outbound/inbound airway, which would incorrectly pass an equality check.

## Screenshots (if necessary)

## References
N/A

## Additional context
N/A

Discord username (if different from GitHub): pareil6#0990

## Testing instructions
Check 'undefined' never shows up as an airway name - try SIDs/STARs, random points within a flight plan, last waypoint before STAR/first after SID/etc.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2020-12-21 21:32 UTC, MisterChocker approved these changes
LGTM

2020-12-21 21:37 UTC, MisterChocker commented
Please add changelog

2020-12-21 21:39 UTC, pareil6 commented
> Please add changelog

Dammit, every time... Done 😛

2020-12-21 21:42 UTC, MisterChocker commented
Tested and works.

2020-12-21 21:49 UTC, MisterChocker requested changes

2020-12-21 21:49 UTC, MisterChocker commented on .github/CHANGELOG.md
> +1. [CDU] Fix FPLN airways showing as undefined
```suggestion
1. [CDU] Fixed FPLN airways showing as undefined - @pareil6 - (pareil6)
```

2020-12-21 21:52 UTC, MisterChocker approved these changes

2020-12-21 21:54 UTC, MisterChocker requested changes

2020-12-21 21:54 UTC, MisterChocker commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
> +                            if (prevWaypoint.infos.airwayOut && (prevWaypoint.infos.airwayOut === waypoint.infos.airwayIn)) {
```suggestion
                            if (prevWaypoint.infos.airwayOut && prevWaypoint.infos.airwayOut === waypoint.infos.airwayIn) {
```

2020-12-21 21:54 UTC, MisterChocker commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_FlightPlanPage.js
> +                            if (prevWaypoint.infos.airwayOut && (prevWaypoint.infos.airwayOut === waypoint.infos.airwayIn)) {
missed these parentheses before, they are not needed btw

2020-12-21 22:00 UTC, MisterChocker approved these changes

2020-12-22 02:45 UTC, NickFarin commented
Category: QA Tester
Name: Nick F[Z+8]#5327
Date of testing: 22/12/2020
Version of the sim: 1.11.7.0
PR Tested: #2589 
Object of test: CDU airways showing as undefined

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Spawned at KLAS
2. Made a flight plan on SimBreif
3. Pressed Init request
4. Checked if there are any undefined airways

Flight notes (If required):

Issues (If Any): 
Overall Rating: Good
Conclusions of the testing: Test was nominal.

2020-12-22 06:40 UTC, merged