[ECAM] Support CONF 3 Landing
flybywiresim/a32nx pull request #3140
Opened 2021-01-22 10:38 UTC by tracernz

I have split the ECAM half off #2889 in this PR.

## Summary of Changes

The final item on the ECAM landing memo is flaps. Whether this item refers to flaps 3 or full depends on the GPWS LDG FLAP 3 switch on the overhead panel. The logic to enable GPWS warnings at flaps 3 or full depending on the switch already exists.

## Screenshots (if necessary)

Before:
![image](https://user-images.githubusercontent.com/9995998/105479768-beac8c00-5d09-11eb-89ef-869f2b789feb.png)

After:
![image](https://user-images.githubusercontent.com/9995998/105479816-ccfaa800-5d09-11eb-95bb-6664fc20d0c5.png)
![image](https://user-images.githubusercontent.com/9995998/105479840-d3891f80-5d09-11eb-8582-0b9fd1196eff.png)

## References

FCOM for the ECAM memo:
![image](https://user-images.githubusercontent.com/9995998/105479887-e6035900-5d09-11eb-9e38-eab4d5cff825.png)

## Additional context

Discord username (if different from GitHub): tracernz

## Testing instructions

NOTE: This PR does not implement the MCDU part, so the target approach speed (magenta triangle on PFD speed tape) will still be that for flaps full. FMCG/MCDU work to come in #2889.
- GPWS warnings disabled while near ground with CONF 3 (and GPWS CONF 3 switch ON (indicates OFF per #803). This was already working before the PR.
- ECAM landing memo displaying correct flaps config and action.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2021-01-22 21:55 UTC, beheh commented
The same condition that switches the LDG MEMO to FLAP should also add a green `GPWS FLAP 3` memo to the right column (based on the GPWS button). Order-/Priority-wise it's one of the lowest items in the list, before the AUTO BRKs and after the APU AVAIL/BLEED and LDG LT memo.

2021-01-23 03:50 UTC, tracernz commented
> The same condition that switches the LDG MEMO to FLAP should also add a green `GPWS FLAP 3` memo to the right column (based on the GPWS button). Order-/Priority-wise it's one of the lowest items in the list, before the AUTO BRKs and after the APU AVAIL/BLEED and LDG LT memo.

Thanks @beheh. The message was already there, but looking at the wrong L var, so I have fixed that in 982b729. One thing I note is that `L:A32NX_GPWS_FLAPS3` is fetched quite a few times and as I understand it simvars are a little slow. Would it be worth getting it once per update and putting it in a member variable for use in the various places? I guess these kinds of problems go away when the EWD ECAM gets re-written for React if we have a SimVar watcher?

2021-01-23 12:46 UTC, beheh commented
>One thing I note is that L:A32NX_GPWS_FLAPS3 is fetched quite a few times and as I understand it simvars are a little slow. Would it be worth getting it once per update and putting it in a member variable for use in the various places?

A helper for this already exists in the UpperECAM. You can call `this.getCachedSimVar`.

> I guess these kinds of problems go away when the EWD ECAM gets re-written for React if we have a SimVar watcher?

Yes, although it will be structured quite differently as the message activation logic will live in WASM, and the EWD itself will have to only look at a few SimVars to determine which message is shown.

2021-01-23 15:38 UTC, tracernz commented
> A helper for this already exists in the UpperECAM. You can call `this.getCachedSimVar`.

Didn't notice I was already using it in https://github.com/flybywiresim/a32nx/pull/3140/commits/982b729f7a6dfa12ccfeda9dfd075ac8dffe2a7b >.<. Replaced the rest of the accesses.
> 
> Yes, although it will be structured quite differently as the message activation logic will live in WASM, and the EWD itself will have to only look at a few SimVars to determine which message is shown.

Brilliant.

2021-01-23 15:56 UTC, beheh approved these changes

2021-01-24 01:08 UTC, MisterChocker requested changes
tempus

2021-01-24 01:08 UTC, MisterChocker commented on .github/CHANGELOG.md
> +1. [ECAM] Add CONF/FLAPS 3 memos when GPWS LDG FLAPS 3 enabled - @tracernz (Mike)
```suggestion
1. [ECAM] Added CONF/FLAPS 3 memos when GPWS LDG FLAPS 3 enabled - @tracernz (Mike)
```

2021-01-24 10:16 UTC, sidnov commented
Category: QA Tester
Name: sidnov#8337
Date of testing: 24/01/2021
Version of the sim: 1.12.13.0
PR Tested: #3140 
Tier of testing: 1
Changes to observe: ECAM CONF 3 indication

Testing technique: Tryout

Steps you've made to test the Pull Request:

1. Spawn on VABB Approach for RWY27.
2. Turned on GPWS FLAP 3, checked ECAM (Screenshot 1)
3. Set Flaps to 3. (Screenshot 2)
4. Continued approach. Tried turning off GPWS FLAP 3, ECAM mode reverted to FLAP FULL config.

Media:
![image](https://user-images.githubusercontent.com/29005005/105627003-ef034000-5e59-11eb-9aae-f02c9a327fb3.png)

![image](https://user-images.githubusercontent.com/29005005/105627032-2540bf80-5e5a-11eb-80e7-1f3a09c8b9e4.png)

![image](https://user-images.githubusercontent.com/29005005/105627041-37226280-5e5a-11eb-8f3e-67f829e5f59a.png)

Issues (If Any): None

Overall Rating: Good
Conclusions of the testing: Since it's an ECAM visual addition, not tested in detail, looks good to go. Can't wait for the other half of the PR (MCDU) to be implemented! 💯

2021-01-24 10:45 UTC, stescouse commented
Category: QA Tester
Name: Discord User stescouse#7271
Date of testing: 24.1.2021
Version of the sim: 1.12.13.0
PR Tested: #3140
Tier of testing: 1
Changes to observe: [ECAM] Support CONF 3 Landing.

Testing technique: TryOut
Steps you've made to test the Pull Request:

1. Spawned C&D at GMME
2. Flew to LFPG.
3. On APPR engaged GPWS FLAP 3
![flap 3 - 2](https://user-images.githubusercontent.com/77486160/105627662-cde22580-5e40-11eb-9387-533cf9e5f4cf.PNG)

4. GPWS FLAP 3 displayed correctly in ECAM.

![flap 3 - 1](https://user-images.githubusercontent.com/77486160/105627683-f4a05c00-5e40-11eb-9c16-61567e977740.PNG)

5. On Final APPR engaged FLAPS 3 and displayed correctly in ECAM with no config warning.

![flap 3 - 3](https://user-images.githubusercontent.com/77486160/105627699-1699de80-5e41-11eb-8d54-7fef5a091a92.PNG)

6  After landing messages cleared correctly in ECAM

![flap 3 - 4](https://user-images.githubusercontent.com/77486160/105627722-329d8000-5e41-11eb-863b-4aff1fe04182.PNG)


Flight notes (If required: Full flight from GMME to LFPG.

Issues (If Any): None;


Overall Rating: Good
Conclusions of the testing: Performed as set out in PR and as stated on MDCU approach speed for PFD is still FLAPS FULL.

2021-01-24 14:42 UTC, MisterChocker approved these changes

2021-01-24 14:43 UTC, merged