Known issues fixes
flybywiresim/a32nx pull request #3286
Opened 2021-02-02 00:54 UTC by TansyEliot

Fixes #[issue_no]

## Summary of Changes

Known issues fixes on README.md

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub): TansyEliot#9914

## Testing instructions

No testing necessary.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2021-02-04 13:18 UTC, pepperoni505 requested changes
This should include the known issues on our Discord

2021-02-04 13:22 UTC, pepperoni505 commented on README.md
> +- Automatic ECAM page switching has minor bugs.
```suggestion
- Automatic ECAM page switching has minor bugs.
- AP not following the flight plan (leaking input values affect, but don't disconnect the AP) [Workaround: Set dead-zones for your input device higher] 
- Autopilot goes direct to RWY on APP (same with the default A320) [Workaround: Use DIR to a waypoint or selected heading]
- Upper ECAM displays wrong THR levers position / N1 rating.
- Newly added ASOBO A320 liveries are incompatible with the A32NX mod. 
- Ruder keybindings not working (you have to set your keybinding to rudder axis right and left)
- Wing dips on landing (due to bad transition to direct law in flare, same with the default A320)  [Workaround use minimal aileron input on landing]
- Black screens / unable to start (conflict with another mod/livery or incorrect installation of the A32NX mod, use the [installer](https://api.flybywiresim.com/installer))
```

2021-02-04 13:22 UTC, pepperoni505 commented on README.md
> +- Captain's PFD may occasionally turn off during flight.
```suggestion
- Captain's PFD may occasionally turn off during flight

```

2021-02-04 18:15 UTC, ImenesFBW approved these changes
LGTM!

2021-02-05 06:59 UTC, ZigTag approved these changes
LGTM

2021-02-05 07:08 UTC, merged