feat(ecam): Add ap&athr warning
flybywiresim/a32nx pull request #3288
Opened 2021-02-02 10:56 UTC by Kimbyeoungjang

Fixes #[issue_no]

## Summary of Changes

using #3281 warning system, add warning message when disconnect autopilot / autothrottle.
also, when disconnect autothrottle, caution alert will ringing.

## Screenshots (if necessary)

## References

![image](https://user-images.githubusercontent.com/23118756/106590638-aaca1b00-6590-11eb-9dc4-13cc84e874f5.png)
![image](https://user-images.githubusercontent.com/23118756/106590649-ad2c7500-6590-11eb-98ab-58c06faec1f1.png)
![image](https://user-images.githubusercontent.com/23118756/106590653-af8ecf00-6590-11eb-9699-0d0ee27d368e.png)

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2021-02-02 12:47 UTC, Kimbyeoungjang commented
this using my warning logic. so some of my pr is merged(i wish), need to fix my other pr.

2021-02-02 15:32 UTC, beheh requested changes

2021-02-02 15:32 UTC, beheh commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +                    },
The messages should be swapped, as AP OFF has a higher priority.

2021-02-02 15:32 UTC, beheh commented on A32NX/html_ui/Pages/A32NX_Core/A32NX_Core.js
> +            new A32NX_Warning
There is no reason to introduce a new warning system, this logic should be handled by the Flight Warning Computer (A32NX_FWC). I suggest moving your code to A32NX_FWC and removing A32NX_Warning.

2021-02-02 15:51 UTC, beheh commented on A32NX/html_ui/Pages/A32NX_Core/A32NX_Warning.js
> +        this.apdeltaTime = 0;
You can use logic nodes from A32NX_Logic for this. Look at the FWC for examples on how they work.

2021-02-04 10:47 UTC, Kimbyeoungjang commented
working done but need to merge #3281 first.

2021-02-09 07:53 UTC, Kimbyeoungjang commented
change to draft until merge my other pr.
also need to add flashing logic - current AP warning only turn on and off but real aircraft have a flashing master warning.

2021-03-06 11:05 UTC, Kimbyeoungjang commented
reopen to other pr due to branch cleanup

2021-03-11 03:02 UTC, closed without merging