Temporary Fixed tooltips and added Signs off light
flybywiresim/a32nx pull request #338
Opened 2020-09-03 00:06 UTC by oliverpope03

https://gyazo.com/c41a86eb5d2927f5a051aeb99355d96f

2020-09-03 07:22 UTC, NathanInnes requested changes

2020-09-03 07:22 UTC, NathanInnes commented on A32NX/SimObjects/AirPlanes/Asobo_A320_NEO/model/A320_NEO_INTERIOR.xml
> +
Remove extra line spaces.

2020-09-03 17:52 UTC, NathanInnes commented
Please rename PR and comment all changes made clearly

2020-09-04 12:16 UTC, oliverpope03 commented
I will Not push more changes into this PR unless something is reported wrong i realised ive done alot in one PR but its all overhead and sound :)

2020-09-06 14:43 UTC, oliverpope03 commented
Just rebased onto the latest build to make sure no clashes would occur*

2020-09-06 15:52 UTC, oliverpope03 commented
Fixed better by @tyler58546 's ECAM PR

2020-09-06 16:06 UTC, closed without merging