fix(efb): Fix Scrolling in EFB Loadsheet
flybywiresim/a32nx pull request #3519
Opened 2021-02-14 03:56 UTC by akhileshmalini

Fixes Issue where scrolling load sheet is impossible.

## Summary of Changes

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub): EwilCorp

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2021-02-14 09:47 UTC, myselfaaryan requested changes

2021-02-14 09:47 UTC, myselfaaryan commented on src/instruments/src/EFB/Dispatch/Pages/Loadsheet.scss
> +    width: 1em;
@apply w-4;

2021-02-14 09:47 UTC, myselfaaryan commented on src/instruments/src/EFB/Dispatch/Pages/LoadsheetPage.tsx
> +				<div className="bg-gray-800 rounded-xl p-6 text-white shadow-lg mr-4">
indents

2021-02-14 09:47 UTC, myselfaaryan commented on src/instruments/src/EFB/Dispatch/Pages/Loadsheet.scss
> +    -webkit-box-shadow: inset 0 0 6px rgba(0,0,0,0.3);
indents

2021-02-14 17:29 UTC, Benjozork commented
Styling needs improvement imo. Maybe add some FBW blue (called blue-light in the tailwind config) and some ever so slightly rounded corners ?

2021-02-14 18:16 UTC, akhileshmalini commented
![Uploading Scrolled.PNG…]()

Updated Scrollbar styles

2021-02-16 22:58 UTC, ZigTag approved these changes
LGTM

2021-02-16 23:21 UTC, akhileshmalini commented
![Screen_Shot_2021-02-15_at_3.35.09_PM.png](https://user-images.githubusercontent.com/11068772/108134172-8da24b80-706a-11eb-9b85-16cee83b72aa.png)

Based on conversations on Discord, I've added a way for people to increase Font size.

2021-02-17 04:07 UTC, marcman86 commented
Name: marcman86#4907
Date of testing: 17.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3519
Tier of testing: 1
Changes to observe: EFB Loadsheet scrolling
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Started EFB
3.) Tested loadsheet scrolling via bar and touchscreen drag
4.) Tested min. zoom (Image1) and max. zoom (Image 2)

Media:

![76](https://user-images.githubusercontent.com/78707844/108154566-6c2e7780-70dd-11eb-8d8b-a1bbe6c6300c.png)
Image1

![77](https://user-images.githubusercontent.com/78707844/108154578-705a9500-70dd-11eb-8e82-fafc5785ae5d.png)
Image2

Issues: 

- The slider is tiny and the sliding bar very thin, so the clickzones are tiny to. This gets frustrating cause the EFB is small for itself.
- The horizontal space is not fully used on max zoom. 
- Horizontal space is wasted from the two zoom buttons. 
- Images dont get magnified when zoomed in.

Design suggestions (my opinion :-)): 

- Make the slider size as a zoom button and also the slidebar in this width. 
- Shorten the slidebar and put the zoom buttons under the slidebar.
- Make max. zoom higher, so that the text will fill the whole page.

Minor improvement: Can you make the (mouse)hand grab on drag? 

Overall Rating: -

Conclusions of the testing: Needs to be improved.

Hope this helps :-)

2021-02-25 11:06 UTC, FlyingCarpet7 commented
When you are at this page can you please change the Loadsheet menu header to Flightplan or OFP.

2021-03-02 15:44 UTC, akhileshmalini commented
I've fixed the issue with the images and I've allowed for more zoom. 


As for the size of the  scrollbar, I'm not entirely sure how we would achieve that. But the Touch and scroll should be helpful in certain scenarios. 

Not sure if we can move the zoom buttons under the scrollbar. If anything, that'll make it even harder to scroll because of the reduced height of the scrollbar.

2021-03-02 15:46 UTC, akhileshmalini commented
And changing the hand to grab, I've actually implemented that in css, but it doesn't seem to work.

2021-03-11 08:10 UTC, Benjozork commented
Please fix your lint errors

2021-03-13 19:27 UTC, closed without merging