Workaround for active freq being zero
flybywiresim/a32nx pull request #3550
Opened 2021-02-16 10:37 UTC by 1Revenger1

Fixes #3362 

## Summary of Changes
Add workaround for Simvars `COM ACTIVE FREQUENCY:1` and `COM ACTIVE FREQUENCY:2` being set to 0 when loading in at the gate.

## Screenshots (if necessary)
Before:
![image](https://user-images.githubusercontent.com/13190749/108050418-69a92080-6ffe-11eb-868e-cdfe87e78db9.png)
After:
![image](https://user-images.githubusercontent.com/13190749/108050577-a412bd80-6ffe-11eb-9381-bed4c6540ee2.png)

## Additional context
This issue appears to only occur when spawning in at the gate - I tried spawning in the air/approach/on the runway and they all worked fine. Other things I tried:
* I diffed the apron.FLT and runway.FLT files, and didn't find any obvious differences.
* Reading simvars from other instruments (ie the PFD), but `COM ACTIVE FREQUENCY` was still set to zero

I also compared the original code from before the React RMP PR was merged in, and there appears to be a [workaround for these values being set to 0](https://github.com/flybywiresim/a32nx/blob/d53d3f73245cddc50bbb82d2af1f27489188f466/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FDW/A320_Neo_FDW.js#L104-L115) from Asobo. This suggests that the issue is something deeper within the sim which can't be fixed through a FLT file (else they would've likely fixed it that way instead?)

## Testing instructions
1) Spawn at a gate
2) Enable ground power and check that the active frequency for VHF1, VHF2, and VHF3 are non zero
3) Spawn at runway
4) Check the active frequency for VHF1, VHF2, and VHF3

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2021-02-16 10:39 UTC, Kimbyeoungjang commented
change title to 
fix(rmp): Workaround for active freq being zero

2021-02-16 22:52 UTC, ZigTag approved these changes

2021-02-17 04:30 UTC, marcman86 commented
Name: marcman86#4907
Date of testing: 17.2.2021
Version of the sim: 1.13.16.0
PR Tested: #3550
Tier of testing: 1
Changes to observe: RMP frequencys not zero
Testing technique: Tryout

Steps made to test the Pull Request:

1.) Spawned C&D at EDDP
2.) Started bat. and ext. power
3.) Checkes VHF1, VHF2 and VHF3 
4.) Spawned at EDDP Runway
5.) Started bat. and ext. power
6.) Checkes VHF1, VHF2 and VHF3

Issues: None

Overall Rating: Good

Conclusions of the testing: Works!

Hope this helps :-)

2021-02-17 09:06 UTC, theomessin requested changes
You are checking whether the active frequency is zero at _every_ render. It'd be best if you pushed this to an initialise panel function which only gets called once (you can keep a hasInitialised state using hooks). In there you can just set initial values to all the frequencies, not just the currently active one (that way you can set useful frequencies, e.g. `122.8` and `121.5`).

> I also compared the original code from before the React RMP PR was merged in, and there appears to be a workaround for these values being set to 0 from Asobo. This suggests that the issue is something deeper within the sim which can't be fixed through a FLT file (else they would've likely fixed it that way instead?)

Nice catch 😄 at least we now know that this is caused by the sim and not the RMP implementation.

2021-02-20 01:01 UTC, 1Revenger1 commented
@theomessin with the latest commit, is this what you had in mind? I wasn't sure if I should do all frequencies or not.

I feel if we are setting at least the two active frequencies which are zero at spawn, we should probably set all of them just so that they're all in a consistent place.

2021-03-08 07:41 UTC, wpine215 commented
Any update on this PR?

2021-03-08 19:33 UTC, 1Revenger1 commented
Oh, I'd been waiting for a response. Hadn't seen the reaction on my last comment. I'll work more on this later today.

2021-03-17 04:39 UTC, 1Revenger1 commented
I was doing some more testing, and I figured out a couple weird things.
1) The frequency from Apron.FTL is set immediately upon pressing "Fly now" in the main menu
2) The RMP code starts running about ~50% of the way loading
3) Asobo sets the frequency to 0 (or ~400000 according to Vpilot) about 10 seconds after the RMP code starts running.

I tried using just `useEffect(() => { //init }, [])` but that would initialize the frequencies before Asobo set gibberish.
Current solution sets the frequency once every time, or three times for every time that `initFreq` changes. This all occurs though while the plane is loading so no flickering should be seen.

2021-03-26 22:48 UTC, DavidEGTE commented
Category: QA Tester
Name: David#2177
Date of testing: 26/03/2021
Version of the sim: 1.14.6.0
PR Tested: #3550 
Tier of testing: 1

Changes to observe:
workaround for active freq being zero

Testing technique: Try-out

Steps you've made to test the Pull Request:
1. Followed PR instruction
2. Spawned C&D 
3. Spawned Runway

Flight notes (When done a full flight):
N/A
Media: Insert screenshots, recordings, or anything relevant to the review here.
N/A
Issues (If Any): Write any issues
N/A
Steps to achieve the issue:
N/A

Overall Rating: Good
Conclusions of the testing: Works as described, GTG

2021-04-21 00:31 UTC, joseph-tobin commented
FYI the default number set 429496.... is awfully similar to the max theoretical JS array length of 4294967296 elements. This may not be helpful at all but thought I'd mention it.

2021-05-08 11:05 UTC, davidwalschots commented
This was fixed in #3980 by accident. It's unclear how this was fixed by that particular PR. My _guess_ would be that adding `electric_always_available = 1` to `systems.cfg` somehow ensured the value wouldn't reset to zero.

2021-05-08 11:05 UTC, closed without merging