fix(efb): correctly implement current flight on map
flybywiresim/a32nx pull request #3561
Opened 2021-02-16 21:43 UTC by Benjozork

## Summary of Changes

* Update to `@flybywiresim/map` 0.5.0
* Use local data instead of API for locating current flight
* **Note:** `origin` and `destination` do not currently work

Discord username (if different from GitHub): someperson#4953

## Testing instructions

* Ensure the EFB map locates your aircraft correctly

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created and uploaded.
The build script will have already been run with the latest changes, so no need to rerun it once you download the zip.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the right side, click on the **Artifacts** drop down and click the **A32NX** link

2021-02-16 22:54 UTC, ZigTag approved these changes
LGTM

2021-02-16 23:51 UTC, nistei requested changes

2021-02-16 23:51 UTC, nistei commented on .github/workflows/pr.yml
> +          docker run --rm -v "$(pwd)":/external ghcr.io/flybywiresim/dev-env@sha256:0bf0844b914cbd45a8a0a866a71c7a07fa09308f48cb961708be479f0d63aa0f
```suggestion
          docker run --rm -v "$(pwd)":/external ghcr.io/flybywiresim/dev-env@sha256:0bf0844b914cbd45a8a0a866a71c7a07fa09308f48cb961708be479f0d63aa0f scripts/lint-rust.sh
```

2021-02-16 23:51 UTC, nistei commented on .github/workflows/pr.yml
> +          docker run --rm -v "$(pwd)":/external ghcr.io/flybywiresim/dev-env@sha256:0bf0844b914cbd45a8a0a866a71c7a07fa09308f48cb961708be479f0d63aa0f
```suggestion
          docker run --rm -v "$(pwd)":/external ghcr.io/flybywiresim/dev-env@sha256:0bf0844b914cbd45a8a0a866a71c7a07fa09308f48cb961708be479f0d63aa0f scripts/test-rust.sh
```

2021-02-17 00:06 UTC, nistei approved these changes

2021-02-17 01:09 UTC, Awemeter commented
Category: QA Tester
Name: Awemeter#7919 
Date of testing: 2/16/2021
Version of the sim: 1.13.16.0
PR Tested: #3561 
Tier of testing: 1
Changes to observe:

- Update to @flybywiresim/map 0.5.2

- Fix dev-env version

- Use local data instead of API for locating current flight

- Note: origin and destination do not currently work

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request: Tried out
1. Spawned C&D at EGCB 
2. Started aircraft and fly pad and made sure plane shows in the proper place.
3. Started to move and take off and map updated every 10 seconds as it should.
4. Made sure the rest of EFB was still working.

Flight notes (When done a full flight):

Media: Insert screenshots, recordings, or anything relevant to the review here.

Issues (If Any): None


Overall Rating: Good
Conclusions of the testing: All good no issues found.

2021-02-17 01:10 UTC, merged