Selftest after off status knobs
flybywiresim/a32nx pull request #363
Opened 2020-09-03 21:29 UTC by topiek-fs

This puts the panels in "self-test" mode after the knob has been turned from off to another position.

Known issue: We can't seperate the panels yet so when the FO turns his knob to off and back to something, the captains side will also self test. This can be fixed when we can seperate the panels somehow.

2020-09-03 21:33 UTC, topiek-fs commented
![afbeelding](https://user-images.githubusercontent.com/70661970/92175877-b1b3fc80-ee3d-11ea-97e5-6562f66b04cc.png)
![afbeelding](https://user-images.githubusercontent.com/70661970/92175922-cabcad80-ee3d-11ea-805a-10842d6e57c5.png)
![afbeelding](https://user-images.githubusercontent.com/70661970/92175949-d5774280-ee3d-11ea-83d0-4ce77dc39760.png)

2020-09-03 23:38 UTC, Sxribe commented
Not a maintainer, but this project uses double-quotes `"`, not single-quotes `'`. Could you update that to maintain the current used standard?

2020-09-03 23:47 UTC, topiek-fs commented
Currently on mobile, where am I using single quotes? Can't really find it anywhere.

2020-09-04 00:19 UTC, Benjozork requested changes
Please configure your text editor to format your code properly.

2020-09-04 00:19 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
> +
Please fix indentation

2020-09-04 00:19 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
> +		let externalPowerChanged = (externalPower != this.externalPowerLastValue);
Please fix indentation

2020-09-04 00:19 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
> +		this.externalPowerLastValue = externalPower;
Please fix indentation

2020-09-04 00:19 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
> +		this.externalPowerLastValue = false;
Please fix indentation

2020-09-04 00:19 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
> +        this.selfTestDiv = document.querySelector('#SelfTestDiv');
Here for the single quotes

2020-09-04 00:19 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
> +            ) {
Please fix that `if` statement.

2020-09-04 00:19 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/MFD/A320_Neo_MFD.js
> +        this.updateScreenState();
Please fix indentation

2020-09-04 00:19 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/PFD/A320_Neo_PFD.js
>          switch (_event) {
Please fix indentation and formatting issues

2020-09-04 18:12 UTC, topiek-fs commented
Resolved above

2020-09-04 20:32 UTC, Benjozork commented
Looks way better !

Can someone test this ?

2020-09-04 21:36 UTC, nistei commented
Test OK from cold and dark.
Test OK when loading the aircraft on the runway.

2020-09-05 04:50 UTC, Benjozork approved these changes

2020-09-05 04:51 UTC, wpine215 approved these changes

2020-09-05 04:51 UTC, merged

2020-09-05 05:55 UTC, AdenFlorian commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
> +
I think this is causing PFD and MFD to go into self test when turning on the APU, even though I'm on external power.

Also causes self test when leaving external power, even though my apu or engine is up and running.

2020-09-05 06:05 UTC, AdenFlorian commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/A320_Neo_EICAS.js
> +
https://github.com/flybywiresim/a32nx/issues/402