fix(mcdu): init a crz fl / tmp spacing
flybywiresim/a32nx pull request #4033
Opened 2021-03-19 19:18 UTC by MisterChocker

Fixes #[issue_no]

## Summary of Changes

- Fixed crz fl / tmp spacing

## Screenshots (if necessary)

Before:
![image](https://user-images.githubusercontent.com/77690813/111826039-2dc9e980-8923-11eb-9990-8e92ec31f70d.png)
After:
![image](https://user-images.githubusercontent.com/1857322/111831781-22a99600-88f0-11eb-8d56-b416176d79c2.png)

## References

![image](https://user-images.githubusercontent.com/74841560/111828956-f5ef8180-88e3-11eb-8b47-d9af91f6867a.jpeg)

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Look at init a page and compare with reference.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2021-03-19 19:59 UTC, beheh requested changes

2021-03-19 19:59 UTC, beheh commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
> +                cruiseFlTemp = "_____\xa0|____[color]amber";
This is also missing the degree symbol:

```suggestion
                cruiseFlTemp = "_____\xa0|___°[color]amber";
```

FMS 1A reference, but unlikely this changed:

![image](https://user-images.githubusercontent.com/929769/111835754-a0bc6b80-88f5-11eb-8660-6d295d650afa.png)

2021-03-19 19:59 UTC, beheh commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
> +                        "{cyan}FL" + mcdu._cruiseFlightLevel.toFixed(0).padStart(3, "0") + "\xa0/" +
While you're at it, the slash should be small if TEMP is automatic:

![image](https://user-images.githubusercontent.com/929769/111835883-d5c8be00-88f5-11eb-9632-b7de6ea581a6.png)

![image](https://user-images.githubusercontent.com/929769/111835899-dc573580-88f5-11eb-8c77-6aad4443e54d.png)

2021-03-19 20:17 UTC, beheh commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_InitPage.js
> +                        (!!mcdu.cruiseTemperature ? "/" + mcdu.cruiseTemperature.toFixed(0) + "°" : "{small}/" + mcdu.tempCurve.evaluate(mcdu._cruiseFlightLevel).toFixed(0) + "°{end}") +
The double negation is redundant as it's evaluated anyway:

```suggestion
                        (mcdu.cruiseTemperature ? "/" + mcdu.cruiseTemperature.toFixed(0) + "°" : "{small}/" + mcdu.tempCurve.evaluate(mcdu._cruiseFlightLevel).toFixed(0) + "°{end}") +
```

2021-03-19 20:33 UTC, beheh approved these changes

2021-03-20 11:08 UTC, BritishAvgeek commented
Category: QA Tester
Name: BritishAvgeek#1436
Date of testing: 20/03/2021
Version of the sim: 1.14.5.0
PR Tested: #4033 
Tier of testing: 1
Changes to observe: small changes to INIT A page

Testing technique: Spawned C&D, check on ground
Steps you've made to test the Pull Request:
1. Spawned Cold and Dark and Gatwick, filled out data for a flight in the MCDU
2. Checked the pages mentioned above to text, font or spacing issues - none noticed 
3. Made a few changes to see how spacing is affected, no issues there either
4. End of Test

Flight notes (When done a full flight): N/A

Media: N/A

Issues (If Any): None found
Steps to achieve the issue

Overall Rating: Good
Conclusions of the testing: quick PR test with basic inputs on MCDU from EGKK to EGCC - remained on the ground. No issues found

2021-03-20 11:13 UTC, darkfury334 commented
Category: QA Trial
Name:DarkFury#4936
Date of testing: Current date 20/03/2021
PR Tested: #4033
Tier of testing: 1
Changes to observe:
 Fixed crz fl / tmp spacing
 Fixed From/To text positioning
 Fixed missing ° symbol on crz fl temp
 Fixed small slash on auto crz fl temp

Testing technique: Description of how you tested the Pull Request
Steps you've made to test the Pull Request:
1. Load in C&D at EGCC
2. Start Batteries / External pover
3. Click INIT page on MDCU
4.Check From/To text alignment,
5.Check CRZ FL /TEMP space,
6.Check CRL FL TEMP missing ° on entry boxes are fixed,
7.Import a flight plan
8.Check CRZ FL TEMP / is small when automatic populated.


Flight notes (When done a full flight):N/A

Media: 
![Microsoft Flight Simulator Screenshot 2021 03 20 - 10 50 51 83](https://user-images.githubusercontent.com/78447787/111867618-24fe0580-896d-11eb-8bd2-be12ba0eb769.png)

![Microsoft Flight Simulator Screenshot 2021 03 20 - 11 00 19 72](https://user-images.githubusercontent.com/78447787/111867638-4828b500-896d-11eb-8c07-44edd485f77b.png)


Issues (If Any): N/A
Overall Rating: Good
Conclusions of the testing: All Good.

2021-03-20 11:27 UTC, merged