Improved ECAM Messages System
flybywiresim/a32nx pull request #430
Opened 2020-09-05 23:56 UTC by tyler58546

**Summary of Changes**

* ECAM messages area has been completely redone
* Messages can now show on the right side of the ECAM
* Messages will now show in a consistent order
* Added many new ECAM messages
    * T.O. INHIBIT
    * LDG INHIBIT
    * APU BLEED
    * APU AVAIL
    * LDG LT
    * SPEED BRK
    * AUTO BRK LO
    * AUTO BRK MED
    * AUTO BRK MAX
* Added takeoff memo
    * Shows 2 mins after second engine start
    * Hides after takeoff thrust application
* Added landing memo
    * Shows below 2000 feet during approach phase
    * Hides after slowing down below 80kts
* Added support for failures to show on ECAM
* Added NAV TCAS FAULT failure when ADIRS are not aligned
* Added CAB PR EXCESS CAB ALT failure when cabin altitude exceeds 10000ft (can only be triggered by slewing to an extreme altitude)

**Screenshots (if necessary)**

![](https://cdn.discordapp.com/attachments/747971332301389935/751899884810010715/unknown.png)
![](https://cdn.discordapp.com/attachments/747971332301389935/751903140495753256/unknown.png)

2020-09-06 00:12 UTC, Benjozork reviewed
Great improvements !

2020-09-06 00:12 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +                for (var n = 0; n < category.messages.length; n++) {
Use `for ... of` here.

2020-09-06 00:12 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +            for (var i = 0; i < this.messages.failures.length; i++) {
Use `for ... of` here.

2020-09-06 00:12 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +                for (var n = 0; n < messages.length; n++) {
Use `for ... of` here.

2020-09-06 00:12 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +            var output = [];
Can be `const`.

2020-09-06 00:12 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +                var newDiv = document.createElement("div");
Can be `const`.

2020-09-06 00:12 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +            for (var i = 0; i < this.items.length; i++) {
Use `for ... of` here.

2020-09-06 00:12 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +            for (let item of this.items) {
Can be `const`.

2020-09-06 00:12 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +            for (var i = 0; i < this.allDivs.length; ++i) {
Use `for ... of` here.

2020-09-06 00:12 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +                var newDiv = document.createElement("div");
Can be `const`.

2020-09-06 00:12 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +        }
Some variables can be turned into `const`s here.

2020-09-06 00:12 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +        }
Some variables can be turned into `const`s here.

2020-09-06 00:12 UTC, Benjozork commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +            for (let item of this.items) {
Can be `const`.

2020-09-06 00:13 UTC, nabil74 commented
AESEOME CANT WAIT TILL THESE ARE MERGED !!!

 

Regards
Nabil Abaki



 

From: Benjamin Dupont <notifications@github.com> 
Sent: Sunday, 6 September 2020 10:13 AM
To: flybywiresim/a32nx <a32nx@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Subject: Re: [flybywiresim/a32nx] Improved ECAM Messages System (#430)

 

@Benjozork commented on this pull request.

Great improvements !

  _____  

In A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js <https://github.com/flybywiresim/a32nx/pull/430#discussion_r484002368> :

> +        init() {
+            super.init();
+            for (var i = 0; i < this.maxLines; i++) {
+                this.addDiv();
+            }
+        }
+        update() {
+            this.activeCategories = [];
+            this.currentLine = 0;
+            for (let div of this.allDivs) {
+                div.innerHTML = "";
+            }
+            const activeFailures = this.getActiveFailures();
+            for (const i in activeFailures) {
+                const category = activeFailures[i];
+                for (var n = 0; n < category.messages.length; n++) {

Use for ... of here.

  _____  

In A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js <https://github.com/flybywiresim/a32nx/pull/430#discussion_r484002414> :

> +                    }
+                    message.innerHTML = msgOutput;
+                    div.appendChild(message);
+
+                    if (!this.activeCategories.includes(_category)) {
+                        this.activeCategories.push(_category);
+                    }
+                }
+            }
+            this.currentLine++;
+        }
+
+        
+        getActiveFailures() {
+            var output = {};
+            for (var i = 0; i < this.messages.failures.length; i++) {

Use for ... of here.

  _____  

In A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js <https://github.com/flybywiresim/a32nx/pull/430#discussion_r484002435> :

> +                    div.appendChild(message);
+
+                    if (!this.activeCategories.includes(_category)) {
+                        this.activeCategories.push(_category);
+                    }
+                }
+            }
+            this.currentLine++;
+        }
+
+        
+        getActiveFailures() {
+            var output = {};
+            for (var i = 0; i < this.messages.failures.length; i++) {
+                const messages = this.messages.failures[i].messages;
+                for (var n = 0; n < messages.length; n++) {

Use for ... of here.

  _____  

In A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js <https://github.com/flybywiresim/a32nx/pull/430#discussion_r484002454> :

> +                for (var n = 0; n < messages.length; n++) {
+                    const message = messages[n];
+                    if (message.isActive()) {
+                        if (output[i] == null) {
+                            output[i] = this.messages.failures[i];
+                            output[i].messages = [];
+                        }
+                        output[i].messages.push(message);
+                    }
+                }
+            }
+            return output;
+        }
+
+        getActiveMessages() {
+            var output = [];

Can be const.

  _____  

In A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js <https://github.com/flybywiresim/a32nx/pull/430#discussion_r484002470> :

> +                }
+            }
+            return output;
+        }
+
+        getActiveMessages() {
+            var output = [];
+            for (const message of this.messages.normal) {
+                if (message.isActive()) output.push(message);
+            }
+            return output;
+        }
+
+        addDiv() {
+            if (this.divMain != null) {
+                var newDiv = document.createElement("div");

Can be const.

  _____  

In A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js <https://github.com/flybywiresim/a32nx/pull/430#discussion_r484002510> :

> +    }
+    A320_Neo_UpperECAM.MemoItem = MemoItem;
+
+    /**
+     * Represents an ECAM Memo
+     */
+    class Memo extends A320_Neo_UpperECAM.PanelBase {
+        constructor(_parent, _id, _title, _items) {
+            super(_parent, _id);
+            this.allDivs = [];
+            this.title =_title;
+            this.items = _items;
+        }
+        init() {
+            super.init();
+            for (var i = 0; i < this.items.length; i++) {

Use for ... of here.

  _____  

In A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js <https://github.com/flybywiresim/a32nx/pull/430#discussion_r484002555> :

> +     */
+    class Memo extends A320_Neo_UpperECAM.PanelBase {
+        constructor(_parent, _id, _title, _items) {
+            super(_parent, _id);
+            this.allDivs = [];
+            this.title =_title;
+            this.items = _items;
+        }
+        init() {
+            super.init();
+            for (var i = 0; i < this.items.length; i++) {
+                this.addItem(this.items[i], i === 0);
+            }
+        }
+        update() {
+            for (let item of this.items) {

Can be const.

  _____  

In A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js <https://github.com/flybywiresim/a32nx/pull/430#discussion_r484002587> :

> +            this.title =_title;
+            this.items = _items;
+        }
+        init() {
+            super.init();
+            for (var i = 0; i < this.items.length; i++) {
+                this.addItem(this.items[i], i === 0);
+            }
+        }
+        update() {
+            for (let item of this.items) {
+                this.setCompleted(item, item.isCompleted());
+            }
+        }
+        getNextAvailableDiv() {
+            for (var i = 0; i < this.allDivs.length; ++i) {

Use for ... of here.

  _____  

In A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js <https://github.com/flybywiresim/a32nx/pull/430#discussion_r484002593> :

> +                this.addItem(this.items[i], i === 0);
+            }
+        }
+        update() {
+            for (let item of this.items) {
+                this.setCompleted(item, item.isCompleted());
+            }
+        }
+        getNextAvailableDiv() {
+            for (var i = 0; i < this.allDivs.length; ++i) {
+                if (this.allDivs[i].textContent.length == 0) {
+                    return this.allDivs[i];
+                }
+            }
+            if (this.divMain != null) {
+                var newDiv = document.createElement("div");

Can be const.

  _____  

In A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js <https://github.com/flybywiresim/a32nx/pull/430#discussion_r484002621> :

> +        addItem(_item, _first) {
+            var div = this.getNextAvailableDiv();
+            if (div != null) {
+                if (_first) {
+                    var title = document.createElement("span");
+                    title.className = "Underline";
+                    title.textContent = this.title;
+                    div.appendChild(title);
+                }
+                
+                //Item name
+                var itemName = document.createElement("span");
+                itemName.innerHTML = _first ? " "+_item.name : "&nbsp;&nbsp;&nbsp;&nbsp;"+_item.name;
+                div.appendChild(itemName);
+
+                //Action
+                var action = document.createElement("span");
+                action.className = "Action";
+                var actionText = _item.action;
+                for (var i = 0; i < (19 - _item.name.le [...]

2020-09-06 00:44 UTC, tyler58546 commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +            for (var i = 0; i < this.items.length; i++) {
Need the `i` for `i === 1`

2020-09-06 07:57 UTC, wpine215 requested changes
Change "IR IN ALGIN" to "IR IN ALIGN" in A320_Neo_UpperECAM.js

2020-09-06 08:03 UTC, wpine215 requested changes
Received T.O. INHIBIT message during cold-and-dark setup at gate, with APU + APU bleed on, parking brake engaged, seat belts on, and no smoking auto (engines not started yet or in ignition).

2020-09-06 08:06 UTC, wpine215 commented
What are the conditions necessary for GPWS Fault to display?

2020-09-06 15:57 UTC, tyler58546 commented
@wpine215 
> Change "IR IN ALGIN" to "IR IN ALIGN" in A320_Neo_UpperECAM.js

> Received T.O. INHIBIT message during cold-and-dark setup at gate, with APU + APU bleed on, parking brake engaged, seat belts on, and no smoking auto (engines not started yet or in ignition).

Fixed.
> What are the conditions necessary for GPWS Fault to display?

It doesn't currently display. I was just using it as an example to show that multiple failures can show under the same category.

2020-09-06 19:32 UTC, wpine215 requested changes
"LDG LT" memo stays on even after landing lights are retracted following takeoff.
"TO INHIBIT" memo did not show up at all during takeoff roll. (However, LDG INHIBIT works fine on landing)
"FLAPS T.O." should only be marked as completed when the flaps are actually extended to takeoff position, instead of relying on the flap handle position. (Same for flaps full on landing)

2020-09-06 22:03 UTC, tyler58546 commented
I fixed T.O. INHIBIT not showing. It looks like there aren't any good simvars for flap position and landing lights.

2020-09-06 23:03 UTC, merged

2020-09-07 01:52 UTC, griffon55 commented
Landing memo stay on after landing even on the taxiway.
Seat belt and smoking sign button not working now.

2020-09-07 03:39 UTC, AdenFlorian commented
> Seat belt and smoking sign button not working now.
that fix just went to master, caused by different pr