feat(fwc): add L/G NOT DOWN
flybywiresim/a32nx pull request #5181
Opened 2021-06-21 23:59 UTC by Kimbyeoungjang

Fixes #[issue_no]

## Summary of Changes

## Screenshots (if necessary)

## References

![image](https://user-images.githubusercontent.com/23118756/122842219-e004b900-d337-11eb-9914-d9aa7df72b0b.png)
![image](https://user-images.githubusercontent.com/23118756/122842231-e98e2100-d337-11eb-96f8-7d4678328c5f.png)

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2021-06-22 12:00 UTC, beheh requested changes

2021-06-22 12:02 UTC, Kimbyeoungjang commented on flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
> +                    0 (&gt;L:PUSH_AUTOPILOT_MASTERCAUT)
Sorry. I was try to split from before PR so that code follow that.
should I revert that?

2021-06-22 12:03 UTC, Kimbyeoungjang commented on flybywire-aircraft-a320-neo/html_ui/Pages/A32NX_Core/A32NX_FWC.js
> +            const isEngine1Shutdown = (SimVar.GetSimVarValue("TURB ENG N1:1", "Percent") < 15 || SimVar.GetSimVarValue("FUELSYSTEM VALVE SWITCH:1", "Bool") == 0) && !Simplane.getIsGrounded();
this from old engine shutdown code. I'll fix it

2021-06-22 12:23 UTC, Kimbyeoungjang commented on flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
> +                    0 (&gt;L:PUSH_AUTOPILOT_MASTERCAUT)
lol I am idiot.

I change these names to reduce simvar.
also, master warning should not canceled by button when overspeed & l/d not down condition. So i change that

2021-08-14 12:26 UTC, 2hwk commented
This PR has not had much activity recently/is stale, so to help us categorize I'm converting this back to draft. You can mark it as ready for review once there is a status update or change pushed.

2022-02-15 21:30 UTC, aguther commented
Will be implemented with new FWC

2022-02-15 21:30 UTC, closed without merging