feat(adirs): separated adirus
flybywiresim/a32nx pull request #5242
Opened 2021-06-30 09:21 UTC by davidwalschots

Partially addresses #3335

## Summary of Changes
Currently the ADIRS' ADIRUs aren't separated: once a single ADIRU is aligned the PFD and ND on the left and right side will both fully work. In this PR, I modify the implementation such that each ADIRU is separated and has more functionality.

## Bug fixes

- [ ] The longest instead of the shortest remaining alignment time is displayed on the upper ECAM.

## Features

### Overhead panel

- [ ] IR1, IR3, or IR2 can be pushed OFF to disconnect output of IR information from that particular ADIRU.
- [ ] ADR1, ADR3, or ADR2 can be pushed OFF to disconnect output of ADR information from that particular ADIRU.
- [ ] ATT mode only supplies attitude and heading information to the IR portion of the ADIRU.

### PFD

- [ ] The selected ADR provides altitude (ALT), computer air speed (CAS), mach number (M), and barometric vertical speed (BARO V/S). 
- [ ] BARO V/S is a backup to inertial V/S.
- [ ] When the selected ADR does not provide CAS, the speed scale is replaced by a red SPD flag.
- [ ] When the selected ADR does not provide M, the mach number is replaced by a red MACH flag.
- [ ] When the selected ADR does not provide ALT, the altitude is replaced by a red ALT flag.

### ND
- [ ] The selected ADR provides true air speed (TAS).
- [ ] In case of selected ADR TAS failure, the value isn't displayed (blank).

### Lower ECAM

- [ ] ADR1 provides static air temperature (SAT), total air temperature (TAT) and international standard atmosphere temperature (ISA).
- [ ] In case of ADR1 failure, once the AIR DATA selector is set to CAPT 3, ADR3 will provide SAT, TAT and ISA.
- [ ] In case of selected ADR (1 or 3) failure, the TAT & SAT indications show amber crosses.

### Switching panel

- [ ] ADIRU1 supplies the captain's instruments when ATT HDG and AIR DATA are in the NORM position.
- [ ] ADIRU2 supplies the F/O's instruments when ATT HDG and AIR DATA are in the NORM position.
- [ ] ADIRU3 supplies the captain or F/O instruments with IR information when ATT HDG is switched to CAPT 3 or F/O 3.
- [ ] ADIRU3 supplies the captain or F/O instruments with ADR information when AIR DATA is switched to CAPT 3 or F/O 3.

## Future work

- When in ATT mode, the heading needs to be updated regularly within the MCDU.

## References

## Additional context

Discord username (if different from GitHub): SjotgunSjonnie#9623

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2021-07-22 22:01 UTC, Benjozork requested changes

2021-07-23 09:39 UTC, Benjozork approved these changes

2021-07-24 08:16 UTC, tracernz approved these changes

2021-07-24 09:34 UTC, frankkopp commented
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5242
Tier of Testing: 1
Date: 24.7.2021

Testing Process: 
- Started C&D on ground

OnGround:

- Turned on ADIRS one after the other waiting until ON  BAT goes out
- Waited until aligned - confirmed that ADIRs 1 and ADIRS 2 are independed as ND etc. showed alignment independendly. 
- Turned off ADIRS 2 - F.O. ND goes to MAP NOT AVAIL again
- Turned ADIRS 3 to F.O. via Switching panel ==> OK
- Tested the same for CAPT ADIRS 1 ==> OK
- Remaining alignment time is always the longest ==> OK
- Set ADIRS1 to ATT - switching back restarts alignment timer
- Turning IR or ADR OFF for each ADIR had the expected effect on CAPT/FO PFD/ND also when switching to ADIRS3 with IR3 or ADR3 off. ==> OK
- PFD logic as described ==> OK
- ND logic as described ==> OK
- TAS logic ==> OK
- GS logic ==> OK
- Wind logic ==> OK
- GPS logic ==> OK (one GPSSU is sufficient)
- Upper ECAM: ATT align msg ==> OK
- Lower ECAM logic ==> OK

Inflight:
- V/S still displayed when IR is turned off ==> OK (assuming usage of ADR baro v/s)
- no V/S when ADR and IR are not available ==> OK
- By turning off ADIRS3 and switching to CAPT: 
  - Confiormed TAS logic in flight ==> OK (not the actual boundary 60kts - but the general logic)
  - Confirmed GS logic
 
Negatives: None

Testing Results: Passed

Conclusions: 
- Awesome PR - works really well / hard to test all permutations

2021-07-24 10:05 UTC, marcman86 commented
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #5242
Tier of Testing: 1
Date: 23/07/2021

Testing Process:
- Spawned C&D at EDDP
- Turned on bat. and ext. power > MCDU and ND GPS PRIMARY LOST
- Test alignment time display > works, also MCDU GPS PRIMARY
- ATT1 > Pilot ND MAP NOT AVAIL
- ATT2 > F/O ND MAP NOT AVAI
- ATT3 > Pilot ND MAP NOT AVAIL, when switched to ADIRS3
- IR1 > Pilot displays show red ATT and MAP NOT AVAIL
- IR2 > F/O displays show red ATT and MAP NOT AVAIL
- IR3 > Pilot displays show red ATT and MAP NOT AVAIL, when switched to ADIRS3
- ADR1 > Pilot PFD SPD, MACH. ALT red
- ADR2 > F/O PFD SPD, MACH. ALT red
- ADR3 > Pilot PFD SPD, MACH. ALT red, when switched to ADIRS3
- Took off
- Wind displayed at TAS > 100kts 
- SAT, TAT, ISA
- Tested switching panel ATT HDG and AIR DATA


Negatives: SET an ADIRS in ATT and back to NAV it needs time to align (the ND is still red for a few minutes). This is where i expect IR X IN ATT ALIGN. These messages dont show up in air. After restart i tryed this on ground. Here only IR IN ALIGN X MN is shown.

Testing Results: Passed. Maybe small fixing is needed.
Conclusions: Awesome PR! So many new functions. Only the ATT ALIGN messages dont work for me. But i also dont know how to trigger them exactly.

Hope this helps :-)

2021-07-24 10:49 UTC, merged