refactor(lights): new potentiometer for lights, emissives and screens
flybywiresim/a32nx pull request #5244
Opened 2021-06-30 11:58 UTC by bouveng

![122734264-357c8f80-d27e-11eb-82f5-a12c8d06dc5d](https://user-images.githubusercontent.com/433429/123943407-6a829380-d99c-11eb-9e95-aef3a4c35f87.gif)

Fixes #2901, #1450
Previous 3 PR's for this functionality: #5177, #5182 and #5183  is **CLOSED**.

## Summary of Changes
- New potentiometer for **ALL** knobs used for lights, emissives and screens
- Stepless + Silent
- 0-100% in steps of 1 for **click/hold**
- 5x speed with **MOUSEWHEEL**
- Annotates **TOOLTIPS** with current %-setting
- Adjusted **MAIN PNL FLOOD LT** and **FLOOD LT PED**
- Indirect light (ambient) added to **MAIN PNL FLOOD LT** and **FLOOD LT PED**

**Affected potentiometers:**
- MAIN PNL FLOOD LT
- INTEG LT MAIN PNL & PED
- FLOOD LT PED

- CPT READING LT

- CPT TABLE LT
- F/O READING LT
- CPT PFD/ND/WX SCREENS
- F/O PFD/ND/WX SCREENS
- ECAM UPPER & LOWER SCREENS
- F/O TABLE LT
- FCU INTEG LT
- FCU LED DISPLAY LT

**Also affected, but controls no light and has no tooltip annotations:**
- COCKPIT, FWS, AFT CABIN AIRCON
- LDG ELEV AUTO

## Screenshots (if necessary)
![Microsoft Flight Simulator 2021-06-30 12_45_36](https://user-images.githubusercontent.com/433429/123955498-f818b000-d9a9-11eb-9191-eed5bd4618c7.png)
![Microsoft Flight Simulator 2021-06-30 12_43_54](https://user-images.githubusercontent.com/433429/123955441-e7683a00-d9a9-11eb-8184-82cf02d9bf50.png)
![Microsoft Flight Simulator 2021-06-30 13_07_37](https://user-images.githubusercontent.com/433429/123955622-1d0d2300-d9aa-11eb-8468-c274e2e6efd2.png)
![annotation](https://user-images.githubusercontent.com/433429/123955897-72493480-d9aa-11eb-858f-d21377e07abd.png)
Potentiometer with tooltip annotation showing power-setting

## References

> They are just rotary knobs with no off indentation to confirm it's off. Just spin it one way for light and the other for darkness
> — Tricker

![122999679-dff3d000-d3ae-11eb-86c9-ba697759c113](https://user-images.githubusercontent.com/433429/123955046-72950000-d9a9-11eb-8e6a-8efca4dde9d8.jpg)

![122999530-ae7b0480-d3ae-11eb-8ff1-9c9e3185501f](https://user-images.githubusercontent.com/433429/123955192-a1ab7180-d9a9-11eb-987c-c896d09887ee.jpg)

## Additional notes
- Intensity is a function of input power, but it is not 100% linear
- Emissives behaves differently than lights
- Expect most visible in bottom to mid ranges

Discord username: bouveng

## Testing instructions

1, Spawn C&D, somewhere dark, with as little external lights as possible (on RW29 at EKRN for example)
2, Power aircraft in any suitable way if needed.
3, Turn of any interfering lights, integrated lights, screen, etc to your liking.
4, Try out the potentiometers with both click/hold/mousewheel for affected potentiometers:
- MAIN PNL FLOOD LT
- INTEG LT MAIN PNL & PED
- FLOOD LT PED
- OVHD INTEG LT
- CPT READING LT
- F/O READING LT
- CPT PFD/ND/WX SCREENS
- F/O PFD/ND/WX SCREENS
- CPT TABLE LT
- F/O TABLE LT
- FCU INTEG LT
- FCU LED DISPLAY LT
- ECAM UPPER & LOWER SCREENS

5, Verify that COCKPIT, FWD, AFT CABIN AIRCON and LDG ELEV AUTO still works as expected

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2021-06-30 22:56 UTC, bouveng commented
Spotted **small** issue. Converted to **draft** while I fix.

2021-07-01 22:23 UTC, Benjozork requested changes

2021-07-01 22:23 UTC, Benjozork commented on flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
>                  <ANIM_NAME>LIGHTING_Knob_Pedestal</ANIM_NAME>
Since those are almost always the same, the template should set the latter two to be equivalent to `NODE_ID` by default.

2021-07-01 22:23 UTC, Benjozork commented on flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
> +                <!-- ECAM UPPER DISPLAY BRIGHTNESS -->
This comment should be consistent with the other ones:

`<!-- UPPER ECAM SCREEN -->`

2021-07-01 22:23 UTC, Benjozork commented on flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
> +                <!-- ECAM LOWER DISPLAY BRIGHTNESS -->
Ditto

2021-07-01 22:23 UTC, Benjozork commented on flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
> +
```suggestion
```

2021-07-01 22:23 UTC, Benjozork commented on flybywire-aircraft-a320-neo/SimObjects/AirPlanes/FlyByWire_A320_NEO/model/A320_NEO_INTERIOR.xml
>                          <UseTemplate Name="FBW_Continuous_Knob_Limited_From_Simvar">
Why do we have both `L:A32NX_LANDING_ELEVATION` and `L:XMLVAR_KNOB_OVHD_CABINPRESS_LDGELEV` ?

2021-07-01 22:23 UTC, Benjozork commented on src/behavior/src/A32NX_Interior_Generics.xml
> +            - ANIM_SIMVAR_TYPE      <no default>            The type of variable used to drive animation
We can combine those.

2021-07-03 16:25 UTC, TheSledge-SLEJ commented
Excited for this one! Great work

2021-07-04 08:22 UTC, Benjozork approved these changes

2021-07-04 11:33 UTC, marcman86 commented
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #5244
Tier of Testing: 1
Date: 4/07/2021

Testing Process:
- Spawned C&D at EDDP
- Turned on bat. and ext. power
- Tested light and display brightness knobs
- Tested other knobs
- Tested ambient light on a dark spot

Negatives: -

Question: Needs there be an on/off click? So 0, click to 1, then silent to 100. 

Testing Results: Passed
Conclusions: Works, nice work. For my part i would like more rough steppings on the mousewheel, like before 10.
Media:-

Hope this helps :-)

2021-07-04 17:19 UTC, bouveng commented
> Question: Needs there be an on/off click? So 0, click to 1, then silent to 100.

Hi! No, these potentiometers do not work like that, confirmed by Tricker in the reference section of the PR. =)

> Conclusions: Works, nice work. For my part i would like more rough steppings on the mousewheel, like before 10.

0-10 was the steps before, no matter using clicks or mouse-wheel, as that was a limit within the potentiometer itself.
No you get 5 instead, so people using mouse-wheel gets a small cut of the increased control over light.
Also, since most of the intensity range happens between 0-50%, the you still have "10" steps to "max".

For precision setting, clicks is the way to go.

Br.

/J

2021-07-04 19:22 UTC, St54Kevin commented
**Quality Assurance Tester**

Object of testing: #5244 
Tier of Testing: 1
Date: 04/07/2021

**Testing Process:**
1. Loaded up C&D in the black night and powered up
2. Tested all above mentioned light knobs in full range
3. Did the same again in day light and dusk

**Negatives:** N/A
**Testing Results:** Mouse Wheel mafia approves!

2021-07-04 20:24 UTC, frankkopp commented
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #5244
Tier of Testing: 1
Date: 04.07.2021

Testing Process:

Try out the potentiometers with both click/hold/mousewheel for affected potentiometers:
• MAIN PNL FLOOD LT ==> OK
• INTEG LT MAIN PNL & PED ==> OK
• FLOOD LT PED ==> OK
• OVHD INTEG LT ==> OK
• CPT READING LT ==> OK
• CPT TABLE LT  ==> OK
• F/O READING LT ==> OK
• F/O TABLE LT ==> OK
• CPT PFD/ND/WX SCREENS ==> OK
• F/O PFD/ND/WX SCREENS ==> OK
• ECAM UPPER & LOWER SCREENS ==> OK 
• FCU INTEG LT ==> OK
• FCU LED DISPLAY LT ==> OK

5, Verify that COCKPIT, FWD, AFT CABIN AIRCON and LDG ELEV still works as expected
==> OK

Negatives: N/A

Testing Results: Passed

Conclusions: 
I really like the stepping with 5% and the speed of click&hold. 

Remark: AIRCON and LDG ELEV have no tooltip - probably no part of this PR

2021-07-04 21:52 UTC, bouveng commented
> Remark: AIRCON and LDG ELEV have no tooltip - probably no part of this PR

Correct. They are potentiometers by definition and underlaying functionality as they share the same code, but they are no potentiometers that controls lights, emissives or screens, so they do not get the tooltip, showing degrees Celsius and feet instead.

Br.

/J

2021-07-05 16:37 UTC, TheSledge-SLEJ commented
Oh I'm not waiting for this to merge.
No...I'm not waiting for this to merge...
Waiting for this to merge? Me? Noooo...

...

2021-07-05 20:02 UTC, merged