Flypados v2 view state fixes
flybywiresim/a32nx pull request #5274
Opened 2021-07-05 19:14 UTC by antonyisoardi

Fixes #4575

## Summary of Changes

Updates to maintain view state of views when navigating away from them. From now on, when a user is in a "sub-view" for Performance or Dispatch, then will the last selected sub-view when the return to Performance or Dispatch

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2021-07-05 20:39 UTC, Benjozork commented
Note that this needs to be ported over when we switch back to react router

2021-07-11 18:48 UTC, Benjozork requested changes

2021-07-11 18:48 UTC, Benjozork commented on src/instruments/src/EFB/Components/Navbar.tsx
> +    activeIndex: number
```suggestion
    activeIndex: number,
```

2021-07-11 18:49 UTC, Benjozork commented on src/instruments/src/EFB/Store/performance-reducer.ts
> +// export const PerformanceContext:Context<PerformanceContextType> = createContext<PerformanceContextType>({ performanceState: performanceInitialState, performanceDispatch: () => {} });
```suggestion
```

2021-07-11 18:49 UTC, Benjozork approved these changes

2021-07-11 18:50 UTC, Benjozork commented
@antonyisoardi Can you please fill in the testing instructions ?

2021-07-12 11:27 UTC, St54Kevin commented
**Quality Assurance Tester**

Object of testing: #5274 
Tier of Testing: 1
Date: 12/07/2021

**Testing Process:**
1. Loaded in and tested EFB all subpages

**Negatives:** N/A
**Testing Results:** Passed

2021-07-12 22:52 UTC, hiaaryan commented
Please fix conflicts 😄

2021-07-20 11:33 UTC, TheSledge-SLEJ commented
Thanks for working on this. Will be a fab milestone when complete.

2021-07-24 04:25 UTC, antonyisoardi commented
@St54Kevin ready for retest please

@Benjozork @hiaaryan @TheSledge-SLEJ - refactored code ready for your review. Once this is in, I'll pick up the other state management stuff that @hiaaryan has raised for some of the other views and probably a bit of a refactor on the navigraph stuff to bring it inline with these views.

Cheers

2021-07-24 05:23 UTC, hiaaryan commented
If it does not fix #5307 you can remove it from the description :)

2021-07-24 05:26 UTC, hiaaryan requested changes

2021-07-24 05:26 UTC, hiaaryan commented on src/instruments/src/EFB/Dispatch/Pages/FuelPage.tsx
> +                            <div className="flex mt-4">
this should not have flex class.

2021-07-24 05:26 UTC, hiaaryan commented on src/instruments/src/EFB/Dispatch/Pages/FuelPage.tsx
> +                            <div className="flex mt-4">
this should not have flex class.

2021-07-24 08:41 UTC, hiaaryan commented on src/instruments/src/EFB/Dispatch/Pages/FuelPage.tsx
> +                            <div className="flex mt-4">
This has not been removed still :D

2021-07-29 12:30 UTC, hiaaryan approved these changes

2021-07-29 13:00 UTC, davidwalschots requested changes

2021-07-29 13:00 UTC, davidwalschots commented on package.json
> +    "postcss": "^8.3.5",
**issue**: duplicate
```suggestion
```

2021-07-29 13:01 UTC, davidwalschots commented
Can we get a clean commit history please?

2021-07-29 13:02 UTC, hiaaryan commented on package.json
> +    "postcss": "^8.3.5",
wow, sorry, missed it somehow 😅

2021-07-29 14:44 UTC, Benjozork requested changes
Ok I'm sorry for saying this now, but we cannot keep adding more Redux stuff. This should be done with react-router, properly.

Either we wait until another PR migrates the EFB to react-router or we make this PR switch it.

2021-07-29 14:47 UTC, antonyisoardi commented
> Ok I'm sorry for saying this now, but we cannot keep adding more Redux stuff. This should be done with react-router, properly.
> 
> Either we wait until another PR migrates the EFB to react-router or we make this PR switch it.

React Router will not give you state persistence. So what is it you want to achieve by using router?

2021-07-29 14:53 UTC, Benjozork commented
I would like the routing system to be refactored before we do this. I didn't mean doing this with react router.

2021-07-29 14:54 UTC, Benjozork commented
We have too many problems in the EFB right now that require refactors, especially regarding Redux, so I'd like to start ASAP. It's gonna block us very soon.

2021-07-29 14:59 UTC, Benjozork commented
Here are the main issues.

- There's unclear use of Redux and sometimes uses of it that I feel are unjustified.

- There are complex components that seem to either be overengineered or badly designed.

- The routing system is currently relying on react state. It's very messy.

I think the third one is where we should start.

2021-07-29 15:17 UTC, davidwalschots commented
To add to this. The mixing of module systems and JS/TS isn't good either. I guess this all stems from the fact that the EFB, and all other instruments are in the same "project" instead of being cleanly separated.

I would have liked to use a provider I built as part of the failures package:
```typescript
import { FailuresOrchestratorProvider } from '@flybywiresim/failures';
```
but I can't do that, because the file in which I want to use it is `index.jsx` instead of `index.tsx`. Changing to `tsx` brings its own problems as there is still a `js` import:
```typescript
import { getSimVar, setSimVar } from '../util.js';
```

Now I will have to figure out a way to deal with this, and I will, because I want to complete implementing the bare bones of failures. It is however a needlessly complex and time consuming affair. 😀

2021-07-29 15:19 UTC, Benjozork commented
We should definitely remove the JS files in `src/` I think. Unfortunately the PFD still uses them. We could duplicate those functions to a TS module for now?

2021-07-29 15:19 UTC, Benjozork commented
Maybe an issue should be opened for this!

2021-08-13 07:02 UTC, Venorcis commented
> If it does not fix #5307 you can remove it from the description :)

This pull indeed does not seem to fix the chartsview persisting when you navigate, or am I missing something?

2021-08-14 11:29 UTC, 2hwk commented
I will be moving this as under the 0.8.0 milestone, as we are planning to release 0.7.0 fairly soon.

2021-08-22 02:15 UTC, oim1 commented
Quality Assurance Trainee Report

Object of testing: (#5274)
Tier of Testing: 1
Date: 22/08/2021

Testing Process: 
Loaded Cold and Dark at YMML
Turned on Flypad
Copied simbrief flightplan
Clicked on Dispatch > OFP
Clicked onto another page 
Went back into Dispatch Page
Checked to see if it remained on OFP. 
Repeated for perf page. 

Negatives: It didn't remain on any subpage when I clicked back on.
Testing Results: Not Passed

Media: 

https://user-images.githubusercontent.com/81839029/130339662-087128ef-ffbd-4196-ba20-0cdfc041d713.mp4

2021-08-23 03:22 UTC, oim1 commented
Quality Assurance Trainee Report

Object of testing: (#5274)
Tier of Testing: 1
Date: 23/08/2021

Testing Process:
Loaded Cold and Dark at YMML
Turned on Flypad
Copied simbrief flightplan
Clicked on Dispatch > OFP
Clicked onto another page
Went back into Dispatch Page
Checked to see if it remained on OFP.
Repeated for perf page.

Negatives: N/A
Testing Results: Passed

Conclusion: Both performance and dispatch page remained on their subpage after moving away from them. Not sure what happened in the previous test but a reinstall of msfs seems to have fixed it. LGTM.

2021-08-28 03:37 UTC, Benjozork commented
Please fix conflicts.

2022-01-26 14:44 UTC, ErickSharp commented
This is being done in Flypad OS 3

2022-01-26 14:44 UTC, closed without merging