fix(pfd): FMA Showing FDs Engaged While ADIRs Not Aligned
flybywiresim/a32nx pull request #5375
Opened 2021-07-23 03:57 UTC by tracernz

Fixes #4242 (actually Andreas already did most of it)

## Summary of Changes

FDs are automatically armed by the FMGC on power-up. The FDs should not be engaged on the ground until at least 2 ADIRUs are aligned. Implemented this logic in the PFD for now, but it should eventually move into the FMGC after CFPM merges. @davidwalschots may want to pull the ADIRs change into his tree for #5242 and sequence this PR after it. Noticed by Ryan_D1994.

## Screenshots (if necessary)

Before:
![image](https://user-images.githubusercontent.com/9995998/126735698-0c00541b-2269-454f-b0dd-6e015151d0da.png)

After:
![image](https://user-images.githubusercontent.com/9995998/126735579-e37d34fc-9be4-4229-bc74-cf74860e068d.png)

## References

ATA22 training manual.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2021-07-23 07:17 UTC, davidwalschots commented
I think the dependency here is reversed. You should wait for #5242 to be merged, as `ADIRS_NUM_ALIGNED` is no longer needed once that PR is merged. Secondly, you could consider fixing this in cFPM, as it does indeed belong there and would remove the need to fix it multiple times.

2021-07-23 07:45 UTC, davidwalschots requested changes

2021-07-23 07:45 UTC, davidwalschots commented on src/systems/systems/src/adirs/mod.rs
> +    }
**thought**: Can make use of `filter` and `count`.
**suggestion**: See below, note that you need to add a `Write` implementation for `usize` for this in `systems/src/simulation/mod.rs`.

```suggestion
    fn number_aligned(&self) -> usize {
        self.adirus
            .iter()
            .filter(|adiru| adiru.is_aligned()).count()
    }
```

2021-07-23 07:45 UTC, davidwalschots commented on src/systems/systems/src/adirs/mod.rs
> +    const NUMBER_ALIGNED_KEY: &'static str = "ADIRS_NUM_ALIGNED";
**issue**: Missing `a320-simvars.md` documentation.

2021-07-23 07:45 UTC, davidwalschots commented on src/systems/systems/src/adirs/mod.rs
> +        writer.write(Self::NUMBER_ALIGNED_KEY, self.number_aligned());
**issue**: Missing unit test(s).

2021-08-14 12:27 UTC, 2hwk commented
This PR has not had much activity recently/is stale, so to help us categorize I'm converting this back to draft. You can mark it as ready for review once there is a status update or change pushed.

2021-08-14 14:55 UTC, tracernz commented
> This PR has not had much activity recently/is stale, so to help us categorize I'm converting this back to draft. You can mark it as ready for review once there is a status update or change pushed.

Unfortunately I think this really needs to be done in simulink, to prevent modes arming as well. I’ll keep it for now…

2022-03-08 23:22 UTC, closed without merging