Fix of issue #5574 where strobe lights would turn on when switched off
flybywiresim/a32nx pull request #5595
Opened 2021-08-08 23:32 UTC by ryan205

Fixes #5579

## Summary of Changes

Simple bug fix that addresses issue #5579 whereby the strobe lights turn ON when turned OFF on the overhead panel. Fix now ensures that strobe lights turn OFF when switched OFF. 

## Screenshots (if necessary)

None

## References

None required - trivial fix.

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Initialise aircraft in dark environment for ease of testing.
2. Ensure Strobe lights are in AUTO/ON position prior to beginning test.
2. To begin test, move strobe lights to OFF position. 
3. Move to external camera view, and focus on strobe lights over the wing. 
4. Verify that strobe lights are now OFF, vs. ON prior to this bug fix. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2021-08-09 01:35 UTC, 2hwk commented
LGTM, ready for QA.

2021-08-09 01:35 UTC, 2hwk submitted a review, later dismissed

2021-08-09 01:56 UTC, bouveng commented
@ryan205 Hi, just curious. Why does this work? ECAM has nothing to do with exterior lightning, or have I misunderstood the bug?

2021-08-09 04:27 UTC, sidnov commented
I agree to what @bouveng mentioned here.
All this PR does at the moment is change the condition for the message "STROBE LT OFF" to appear. It does not manipulate when strobe turn off or on. Try taking off with strobe switch in the off position. They still turn on.

2021-08-09 04:28 UTC, sidnov requested changes

2021-08-09 04:28 UTC, sidnov commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/EICAS/ECAM/A320_Neo_UpperECAM.js
> +                            this.isInFlightPhase(6, 7, 8) && !this.getCachedSimVar("LIGHT STROBE OFF", "Bool")
It only prevents the message from appearing at all, when departing with strobe light in off position, instead of changing the strobe behavior itself.

2021-08-13 13:34 UTC, 2hwk commented
@ryan205 I've bumped this back to draft, I suspect this may be a deeper issue with the stock asobo model behaviour XML template being used. Let us know if you are still working on this.

2021-08-17 01:36 UTC, closed without merging