docs: updates to README FAQ, technical specification, and fixed links
flybywiresim/a32nx pull request #5710
Opened 2021-08-24 08:49 UTC by Benjozork

## Summary of Changes

This PR improves the following about the README:

- Adds three questions related to project goal and advancement;
- Fixes `flightsim.to` liveries link (requested by @bouveng);
- Specifies APU model and fixes FMGS release in aircraft technical specification.

Discord username (if different from GitHub): someperson#4953

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2021-08-29 08:55 UTC, frankkopp requested changes
I suggest use of "feature X" instead of "X feature" or only "X".
Otherwise LGTM

2021-08-29 08:55 UTC, frankkopp commented on README.md
> +### Is X feature from the A320neo going to be implemented?
Better grammar:
Is feature X from the A320neo going to be implemented?

2021-08-29 08:55 UTC, frankkopp commented on README.md
> +### Why has X not been implemented yet?
Consistency with question above:
Why has feature X not been implemented yet?

2021-08-30 21:35 UTC, bouveng approved these changes

2021-08-30 21:35 UTC, bouveng commented on README.md
```suggestion

### Is there a list of features or a changelog available?

We do not keep a list of features implemented, but a lengthy [changelog](https://github.com/flybywiresim/a32nx/blob/master/.github/CHANGELOG.md) of what has been implemented, and their associated [pull requests](https://github.com/flybywiresim/a32nx/pulls) can be [found here](https://github.com/flybywiresim/a32nx/blob/master/.github/CHANGELOG.md).

```

Somewhat hard to locate if you do not know github file structure.

2021-09-01 01:30 UTC, bouveng approved these changes

2021-09-01 11:36 UTC, bouveng approved these changes

2021-09-02 05:08 UTC, merged