feat(model): add portholes
flybywiresim/a32nx pull request #6107
Opened 2021-10-29 17:00 UTC by igor8518

Fixes #6094 

## Summary of Changes
This PR adds four portholes. Two opposite the existing ones, and two above the wing.

## Screenshots (if necessary)

![1250410_20211031101511_1](https://user-images.githubusercontent.com/24699399/139565672-db257ad4-e496-47e9-ae60-fb2b161b63da.png)
![1250410_20211031101530_1](https://user-images.githubusercontent.com/24699399/139565682-8ee201cb-c703-4251-8df0-60a289d83a7c.png)
![1250410_20211031101543_1](https://user-images.githubusercontent.com/24699399/139565686-2ffca5d0-7378-4d02-b4c6-cd0c8b4b6007.png)
![1250410_20211031101554_1](https://user-images.githubusercontent.com/24699399/139565690-1ae17865-4bce-4ee9-a8c0-b923ea97a66a.png)
![1250410_20211031101607_1](https://user-images.githubusercontent.com/24699399/139565692-4b65dab7-a64d-46e6-888d-ccccfe369d32.png)
![1250410_20211031101619_1](https://user-images.githubusercontent.com/24699399/139565694-a6b2a3f0-15c9-48cf-ad39-127b97c5a3f9.png)

## References

## Additional context

### Nodes for control:
**Legacy:**

-   HublotIn
-   glass
-   HublotIn002
-   glass002

**Added:**

-   HublotIn003
-   glass003
-   HublotIn004
-   glass004
-   HublotIn005
-   glass005
-   HublotIn006
-   glass006

 

Discord username: igor8518

## Testing instructions
Just check if there are any visual artifacts on the internal and external model.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2021-10-29 18:39 UTC, BlueberryKing commented
Hello! If you are still working on this PR, you can mark it as a draft on GitHub to make it clear to everybody.

2021-10-30 12:38 UTC, bouveng commented
@igor8518 Hi! Nice! What's left to do on this? Could you provide the node-names for all port-holes as additional context for this PR? Would be useful if we want to toggle the visibility for all portholes sometime in the future.

Br.

2021-10-30 15:20 UTC, igor8518 commented
> @igor8518 Hi! Nice! What's left to do on this? Could you provide the node-names for all port-holes as additional context for this PR? Would be useful if we want to toggle the visibility for all portholes sometime in the future.
> 
> Br.

Hi!
Done.

2021-10-30 16:53 UTC, bouveng approved these changes
LGTM, but @tracernz should have a look as well.

2021-10-30 19:06 UTC, marcman86 commented
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #6107
Tier of Testing: 1
Date: 30/10/2021

Testing Process:
- Spawned C&D at EDDB
- Swithed to fixed external views

Negatives: - Windows are only visible on external view 12 and 13

Testing Results: Not passed
Conclusions: Same as before the PR

Hope this helps :-)

2021-10-30 20:21 UTC, bouveng commented
> Negatives: - Windows are only visible on external view 12 and 13

@marcman86 Are you using the default A32NX views? I think these views are part of the fixed showcase views.

Br.

2021-10-30 20:41 UTC, marcman86 commented
I tested all available fixed external views. Also the ones added by #3702. In these views i expect the new windows. If not then the PR description is not clear enough.

2021-10-30 21:18 UTC, bouveng commented
> In these views i expect the new windows. If not then the PR description is not clear enough.

Sure, these should be in the same array as the 2 other porthole views. And should be visible when using the showcase cam.

@igor8518 Where are the windows? :see_no_evil:

2021-10-31 03:20 UTC, igor8518 commented
Corrected fixed cameras 14-19 in cameras.cfg. I also corrected screenshots from new cameras. I suggest removing cameras 12, 13.

2021-10-31 08:07 UTC, bouveng approved these changes

2021-10-31 11:01 UTC, frankkopp commented
Quality Assurance Tester Report

Discord: Cdr_Maverick#6475
Object of testing: #6107
Tier of Testing: 1
Date: 31.10.2021

Testing Process: 
C&D at gate
External and Drone view detailed checks
Fixed camera checks
Looking for artefacts and errors
Tested with default livery and one custom livery

Negatives: none

Testing Results: passed

Conclusions: some redundancy but this has been commented already.

2021-10-31 12:48 UTC, marcman86 commented
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #6107
Tier of Testing: 1
Date: 31/10/2021

Testing Process:
- Spawned C&D at EDDV
- Swithed to fixed external views

Negatives: - 

Testing Results: Passed
Conclusions: Works for me

Hope this helps :-)

2021-11-02 08:21 UTC, tracernz commented
So up to now we've only accepted valid gltf files for merging, and used models.json to modify/add individual bits. I see you've changed it to accept invalid/incomplete gltf files...  Can we not just do the same thing as we've done before even if just for consistencies sake?

2021-11-02 15:05 UTC, igor8518 commented
I agree with you. It just seems to me that models.json turns into an inconvenient file for editing.  

I'll redo it according to your conditions.

2021-11-03 10:26 UTC, bouveng commented
@igor8518 Changed to draft until new impl. is ready.

2021-11-03 23:35 UTC, tracernz commented
> I agree with you. It just seems to me that models.json turns into an inconvenient file for editing.
> 
> I'll redo it according to your conditions.

Yeah, I in some ways like what you did. The thing that swings me is consistency. Let me know if it proves difficult for some reason and we can reconsider.

2021-11-04 02:36 UTC, igor8518 commented
@tracernz, changed the method of adding nodes to the scene, according to your requirements.

2021-11-04 16:57 UTC, bouveng approved these changes
Needs approval from @tracernz as well.

2021-11-05 02:33 UTC, tracernz approved these changes
Thanks for the contribution!

I think the model script is getting to the point it needs a refactor (it really was prior to this PR as well 😛), but that is beyond the scope of your PR.

2021-11-05 02:41 UTC, igor8518 commented
Thank you, Michael. 
I'm currently working on a passenger cabin. At the same time, I found a lot of problems with the visual model from Asobo.

2021-11-05 02:44 UTC, tracernz commented
> 
> 
> Thank you, Michael. I'm currently working on a passenger cabin. At the same time, I found a lot of problems with the visual model from Asobo.

Are you able to go on Discord? It would be good to loop in with our modelling people, as they're already working on an entirely new A320 model, using none of the Asobo assets. https://discord.gg/flybywire

2021-11-05 02:57 UTC, igor8518 commented
I'll try a little later.

2021-11-05 15:21 UTC, bouveng commented
@igor8518 Please fix linting errors. 🔍🧐

```
/external/src/model/build.js
  50:9   error  'nodesBackup' is never reassigned. Use 'const' instead  prefer-const

  88:32  error  Block must not be padded by blank lines                 padded-blocks

  97:2   error  Unnecessary semicolon                                   no-extra-semi`
```

2021-11-06 11:19 UTC, bouveng requested changes
Fix lint errors, suggestions added.

```
50:9   error  'nodesBackup' is never reassigned. Use 'const' instead  prefer-const
88:32  error  Block must not be padded by blank lines                 padded-blocks
97:2   error  Unnecessary semicolon                                   no-extra-semi
```

2021-11-06 11:19 UTC, bouveng commented on src/model/build.js
> +    let nodesBackup = nodes;
```suggestion
    const nodesBackup = nodes;
```

2021-11-06 11:19 UTC, bouveng commented on src/model/build.js
> +    }
```suggestion
        gltfA.nodes.push(node);
    }
```

2021-11-06 11:19 UTC, bouveng commented on src/model/build.js
> +};
```suggestion
}
```

2021-11-06 17:10 UTC, bouveng approved these changes

2021-11-06 21:17 UTC, marcman86 commented
Quality Assurance Tester Report
Discord:marcman86#4907
Object of testing: #6107
Tier of Testing: 1
Date: 6/11/2021

Testing Process:
- Spawned C&D at EDDH
- Swithed to fixed external views

Negatives: - 

Testing Results: Passed
Conclusions: Works for me

Hope this helps :-)

2021-11-07 07:41 UTC, tracernz approved these changes

2021-11-07 12:52 UTC, xZreai commented
Quality Assurance Trainee Report

Discord: Cleon#5802
Object of testing: #6107
Tier of Testing: (1)
Date: (07/11/2021)

Testing Process: 
Spawned C/D at VHHH
Went into camera options and checked new camera views
Tested camera views via keybinds


Negatives: Nil


Testing Results: PASS


Conclusions: nil


Media: 
A nice departure on today's VATSIM event ;)
![image](https://user-images.githubusercontent.com/81078099/140645700-ae320309-ee17-42af-9902-aafff1e658bf.png)

2021-11-07 12:59 UTC, igor8518 commented
@xZreai, thank you.))

2021-11-07 12:59 UTC, merged

2021-11-07 13:00 UTC, bouveng commented
@igor8518 Merged! :sunglasses:

2021-11-08 16:42 UTC, bouveng commented
> Corrected fixed cameras 14-19 in cameras.cfg. I also corrected screenshots from new cameras in EDDB(!) airport. I suggest removing cameras 12, 13.

Cameras 12, 13 where redundant, and now replaced with the previous views 14-15, that some user missed.
See https://github.com/flybywiresim/a32nx/pull/6158

2021-11-10 13:52 UTC, bouveng commented
@igor8518 They seem to like it =) https://www.facebook.com/FlyByWireSimulations/posts/364343638770553

2021-11-10 14:26 UTC, igor8518 commented
:)

2021-11-10 14:35 UTC, igor8518 commented
How to insert a picture? )))

2021-11-10 14:36 UTC, igor8518 commented
![1250410_20211110212722_1](https://user-images.githubusercontent.com/24699399/141132633-fd848845-f331-44ed-9a05-26d18d18aa8c.png)

2021-11-10 14:40 UTC, igor8518 commented
I say right away, this is not my salon. I just implemented it with a few changes.