add rnav template page
flybywiresim/a32nx pull request #6218
Opened 2021-11-21 18:11 UTC by samiFBG

Fixes #[issue_no]

## Summary of Changes

      I have add the template of rnav page in the new mcdu
## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2021-11-21 18:35 UTC, Lucky38i requested changes
Very nice template so far, just a few changes

2021-11-21 18:35 UTC, Lucky38i commented on src/instruments/src/MCDU/Pages/PagesContainer.tsx
> +import { addScratchpadMessage } from '../redux/actions/scratchpadActionCreators';
This is the incorrect way to be using redux hooks. this action creator by itself won't do anything you need to dispatch it. Also, this is the pages container but I wouldn't use it as a redux container, better you do that inside of `Radnav.tsx`

2021-11-21 18:35 UTC, Lucky38i commented on src/instruments/src/MCDU/Pages/FMGC/RadNav/Radnav.tsx
> +    const dispatch = useMCDUDispatch();
in reference to my other comment, you already have the dispatcher here so just do 
```js
import * as scratchpadActions from '../../../redux/actions/scratchpadActionCreators';
const addMessage = (msg: ScratchpadMessage) => {
        dispatch(scratchpadActions.addScratchpadMessage(msg));
};
```
See below for a usage example https://github.com/flybywiresim/a32nx/blob/1bdbc95860f8b482c0928e3e349256d74aa6ef84/src/instruments/src/MCDU/Pages/FMGC/Init/Init.tsx#L56-L58

2021-11-21 18:35 UTC, Lucky38i commented on src/instruments/src/MCDU/Pages/FMGC/RadNav/Radnav.tsx
> +                <Vortwo addMessage={addMessage} />
Consider merging `Vorone` and `vortwo` into one single react component? makes the code tidier and the uses for both cases are the same. The same for `crsone` and `crstwo`, `ls` and `lscrs`, as-well as `adfone` and `adftwo`.

Bear in mind a single component can return `RowHolder`s so with the case of merging `ls` and `lscrs` you can do
```js
return (
    <RowHolder columns={2}>
        <...the inners of ls component/>
     </RowHolder>
     <RowHolder columns={2}>
         <...the innerds of lscrs component />
     </RowHolder>
)
```

2021-11-25 13:33 UTC, samiFBG commented
> Fixes #[issue_no]
> ## Summary of Changes
> 
> ```
>   I have add the template of rnav page in the new mcdu
> ```
> 
> ## Screenshots (if necessary)
> 
> ![alt text](https://camo.githubusercontent.com/4119e6cded9e4fda286c6620f54e4e2a880580c97b1bdccc7c6a7f46059b70e1/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3834303631393235383337343235383730312f3931333432313434333836303133353939362f756e6b6e6f776e2e706e67)
> ## References
> 
> I have use Honeywell Pegasus Step 1A (Rev 0), 2009 edition manual. ![alt text](https://camo.githubusercontent.com/2c4a3d1d2d381aa6328a7ab5d94a98e0782cbb945be6c8d04256133eaf49f634/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3834303631393235383337343235383730312f3931333431393833333135393333313838302f756e6b6e6f776e2e706e67)
> ## How to download the PR for QA
> 
> Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.
> 
>     1. Make sure you are signed in to GitHub
> 
>     2. Click on the **Checks** tab on the PR
> 
>     3. On the left side, click on the bottom **PR** tab
> 
>     4. Click on the **A32NX** download link at the bottom of the page

2021-11-25 13:41 UTC, Lucky38i requested changes
Much better changes, just double check the rendering in-sim. looks like you might've forgot a LineHolder or RowHolder

2021-11-25 13:41 UTC, Lucky38i commented on src/instruments/src/MCDU/Pages/FMGC/RadNav/Radnav.tsx
> +        <LineHolder columnPosition={1}>
I think you forgot to add a RowHolder here

2021-11-30 10:16 UTC, Lucky38i requested changes
gotta remove the clearing of the scratchpad in the page, the components do this automatically.

As a page builder, you need to handle invalid values, setting values and when the user presses `CLR` on the scratchpad. Below is an example, 
https://github.com/flybywiresim/a32nx/blob/1bdbc95860f8b482c0928e3e349256d74aa6ef84/src/instruments/src/MCDU/Pages/FMGC/Init/InitA.tsx#L166-L184

2021-11-30 10:16 UTC, Lucky38i commented on src/instruments/src/MCDU/Pages/FMGC/RadNav/Radnav.tsx
> +            <Adf addMessage={addMessage} clearScratchpad={clearMessage} />
All interactive components automatically clear the scratchpad, you don't need to handle that. https://github.com/flybywiresim/a32nx/blob/1bdbc95860f8b482c0928e3e349256d74aa6ef84/src/instruments/src/MCDU/Components/Fields/Interactive/StringInputField.tsx#L55-L62

2022-01-25 13:27 UTC, St54Kevin commented
VHF and ADF empty fields should be one space wider. The devider is always at the same location as in the header

2022-02-04 11:14 UTC, davidwalschots commented
@samiFBG Do you intend to continue work on this PR in the near future?

2022-03-04 16:55 UTC, davidwalschots commented
I'm going to close this PR, because the author is not responding. Feel free to (re)open.

2022-03-04 16:55 UTC, closed without merging