refactor(ap): Move FD smoothing from C++ Interface to model
flybywiresim/a32nx pull request #6398
Opened 2021-12-21 20:07 UTC by lukecologne

## Summary of Changes

This PR moves the flight director smoothing from the FlyByWireInterface into the Matlab model.
Also, the smoothing behavior was slightly changed, which means that the lateral FD now uses a lag filter, while the vertical FD uses a rate limiter. This should make them behave closer to real life.

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub): 

## Testing instructions

Fly the aircraft, and observe the behavior of the two FD bars. Compare them to some real-life or level-D sim footage, to determine if they are realistic. Also Test the FD with the TRK/FPA mode enabled.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2021-12-22 09:49 UTC, aguther approved these changes
Code LGTM, will now to flight testing

2021-12-22 10:44 UTC, aguther requested changes
The smoothing of the vertical flight director bar must be improved. I suggest taking the previous implementation as orientation, it was accepted and we had no recent feedback it's unrealistic.

2021-12-22 10:50 UTC, aguther commented
Test Result: NOT PASSED

The behavior of the vertical FD bar is not ok, it's too abrupt now.

Implementation now:
https://user-images.githubusercontent.com/6629914/147079601-abe521ba-78dd-4b69-b913-6a0a1c40e09a.mp4

Implementation before:
https://user-images.githubusercontent.com/6629914/147081253-3fe6e4fc-4b57-4bd3-a1e5-239df4efe033.mp4

Real world references:
https://youtu.be/CsGEmDnMZH0?t=118
https://youtu.be/n3TJMro_NzA?t=288
https://youtu.be/5PfIW-Ar4Fo?t=96

2021-12-22 11:19 UTC, aguther commented
Comparison for engagement of SRS:

Current implementation:
https://user-images.githubusercontent.com/6629914/147084691-a906bde2-4313-4a6d-bcd1-0b3f62a8b0cd.mp4

Proposed implementation:
https://user-images.githubusercontent.com/6629914/147084706-333af2cc-7d74-4e5f-934c-076944820cfe.mp4

Real world-examples:
https://youtu.be/n3TJMro_NzA?t=218
https://youtu.be/CsGEmDnMZH0?t=22
https://www.youtube.com/watch?v=5PfIW-Ar4Fo&t=0s

2021-12-22 11:24 UTC, IbrahimK42 commented
> Comparison for engagement of SRS:
> 
> Current implementation: https://user-images.githubusercontent.com/6629914/147084706-333af2cc-7d74-4e5f-934c-076944820cfe.mp4
> 
> Proposed implementation: https://user-images.githubusercontent.com/6629914/147084691-a906bde2-4313-4a6d-bcd1-0b3f62a8b0cd.mp4
> 
> Real world-examples: https://youtu.be/n3TJMro_NzA?t=218 https://youtu.be/CsGEmDnMZH0?t=22 https://www.youtube.com/watch?v=5PfIW-Ar4Fo&t=0s

The proposed implementation seems still too slow. It should be about 2 seconds from 0 to 10°

2021-12-23 10:02 UTC, aguther approved these changes

2021-12-23 12:14 UTC, merged

2021-12-23 12:14 UTC, aguther commented
PR is passed from my side.