feat(atsu): Datalink status page and Max uplink delay page
flybywiresim/a32nx pull request #6596
Opened 2022-01-26 11:15 UTC by svengcz

Fixes #[issue_no]

## Summary of Changes
This PR adapts the datalink status page to the Hoppie integration and adapts it to MSN7560 layout.
The Max Uplink Delay page is also integrated.

## Screenshots (if necessary)

### Max uplink delay (logged in)
![grafik](https://user-images.githubusercontent.com/64070348/151153664-80f7f48b-34f6-4992-a098-2e1cb50c8cc8.png)

### Max uplink delay (logged off)
![grafik](https://user-images.githubusercontent.com/64070348/151153686-259589bb-767a-496c-aca4-40419822e251.png)

### Datalink status without Hoppie connection
![grafik](https://user-images.githubusercontent.com/64070348/151153629-34cd1235-c3a2-4ec6-9513-5dfb1a72a300.png)

### Datalink status with Hoppie connection
![grafik](https://user-images.githubusercontent.com/64070348/151153487-ce3d99a5-5d2a-415d-b1e7-52276ae2cb5f.png)

### Printed datalink page
![grafik](https://user-images.githubusercontent.com/64070348/151153546-b865627e-35fb-45bb-aab2-b24f64773c1b.png)

## References

A320 FCOM documentation for MSN7560

## Additional context

Discord username (if different from GitHub): sven

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2022-02-18 06:19 UTC, 2hwk requested changes

2022-02-18 06:19 UTC, 2hwk commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATSU_DatalinkStatus.js
> +        if (SimVar.GetSimVarValue('L:A32NX_HOPPIE_ACTIVE', 'number') === 1) {
```suggestion
        if (SimVar.GetSimVarValue("L:A32NX_HOPPIE_ACTIVE", "number") === 1) {
```

2022-02-18 06:19 UTC, 2hwk commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATSU_DatalinkStatus.js
> +        mcdu.activeSystem = 'ATSU';
```suggestion
        mcdu.activeSystem = "ATSU";
```

2022-02-18 06:19 UTC, 2hwk commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATSU_Menu.js
>          mcdu.activeSystem = 'ATSU';
```suggestion
        mcdu.activeSystem = "ATSU";
```

2022-02-18 06:19 UTC, 2hwk commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_ConnectionStatus.js
>          if (mcdu.atsuManager.atc.nextStation() !== '') {
```suggestion
        if (mcdu.atsuManager.atc.nextStation() !== "") {
```

2022-02-18 06:19 UTC, 2hwk commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_ConnectionStatus.js
>          if (mcdu.atsuManager.atc.currentStation() !== '') {
```suggestion
        if (mcdu.atsuManager.atc.currentStation() !== "") {
```

2022-02-18 06:19 UTC, 2hwk commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/ATSU/A320_Neo_CDU_ATC_ConnectionStatus.js
>          if (mcdu.atsuManager.atc.currentStation() !== '') {
Our style guide/convention is to use double quotes in js. 

(In typescript we have changed to use single quotes, and there are still portions where this is missed sometimes).

2022-02-18 08:06 UTC, svengcz commented on .github/CHANGELOG.md
> -1. [EFB] Added Hoppie configuration to ATSU/ATC page - @svengcz (Sven Czarnian)
That was discussed in the discord. I created (5?) entries with my first PR. We agreed to clean it up.

2022-02-19 01:25 UTC, 2hwk approved these changes

2022-02-19 18:16 UTC, mico975 commented
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #6596 
Tier of Testing  : 1
Date             : 19/02/2022

Testing Process: 
tests of non-editable
keep INIT-page empty
AOC/DEPART REQ should show ------ for the callsign and from/to - OK
Atc/Connection status should show ---- for current and next ATC - OK
Atc/Notification should show ---- for the callsign - OK

fill out INIT-page
AOC/DEPART REQ should be filled for callsign and from/to - OK
Atc/Connection should be the same as above - OK
Atc/Notification should show the callsign - OK

tests of datalink status
open the Datalink Status page 
VHF3 is supposed to show AOC Only - OK

activate Hoppie connection via EFB
Datalink Status should show without a page reload that AOC/ATC is shown below VHF3 - OK
deactivation of Hoppie returns to AOC Only - OK

All other com channels are not installed - OK

test print function of datalink status - OK

Connection Status page
check if a handover from one station to an other shows the following information
ACTIVE ATC: station that sent the handover - OK
NEXT ATC: the following station - OK
After an accepted logon of the next station:
ACTIVE ATC: old NEXT ATC - OK
NEXT ATC: empty - OK

MAX UPLINK DELAY in CONNECTION
Not logged on: show ---- for ACTIVE ATC - OK
Logged on: show station in green letters - OK
After a logon or handoff is MAX UPLINK DELAY NONE - OK
can be set via [1] (is reset after a station change) - OK
not editable max uplink delay if no station is active - OK

Negatives:
N/A

Testing Results: 
Passed

Conclusions: 
Nice work 🚀

2022-02-19 21:57 UTC, merged