feat: better wing lights
flybywiresim/a32nx pull request #6693
Opened 2022-02-11 01:50 UTC by DarlanFernandes

## Summary of Changes
 This PR changes the wing lights to better match the A320neo.

##Screenshots
 Before: 

![Microsoft Flight Simulator Screenshot 2021 12 30 - 19 40 07 23](https://user-images.githubusercontent.com/24297116/153525644-049cda38-0bca-42c2-999f-46c8c63f305e.png)

![Microsoft Flight Simulator Screenshot 2022 01 09 - 19 03 45 72](https://user-images.githubusercontent.com/24297116/153525674-2b87567b-1574-42d4-b1f7-18bde9f7ec6c.png)

 After: 

![Microsoft Flight Simulator Screenshot 2022 02 09 - 20 32 02 45](https://user-images.githubusercontent.com/24297116/153525686-9f10e71e-de40-45c6-976d-cab197b55b8b.png)

![Wing](https://user-images.githubusercontent.com/24297116/153525737-39ddfe84-03d8-4afa-8d6d-6eaf86f75854.jpeg)

## References
 - Referencing the pictures at:
 - 
https://www.youtube.com/watch?v=RlRSEuGhVH8

https://www.youtube.com/watch?v=7k3YiOQnovM&t=74s

https://twitter.com/aviacaodobrasil/status/1475917313744461826?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1475917313744461826%7Ctwgr%5E%7Ctwcon%5Es1_&ref_url=https%3A%2F%2Faeroin.net%2Festreiam-em-uberaba-mg-as-operacoes-com-jatos-comerciais-pela-azul%2F
 
https://aeroin.net/wp-content/uploads/2021/06/A320neo_Cold_weather_1-1024x713.jpg

![image](https://user-images.githubusercontent.com/24297116/153525835-1a6bc743-994b-4c83-ae48-b403ebfed91e.png)

2022-02-11 07:50 UTC, ErickSharp commented
Can you show before/after screenshots in similar camera angles and ambient lighting? It is hard to gauge the differences you made when the photos are so different in composition.

2022-02-11 16:42 UTC, DarlanFernandes commented
> Can you show before/after screenshots in similar camera angles and ambient lighting? It is hard to gauge the differences you made when the photos are so different in composition.

ok, i will send.

2022-02-11 17:23 UTC, DarlanFernandes commented
New screenshots on the same view with before and after changes

1 Before = 
![Microsoft Flight Simulator Screenshot 2022 02 11 - 14 11 53 37](https://user-images.githubusercontent.com/24297116/153638479-0485137e-9a7e-4913-bcd8-59041d9acf66.png)

1 After =
![Microsoft Flight Simulator Screenshot 2022 02 11 - 14 10 27 95](https://user-images.githubusercontent.com/24297116/153638559-1fb4180a-ed03-4b86-a09f-7707dd16f540.png)
 
_____________________________

2 Before =
![Microsoft Flight Simulator Screenshot 2022 02 11 - 14 12 37 09](https://user-images.githubusercontent.com/24297116/153638640-2655a126-d58c-485e-9f92-3fadd23c8316.png)

2 After =

![Microsoft Flight Simulator Screenshot 2022 02 11 - 14 19 11 34](https://user-images.githubusercontent.com/24297116/153638675-0643b74a-6684-4b3d-944e-39b67e052565.png)

After changes, the lights illuminate the engines, leading edge of the wing and the sharklet, as in the real aircraft.

2022-02-11 21:03 UTC, lolisec commented
Great Job so far on this wip.

2022-02-15 14:14 UTC, aguther submitted a review, later dismissed

2022-02-16 07:01 UTC, bouveng commented
Hi, two issues.

This PR removes the volumetric lights for the wing lt. If that is intended, there is no use for 2 .fx files.

The range and intensity feels overdone.

Don't be afraid to introduce more ligjt soirces to sculpt the lights just right.

2022-02-16 07:20 UTC, bouveng requested changes

2022-02-16 07:20 UTC, bouveng commented on flybywire-aircraft-a320-neo/effects/LIGHT_A32NX_WingLarge.fx
> +X Rotation=20.00, 20.00
Just a note. This rotation applies to both wing lights as they use the same .fx file. It is fine in most cases, but I would prefer to have this information in the `systems.cfg` instead so the light knows nothing about its orientation.

2022-02-16 07:20 UTC, bouveng commented on flybywire-aircraft-a320-neo/effects/LIGHT_A32NX_WingLarge.fx
> +Intensity=100
Why is the "physical" size of the "bulb" increased x 8, the range by x 5 and the intensity with x 2 (actually x 4 in total when combined/calculated with the volumetric light).

Perhaps the light for the leading edge should be better focused and repositioned. (These light does not need to originate from the modeled light on fuselage, feel free to reposition/add more)

2022-02-16 07:20 UTC, bouveng commented on flybywire-aircraft-a320-neo/effects/LIGHT_A32NX_WingLargeVol.fx
> +Intensity=100
Same as previous comment above.

2022-02-16 07:20 UTC, bouveng commented on flybywire-aircraft-a320-neo/effects/LIGHT_A32NX_WingLargeVol.fx
> +Volumetric=0
Why are we removing the volumetric effect on these lights? If that is inteded, all the properties of this light could be moved into the regular light. Se previous comment about positioning/adding more lights for sculpting this effect.

2022-02-16 15:29 UTC, bouveng commented
@DarlanFernandes I can assist you with task if you want help or ideas. =)

2022-02-19 20:22 UTC, AdamNZ commented
Sorry to hi-jack this thread - but I couldn't find an open one - and it's kind of related ...

My **NAV** (wingtip) lights are so faint they're nigh-on invisiible. Is there an open issue for this - or should I start one. Apologies (and please remove) if this comment is in the wrong place!

2022-02-20 01:11 UTC, bouveng commented
> Sorry to hi-jack this thread - but I couldn't find an open one - and it's kind of related ...
> 
> My **NAV** (wingtip) lights are so faint they're nigh-on invisiible. Is there an open issue for this - or should I start a new one? Apologies (and please remove) if this comment is in the wrong place!

@AdamNZ Please open a new ticket for that. Providing screenshots perhaps. NAV LT have never been stronger as they are now, so I don't really understand.

Br.

/J

2022-02-20 02:26 UTC, AdamNZ commented
OK - will do (thanks) ... and if anyone has the right permissions, please remove these out of context comments of mine ;-)

2022-03-13 13:25 UTC, beheh commented
@DarlanFernandes Any objection if I move this PR back to a draft until you can make the changes that have been suggested?

2022-03-18 16:26 UTC, beheh commented
I have moved this PR back to draft so the suggestions from bouveng can be addressed.

2022-04-21 17:10 UTC, aguther commented
I'm closing the PR for now due to inactivity. It can be reopened at any time if you want to continue the work on it.

2022-04-21 17:10 UTC, closed without merging