feat(clk): Added simvars for Clock CHR and ET
flybywiresim/a32nx pull request #6790
Opened 2022-02-23 06:49 UTC by ssewell

Fixes #6049

## Summary of Changes
Adds simvars for the CHR and ET displays in the Clock module, using a value of -1 when no content is displayed.
 * A32NX_CHRONO_ELAPSED_TIME
 * A32NX_CHRONO_ET_ELAPSED_TIME

Naming was chosen with consistency in mind based on the existing simvars and events in Chrono.tsx and ElapsedTime.tsx.

## Screenshots (if necessary)
No visual changes as only new simvars were added.

## References
N/A

## Additional context
Changes were made to include simvars along with the existing functionality without changing the existing state implementation. Using the simvars exclusively in lieu of the React State hooks was considered but introduced visual judder between two consecutive values at times. 

Discord username (if different from GitHub): AntennaRex#9906

## Testing instructions

1. Ensure the existing CHR and ET features on the Clock continue to behave normally.
2. Enable MSFS 2020 DevMode to inspect the two new simvars (A32NX_CHRONO_ELAPSED_TIME and A32NX_CHRONO_ET_ELAPSED_TIME) to see the seconds elapsed for the Clock's CHR and ET displays, respectively. Each simvar should be set to -1 when the corresponding display on the Clock is blank.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2022-02-23 06:52 UTC, Benjozork commented on docs/a320-simvars.md
> +      -1 | Empty value
```suggestion
      -1 | Empty value

```

2022-02-23 06:52 UTC, Benjozork requested changes

2022-02-23 06:52 UTC, Benjozork commented on src/instruments/src/Clock/Components/Chrono.tsx
> +    const [elapsedSimvarTime, setElapsedSimvarTime] = useSimVar('L:A32NX_CHRONO_ELAPSED_TIME', 'number');
Does not seem like we use the value itself

```suggestion
    const [, setElapsedSimvarTime] = useSimVar('L:A32NX_CHRONO_ELAPSED_TIME', 'number');
```

2022-02-23 06:52 UTC, Benjozork commented on src/instruments/src/Clock/Components/ElapsedTime.tsx
> +    const [elapsedSimvarTime, setElapsedSimvarTime] = useSimVar('L:A32NX_CHRONO_ET_ELAPSED_TIME', 'number');
Ditto

```suggestion
    const [, setElapsedSimvarTime] = useSimVar('L:A32NX_CHRONO_ET_ELAPSED_TIME', 'number');
```

2022-02-23 07:11 UTC, Benjozork approved these changes

2022-02-23 09:59 UTC, mico975 commented
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #6790
Tier of Testing  : 1
Date             : 23/02/2022

Testing Process: 
Ensure the existing CHR and ET features on the Clock continue to behave normally. - OK
Enable MSFS 2020 DevMode to inspect the two new simvars (A32NX_CHRONO_ELAPSED_TIME and A32NX_CHRONO_ET_ELAPSED_TIME) to see the seconds elapsed for the Clock's CHR and ET displays, respectively. Each simvar should be set to -1 when the corresponding display on the Clock is blank. - OK

Negatives:       
On initial load the CHR and ET vars are set to 0 (displays are blank, so it's still ok), after reset they are set to -1.

Testing Results: 
Passed

Conclusions: 
Works

2022-02-23 12:19 UTC, frankkopp commented
@ssewell please make sure to open an issue on the docs repo to update the API documentation 
Best to link to to your PR for details. 
Thanks

2022-02-23 15:58 UTC, ssewell commented
@frankkopp Done!

2022-02-23 18:35 UTC, ssewell commented
> Negatives:
> On initial load the CHR and ET vars are set to 0 (displays are blank, so it's still ok), after reset they are set to -1.

@mico975 Good catch on this! I should initialize these to -1 before they're used.

2022-03-01 01:59 UTC, owen2007 commented
Quality Assurance Trainee Report

Discord          : (owen_#4883)
Object of testing: (#PR 6790)
Tier of Testing  : (1)
Date             : (1/03/2022)

Testing Process: 
(Detail is needed)

Negatives:       
There where no negatives that i found when conducting the test.

Testing Results: 
The test passed 

Conclusions: 
In concluion the simvars both simvars where set to -1

2022-03-08 12:50 UTC, merged