fix(hyd): Higher reservoir init pressures
flybywiresim/a32nx pull request #6878
Opened 2022-03-10 09:22 UTC by crocket63

Fixes #[issue_no]

## Summary of Changes

As plane starts with brake accumulator not fully loaded, yellow air pressure is expected to be higher as fluid is above max.

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2022-03-10 10:36 UTC, beheh approved these changes

2022-03-10 10:37 UTC, beheh requested changes
Actually, looks like another test failed - please check `hydraulic_reservoirs_maintain_pressure_after_bleed_pressure_loss`

2022-03-10 14:41 UTC, crocket63 commented
> Actually, looks like another test failed - please check `hydraulic_reservoirs_maintain_pressure_after_bleed_pressure_loss`

Yeah it will randomly pass or fail due to current bleed issue sadly. This will be solved by #6810.

2022-03-11 17:53 UTC, bouveng approved these changes

2022-03-11 22:13 UTC, crocket63 commented
Can be QA tested now!
Better to merge after #6810 to avoid random test fail.

2022-03-13 13:31 UTC, beheh approved these changes

2022-04-08 09:43 UTC, merged