feat(bleed): Attach hydraulic reservoirs to both engine bleeds
flybywiresim/a32nx pull request #6891
Opened 2022-03-11 16:46 UTC by Gurgel100

Fixes #[issue_no]

## Summary of Changes

This PR attaches the hydraulic reservoirs to both engine bleed systems as it is in the real aircraft.

## Screenshots (if necessary)

## References

Source: @crocket63
![reservoir_bleed](https://user-images.githubusercontent.com/7543925/157909905-564bc039-f91d-4863-9cdb-888ba397510d.png)

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Check the symvars named: `HYD_(GREEN/BLUE/YELLOW)_RESERVOIR_AIR_PRESSURE`.
Drain the reservoir air pressure by enabling the air leak on the corresponding reservoir. Then check if the pressure builds up with:
1. Only left bleed source
2. Only right bleed source
3. Both bleed sources

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2022-03-11 19:39 UTC, crocket63 reviewed
Not a bleed expert but looks like it will do what we need :)

2022-03-11 19:39 UTC, crocket63 commented on src/systems/a320_systems/src/pneumatic.rs
> +    hydraulic_reservoir_bleed_air_valves: [PurelyPneumaticValve; 2],
Those will act as check valves right? Only allowing flow if more pressure upstream?

2022-03-11 19:47 UTC, Gurgel100 commented on src/systems/a320_systems/src/pneumatic.rs
> +    hydraulic_reservoir_bleed_air_valves: [PurelyPneumaticValve; 2],
Correct.

2022-03-11 22:12 UTC, crocket63 approved these changes

2022-03-11 22:28 UTC, davidwalschots reviewed
I'm missing automated tests on this.

2022-03-11 22:32 UTC, Gurgel100 commented
> I'm missing automated tests on this.

You're absolutely right. I forgot about them. Will add some.

2022-03-11 22:38 UTC, BlueberryKing approved these changes
LGTM! Fixing this has been on my list for some time now, so I'm glad you've gotten around to it already 😄

2022-03-12 05:00 UTC, ShadowFrost3 commented
Quality Assurance Tester Report


Object of testing: #6891
Tier of Testing:1
Date: 11/03/2022

Testing Process: Startup
HYD Air leaks - normal
test left/right/both bleed pressurize the system - checked 


Right Bleed system does not pressurize the HYD systems on the ground. - failed
On the ground at 50% power HYD systems (all three leaks on) stabilize at ~14 with no bleeds
With left system on they pressurize to approximately ~15
With right system on they do not change - failure point 
With both on they pressurize to approximately 15 - possibly failure as well. Total pressure should plausibly increase 

Negatives: Plausible right system bleed failure 
Testing Results: Not Passed

Media:
![image](https://user-images.githubusercontent.com/87394534/158004473-ee83f8cb-7749-4b7b-9872-a7907dbb6481.png)
![image](https://user-images.githubusercontent.com/87394534/158004482-63e6b2ab-8520-42db-b439-75a5d5ee07bb.png)
![image](https://user-images.githubusercontent.com/87394534/158004487-4da349e7-bf46-4139-a2e1-1a8c5f8bbd94.png)

2022-03-14 12:46 UTC, mico975 commented
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #6891
Tier of Testing  : 1
Date             : 14/03/2022

Testing Process: 
Drain the reservoir air pressure by enabling the air leak on the corresponding reservoir. Then check if the pressure builds up with:

Only left bleed source - **OK**
Only right bleed source - **OK**
Both bleed sources - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

2022-03-14 17:31 UTC, ShadowFrost3 commented
Quality Assurance Trainee Report


Object of testing: #6891 
Tier of Testing:1
Date: 14/03/2022

Testing Process: Bleeds power HYD system - checked thoroughly trust me 
So thoroughly it was at Grugel100's expense 

Negatives: Need to fix a QA tester flaw... 

Testing Results: Passed

Conclusions:
LGTM

2022-03-14 19:47 UTC, davidwalschots requested changes
Waiting for tests to be added before this can be merged.

2022-03-14 22:19 UTC, Gurgel100 commented
> Waiting for tests to be added before this can be merged.

Added some tests.

2022-03-15 18:35 UTC, merged