(feat)a32nx: Add Local-api integration
flybywiresim/a32nx pull request #6993
Opened 2022-04-01 21:54 UTC by Lucky38i

## Summary of Changes

This PR aims to integrate the fetch and packaging of the local-api into the a32nx addon.
* hash checks against new versions of the local-api
* Removal of the mcdu-server 

## Additional context

Discord username (if different from GitHub): Lcuky38i

## Testing instructions

**NOTE: steps 1-5 won't be needed when using the installer**
1. open `local-server.exe`
2.  The console will print a list of printers
![img](https://i.imgur.com/iGPJzcV.png)
4. copy the name of the printer (for example: `HP ENVY 5000 series [03F136]`) that you use and set that in the properties file found `resources/properties.json` and enable the printer
![img](https://i.imgur.com/PRhRniG.png)
6. restart the server
7. navigate to `localhost:3838/interfaces/mcdu`(or whichever port the server console says) and observe mcdu web client
8. Ensure the mcdu web client performs as it did previously

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2022-04-12 08:03 UTC, 2hwk approved these changes

2022-04-12 08:04 UTC, 2hwk commented
Please solve conflicts

2022-07-27 16:03 UTC, 2hwk requested changes

2022-07-27 16:03 UTC, 2hwk commented on src/instruments/src/EFB/Localization/en.json
> +      "EnabledSimbridgeConnectionAutoDeactivatesAfter5MinutesIfNoSuccessfulConnection": "Enable Simbridge Connection (Auto deactivates after 5 minutes if no successful connection)",
For these localisation strings, you may have to coordinate with the localisation team to have these fixed, or just revert to using the older keys, which may be easier given that localazy is not exactly great at handling changing keys

2022-07-27 16:31 UTC, 2hwk approved these changes

2022-08-02 06:43 UTC, frankkopp requested changes

2022-08-02 06:43 UTC, frankkopp commented on src/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
> +                    <SettingItem name={t('Settings.SimOptions.EnableSimbridge')}>
```suggestion
                    <SettingItem name={t('Settings.SimOptions.EnableSimBridge')}>
```

2022-08-02 06:43 UTC, frankkopp commented on src/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
> +                    <SettingItem name={t('Settings.SimOptions.SimbridgePort')}>
```suggestion
                    <SettingItem name={t('Settings.SimOptions.SimBridgePort')}>
```

2022-08-09 06:19 UTC, 2hwk requested changes

2022-08-09 06:19 UTC, 2hwk commented on src/instruments/src/EFB/Settings/Pages/SimOptionsPage.tsx
> +                    <SettingItem name={t('Settings.SimOptions.EnableSimbridge')}>
<SettingItem name={t('Settings.SimOptions.EnableSimbridge')}>
```suggestion
                    <SettingItem name={t('Settings.SimOptions.EnableSimBridge')}>
```

2022-08-09 06:29 UTC, 2hwk approved these changes

2022-08-28 20:36 UTC, BlueberryKing commented on .github/CHANGELOG.md
> +1. [ADDON] Simbridge Integration - @lucky38i (Alex)
Can you put this under 0.9.0?

2022-08-30 07:10 UTC, 2hwk commented
QA Report

Discord: 2Cas#1022
Object of testing: #6993
Tier of Testing: 1
Date: 30/08/2022

Testing Process: 
- [x] Start SimBridge
- [x] navigate to localhost:3838/interfaces/mcdu(or whichever port the server console says)
- [x]  observe mcdu web client Ensure the mcdu web client performs as it did previously
- [x] Disconnected from then reconnected SimBridge, still functional. 

Negatives: N/A

Testing Results: Passed

Conclusions: LGTM

2022-08-30 10:15 UTC, merged