feat: vertical navigation v1
flybywiresim/a32nx pull request #7080
Opened 2022-04-18 06:51 UTC by aguther

## Summary of Changes
This PR introduces the first step of the implementation of the vertical navigation capabilities of the Airbus A320.

⚠️ For the moment this PR is primarily to have regular builds with linting, that is the reason it is marked for ready for review. You are free to review code but be aware that it's under development and code parts can be reworked/refactored at any time.

## Testing instructions
< not defined yet >

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2023-04-12 21:30 UTC, frenchairbuspilot commented
Discord          : jp320#3336
Object of testing: #7080
Tier of Testing  : 1?
Date             : 12/04/2023 

Testing Process: 
Flight from LFLL to LFML by simbrief ( complex vnav arrival with constraints.)
Loaded directly on the runway 35 and auto filled by simbrief, manual wind uplink import.

The following features are implemented:

Accurate speed, altitude, time and fuel predictions in the MCDU for all phases of flight. 
       -> Correct , only NEXT PAGE on F-PLN page is not implemented yet apparently? 

Vertical predictions on the navigation display in the form of pseudowaypoints.
      -> Correct no remarks.

Ability to program cruise steps in the MCDU.
      -> On the ground I couldn't access the Step climb page via vertical revision. should work that's how I do it irl. Could access 
           once airborn though.

Vertical guidance in managed modes during all phases of flight
      -> Correct and rather accurate! good job, even V/S path prediction ( blue arrow) is shown 

Pause-at-T/D quality of life feature.
      -> First try for me and works nicely with the window popping up with the time of pause. flight resumed perfectly.


**Negatives:**
Couldn't access step climb on the ground, will retry next week. 

Typing a step climb: ALT/WPT , typing the value should work by itself no need to write down FL first, 
Example: 210/MTL should be taken as FL210/MTL, doesn't work atm. (see pictures.)

On Prog page, if you type 1 on scratchpad and insert on CRZ FL ( LSK1L) it should automaticaly populate the FCU ALT value as CRZ FL. ( i don't have a reference for this i could record it in the real plane tomorrow, I flew CEO atm but i assume the same function would be present in the NEO)

**Testing Results:** 
Passed

**Conclusions:** 
Nice work guys, plane flies well in managed, can't wait to see the rest! 
A few corrections for the step climb on the ground ( if i'm not alone beeing unable to reach the STEP CLB page)

Media:
![Microsoft Flight Simulator Screenshot 2023 04 12 - 22 52 54 86](https://user-images.githubusercontent.com/130319464/231589440-3c1a724a-0f14-4ac2-b571-38b6e029f3a1.png)
![Microsoft Flight Simulator Screenshot 2023 04 12 - 22 52 58 28](https://user-images.githubusercontent.com/130319464/231589451-1931b681-48c9-4153-998f-8f447d252bb7.png)
![Microsoft Flight Simulator Screenshot 2023 04 12 - 22 55 49 97](https://user-images.githubusercontent.com/130319464/231589456-939b7991-e92a-4dd8-ae76-d76f29e42a6b.png)

2023-04-13 02:10 UTC, Benjozork requested changes

2023-04-13 17:51 UTC, BlueberryKing commented on fbw-a32nx/src/systems/fmgc/src/guidance/PseudoWaypoint.ts
> +    distanceFromStart: NauticalMiles,
This is used when the PWP is placed along the track line instead of the flight plan (i.e HDG/TRK) mode.

2023-04-13 18:04 UTC, BlueberryKing commented on fbw-a32nx/src/systems/fmgc/src/guidance/vnav/climb/ClimbPathBuilder.ts
> +     * Compute climb profile assuming climb thrust until top of climb. This does not care if we're below acceleration/thrust reduction altitude.
Good point. It's meant to be this way. The comment was meant to remind me that I may want to use the TakeoffPathBuilder instead.

2023-04-13 18:22 UTC, BlueberryKing commented on fbw-a32nx/src/systems/fmgc/src/guidance/vnav/wind/WindObserver.ts
> +        return new WindVector(windDirection.value, windSpeed.value);
Yeah, I agree. Most of the time I'm only looking for the headwind component anyways.

2023-04-13 21:08 UTC, BlueberryKing commented on fbw-a32nx/src/systems/instruments/src/PFD/shared/PFDSimvarPublisher.tsx
> +    tdReached: boolean;
Good idea. These will eventually also be replaced by the proper ARINC values on the FMGC bus.

2023-04-14 19:14 UTC, BlueberryKing commented on fbw-a32nx/src/systems/fmgc/src/guidance/lnav/PseudoWaypoints.ts
> +        const waypointsLeftToDraw = new Set([...CHECKPOINTS_TO_PUT_IN_MCDU, ...CHECKPOINTS_TO_DRAW_ON_ND]);
I'm not sure what you mean. We remove elements of this set during the iteration below. Do you mean that we can get rid of the merging with `[...a, ...b]`?

2023-04-14 19:20 UTC, BlueberryKing commented on fbw-a32nx/src/systems/instruments/src/EFB/Settings/Pages/RealismPage.tsx
> +    const [pauseAtTod, setPauseAtTod] = usePersistentProperty('PAUSE_AT_TOD', 'DISABLED');
Do you mean the property names? If so, yeah, I agree. However, I think that's better suited in a separate PR.

2023-04-14 19:37 UTC, BlueberryKing commented on fbw-a32nx/src/systems/fmgc/src/components/fms-messages/StepDeleted.ts
> +        const newState = SimVar.GetSimVarValue('L:A32NX_FM_VNAV_TRIGGER_STEP_DELETED', 'Bool') === 1;
Yeah, I just saw that we can access the FMGC through the `baseInstrument` passed to the `init` function. Maybe we should use this for all the messages.

2023-04-14 20:34 UTC, BlueberryKing commented on fbw-a32nx/src/systems/instruments/src/ND/elements/TrackLine.tsx
> +                const dy = (symbol.distanceFromAirplane - groundSpeed * (Date.now() - lastUpdateTime) / 1000 / 60 / 60) * mapParams.nmToPx;
I don't know how it works IRL sadly. The issue I'm solving here is that PWP are only recomputed every 5s, but in this time the plane moves closer to the PWP, so it needs to move as well.

2023-04-16 16:26 UTC, Benjozork approved these changes
LGTM

2023-04-27 11:29 UTC, mico975 commented
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #7080
Tier of Testing  : 2
Date             : 27/04/2023

Testing Process: 
The test procedure should go through a full cold & dark startup and go through the flows included in a normal flight. A full flight would be ideal, but checking a few entries in the MCDU is also fine. This could include:

Inserting a route and performance figures so predictions are computed.
Inserting/modifying constraints - **OK**
Inserting/modifying step altitudes - **OK**
Inserting/modifying speed limit - **OK**
Inserting/modifying winds - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

Media:
![image](https://user-images.githubusercontent.com/78908672/234848283-8d88d39f-1aa3-49d7-9760-95ac81a158a8.png)

2023-05-09 18:36 UTC, brewers10 commented
Quality Assurance Tester Report

Discord: brewers_10#5706
Object of testing: #7080 
Tier of Testing: 1
Date: 09/05/2023

Testing Process: 

Loaded from cold and dark at EGGP. Usual startup flows follows and departed towards EGLL. All of the following were testing below:

Inserting a route and performance figures so predictions are computed. - **OK**
Inserting/modifying constraints - **OK**
Inserting/modifying step altitudes - **OK**
Inserting/modifying speed limit - **OK**
Inserting/modifying winds - **OK**

Testing Results: 
Passed

Conclusions: 
LGTM. Fantastic effort from everyone involved. It's a real treat to fly

2023-05-10 20:42 UTC, merged