feat: add true heading and track
flybywiresim/a32nx pull request #7084
Opened 2022-04-18 21:01 UTC by ErickSharp

This PR adds true heading and true track into the current adirs data.

## Summary of Changes

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2022-04-18 21:36 UTC, tracernz requested changes

2022-04-18 21:36 UTC, tracernz commented on src/systems/systems/src/navigation/adirs.rs
> +            .set_value(simulator_data.true_heading, ssm);
The heading should become available prior to full allignment, whereas the ssm you're using here does not.

2022-04-18 21:36 UTC, tracernz commented on src/systems/systems/src/navigation/adirs.rs
> +            ssm,
This should use the ssm of true heading as well below 50 knots.

2022-04-23 15:15 UTC, davidwalschots approved these changes
🚀 Let's get this in!

2022-04-24 00:05 UTC, tracernz approved these changes
🚀

2022-04-24 09:16 UTC, beheh approved these changes
Looks good! It would be nice at some point to properly implement the refresh interval, but applies to all ADIRS values.

2022-04-25 08:39 UTC, aguther commented
Tested in sim and still working:
![image](https://user-images.githubusercontent.com/6629914/165052500-9904cb5c-16f9-4efb-b514-6684d562177a.png)

Looking at the code changes, there are no users of the new variables. This is to be expected.

2022-04-25 08:39 UTC, merged