fix(notif): passthrough pause events
flybywiresim/a32nx pull request #7253
Opened 2022-05-29 15:05 UTC by 2hwk

Fixes #[issue_no]

## Summary of Changes

Pause events were being captured and not passed through to Simconnect, resulting in problems with 3rd party external addons. This PR fixes this to allow these events to passthrough. No visible change for users.

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Spawn in any state
2. Use flight assistant menu to enable AUTO TRIM/RUDDER/etc
3. This should spawn the incompatible options alert notification 

![image](https://user-images.githubusercontent.com/15316958/170876327-5fd0da27-8dae-4bf1-a39b-f0ecffc7398e.png)

5. Press ESC to PAUSE and exit to the menu
6. Notification should now dismiss itself and disappear.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2022-05-29 15:15 UTC, Benjozork approved these changes

2022-05-29 23:06 UTC, tracernz commented on src/shared/src/notification.ts
> +        this.manager.interceptKey('PAUSE_SET', false);
```suggestion
        this.manager.interceptKey('PAUSE_TOGGLE', true);
        this.manager.interceptKey('PAUSE_ON', true);
        this.manager.interceptKey('PAUSE_OFF', true);
        this.manager.interceptKey('PAUSE_SET', true);
```
Second param means pass through to sim.

2022-05-29 23:06 UTC, tracernz requested changes
.

2022-05-31 15:34 UTC, merged

2022-05-31 15:47 UTC, alexr4339 commented
Quality Assurance Tester Report

Discord          : Alex R#6663
Object of testing: #PR 7253
Tier of Testing  : 1
Date             : 31.05.2022

Testing Process: 
Spawned in the air, enabled auto trim and received the error message. Pressed escape to pause and went back to the flight. The error message disappeared

Negatives:       
N/A

Testing Results: 
Passed