refactor(mcdu): Improved departure/arrival pages
flybywiresim/a32nx pull request #7259
Opened 2022-05-30 19:33 UTC by 2hwk

Fixes #[issue_no]

Fixed an issue with being unable to select certain enroute transitions

## Summary of Changes

* Minor overhaul of arrivals/departures page for proper pagination for all fields
* Improved cosmetic appearance to be closer to true-to-life
* Modified routing to be closer to true-to-life behaviour

## Screenshots (if necessary)

## References

https://www.youtube.com/watch?v=twwUjHXdNVU

## Additional context

Discord username (if different from GitHub):

## Testing instructions

1. Spawn and enter the following route in (via sim-brief or manual entry)
KLAS/26R RADYR2 BLAQQ DCT SHTNR ANJLL4 KLAX/24R

KFLL/28R ZAPPA4 PERMT AR16 ILM KBDL/

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are sig1ned in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2022-06-02 18:45 UTC, svengcz requested changes

2022-06-04 04:28 UTC, 2hwk commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_AvailableArrivalsPage.js
> +        const arrPage = 3;
agreed, see latest changes.

2022-06-05 12:59 UTC, svengcz approved these changes
LGTM

2022-06-06 13:26 UTC, marcman86 commented
Quality Assurance Report

Discord: marcman86#4907
Object of testing: #7259
Tier of Testing: 1
Date: 6/06/2022

Testing Process:
- Spawned C&D at KLAS
- Turned on bat. and ext. power
- Enter From/To
- Enter route > SHTNR double,  REGAE2 not in alphabetic order> not OK (image1)
- Spawned C&D at KFLL
- Turned on bat. and ext. power
- Enter From/To
- Enter route > route not correct on ND > not OK (image2)
- Spawned C&D at ESGG
- Turned on bat. and ext. power
- Enter From/To
- Enter route > OGDAV3T not in STAR list > not OK (image3)
- Try to break MCDU departure/arrival pages
- Selecting, removing, then selecting a departure/arrival

Negatives: Some things. But i don't know if this is to the PR.

Testing Results: -
Conclusions: -

Hope this helps :-)

Media:

![37](https://user-images.githubusercontent.com/78707844/172169079-bc5c7190-3484-422f-9e8a-6fc422d66efe.png)
image1

![38](https://user-images.githubusercontent.com/78707844/172169116-33110edd-f351-4f25-a821-3f6f553e6263.png)
image2

![39](https://user-images.githubusercontent.com/78707844/172169165-b7cf3c0f-083c-4d80-a64f-9d0fa85235d4.png)
image3

2022-06-06 16:22 UTC, merged