feat(mcdu): page formatter
flybywiresim/a32nx pull request #7294
Opened 2022-06-11 11:04 UTC by derl30n

## Summary of Changes

This pr aims to ease page formatting by anchoring "data" to a specific location.
Usage can be on a single mcdu line or the entire page. No integration for existing pages required.

## Screenshots (if necessary)

### Example of MCDU Menu Page included in this pr
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1857322/173185105-21680708-31aa-4dfa-8625-0d77e715cf6e.png) | ![image](https://user-images.githubusercontent.com/1857322/173185108-6cf6e0d5-6b61-4008-ba27-97e0f47b5568.png) |

### Example of MCDU Departures Page not included in this pr
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/1857322/173185185-040f7870-0d22-4e73-8c15-2c9c708241dc.png) | ![image](https://user-images.githubusercontent.com/1857322/173185168-2931b4df-a329-4be7-8918-af34386ed80e.png) |

## Additional context

This pr aims to provide a bridge until the overhauled page system is in place.

Discord username (if different from GitHub): DerL30N#3751

## Testing instructions

Observe mcdu page looks the same as described in the picture.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2022-06-15 14:05 UTC, 2hwk approved these changes

2022-06-16 04:40 UTC, ErickSharp requested changes

2022-06-16 04:40 UTC, ErickSharp commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_Format.js
> +    constructor(index, text, ...att) {
```suggestion
/** Used to displayed data on a mcdu page when using the formatting helper */
class Column {
    /**
     * @param {number} index - valid range from 0 to 23
     * @param {string} text - text to be displayed
     * @param {...({ color: string } | { size: string } | { align: bool })} att - attributes of the text, e.g. text size, color and/or alignment
     */
    constructor(index, text, ...att) {
```

2022-06-16 04:40 UTC, ErickSharp commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_Format.js
> +Column.inop = { "color": "inop"};
```suggestion
Column.amber = { "color": "amber" };
Column.red = { "color": "red" };
Column.green = { "color": "green" };
Column.cyan = { "color": "cyan" };
Column.white = { "color": "white" };
Column.magenta = { "color": "magenta" };
Column.yellow = { "color": "yellow" };
Column.inop = { "color": "inop" };
```

2022-06-16 04:40 UTC, ErickSharp commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_Format.js
> + * @param columns {Column}
```suggestion
 * @param columns {@link Column}
```

2022-06-16 04:48 UTC, ErickSharp requested changes

2022-06-16 04:48 UTC, ErickSharp commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_Format.js
> + * @param lines {array[Column[]]} mcdu lines
```suggestion
 * @param {Column[][]} lines - mcdu lines
```

2022-06-16 19:37 UTC, ErickSharp approved these changes
Awesome 🤗🤗

2022-06-20 20:26 UTC, alexr4339 commented
Quality Assurance Tester Report

Discord : Alex R#6663
Object of testing: PR#7294
Tier of Testing : 1
Date : 20/06/2022

Testing Process:
Loaded A/C on runway and checked whether all MCDU pages look the same as before and dont have any errors or misaligned elements. (To me both pictures given above, before and after, look the same to me. Thats why I decided to check whether all pages look as intended)

Negatives:
N/A

Testing Results:
Passed

2022-06-23 03:35 UTC, merged