fix(fmgc): make des spd lim available prior to descent
flybywiresim/a32nx pull request #7529
Opened 2022-10-02 01:57 UTC by tracernz

Fixes #[issue_no]

## Summary of Changes

- Make DES SPD LIM available on VERT REV for all waypoints with DES constraints, and when flight phase is DES (without VNAV we don't have ToD so this is a compromise)
- Fix a couple of copy-pasta bugs with DES SPD LIM

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

Check that CLB SPD LIM can be altered by VERT REV on from airport and SID waypoints, check that DES SPD LIM can be altered by VERT REV on to airport and STAR/APPR waypoints, without affecting each other.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2022-10-02 08:24 UTC, BlueberryKing requested changes

2022-10-02 08:24 UTC, BlueberryKing commented on flybywire-aircraft-a320-neo/html_ui/Pages/VCockpit/Instruments/Airliners/FlyByWire_A320_Neo/CDU/A320_Neo_CDU_VerticalRevisionPage.js
>                  const climb = mcdu.flightPhaseManager.phase < FmgcFlightPhases.CRUISE;
This appears to be unused.

```suggestion
```

2022-10-02 09:27 UTC, BlueberryKing approved these changes

2022-10-04 23:34 UTC, mico975 commented
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #7529 
Tier of Testing  : 1
Date             : 05/10/2022

Testing Process: 
Check that CLB SPD LIM can be altered by VERT REV on from airport and SID waypoints - **OK**
Check that DES SPD LIM can be altered by VERT REV on to airport and STAR/APPR waypoints  - **OK**
Without affecting each other. - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

2022-10-05 18:11 UTC, tracernz commented
Prior to predictions being available SPD LIM is only available on the origin and destination... I will make some tweaks to this.

2022-10-06 22:24 UTC, BlueberryKing approved these changes
🚀

2022-10-10 20:30 UTC, pinatacolada commented
Just a reminder that after this pr was opened,  the clb/des spd lim was correlated to the spd lim flag, that is included along the entire sid/star points

2022-10-11 00:26 UTC, tracernz commented
> Just a reminder that after this pr was opened, the clb/des spd lim was correlated to the spd lim flag, that is included along the entire sid/star points

Yes, thanks again for the new data points. 👍

2022-10-19 08:44 UTC, BlueberryKing approved these changes

2022-10-19 10:20 UTC, merged