refactor(tcas): Fixed several issues with TCAS and traffic display
flybywiresim/a32nx pull request #7567
Opened 2022-10-23 16:34 UTC by 2hwk

Fixes #[issue_no]

## Summary of Changes

Fixed several edge cases with traffic display and TCAS computer
- More traffic should be shown above 10000 feet as an issue with the ground level being incorrectly calculated has been fixed.
- Traffic Advisories should now persist for at least 4 seconds before being dismissed, before the expiry was not being respected.
- In some cases, the ND would fail to correctly display TA/RA symbols for the relevant intruders, this should now always work.

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub): 2Cas#1022

## Testing instructions

Test with both injected traffic (VATSIM/FSLTL) and live traffic (MSFS Live Traffic, not AI Traffic)

1. Load in C&D at FAOR (or another high altitude airfield), with either multiplayer, live traffic or VATSIM/FSLTL traffic enabled (live traffic and traffic from addons i.e. FSLTL preferred)
2. Power on, Turn on ATC XPDR and switch TCAS mode to TA/RA, etc.
3. Check that no traffic that is parked at a gate or taxiing on ground is displayed on the traffic display.
4. Load in on approach at FAOR (or another high altitude airfield) and check that no traffic that is on ground is displayed on the ND. 
5. Fly up to CRZ level 10000, look for and try and intercept local traffic (this may be harder to do with injected traffic. Check that traffic that is in range (-27000 ft to 27000 ft on all TCAS settings (ABV/BEL/ALL), extending to 99000 ft in either direction (ABV/BLW setting) is displayed. Note that the maximum number of displayed intruders is 8, if there is more 8 intruders, the furthest/non-intersecting traffic will not be displayed.
6. Attempt to trigger TAs and RAs
7. Disobey RA instructions at first, then obey the direction, observe that RA dismisses correctly when the conflict is cleared. 

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2022-10-24 10:28 UTC, beheh requested changes

2022-10-24 10:28 UTC, beheh commented on src/tcas/src/components/TcasComputer.ts
> +                    console.log(`${traffic.ID} resetting seconds since last TA to 0`);
```suggestion
                    if (this.debug) console.log(`${traffic.ID} resetting seconds since last TA to 0`);
```

2022-10-24 10:28 UTC, beheh commented on src/tcas/src/components/TcasComputer.ts
> +            console.log(`TA THREAT COUNT IS ${taThreatCount}`);
No debug check?

2022-10-24 10:28 UTC, beheh commented on src/tcas/src/components/TcasComputer.ts
> +                // Downgrade test
Why "test"?

2022-10-24 10:28 UTC, beheh commented on src/tcas/src/components/TcasComputer.ts
> +                // Downgrade test
Why "test"?

2022-10-24 12:59 UTC, 2hwk commented on src/tcas/src/components/TcasComputer.ts
> +                // Downgrade test
Comments were left by mistake, removing

2022-10-25 15:09 UTC, beheh approved these changes

2022-11-02 13:20 UTC, EuanM199 commented
Quality Assurance Trainee Report

Discord   :  Euan#7980
Object of testing: #7567
Tier of Testing: 2
Date: 02/11/2022

Testing Process: 

- [x] Load in C&D at FAOR (or another high altitude airfield), with either multiplayer, live traffic or VATSIM/FSLTL traffic enabled (live traffic and traffic from addons i.e. FSLTL preferred)
- [x] Power on, Turn on ATC XPDR and switch TCAS mode to TA/RA, etc.
- [x] Check that no traffic that is parked at a gate or taxiing on ground is displayed on the traffic display.
- [x] Load in on approach at FAOR (or another high-altitude airfield) and check that no traffic that is on ground is displayed on the ND.
- [x] Fly up to >10000 ft, look for and try and intercept local traffic (this may be harder to do with injected traffic. Check that traffic that is in range (-27000 ft to 27000 ft on all TCAS settings (ABV/BEL/ALL), extending to 99000 ft in either direction (ABV/BLW setting) is displayed. Note that the maximum number of displayed intruders is 8, if there is more 8 intruders, the furthest/non-intersecting traffic will not be displayed.
- [x] Attempt to trigger TAs and RAs
- [x] Disobey RA instructions at first, then obey the direction, and observe that RA dismisses correctly when the conflict is cleared.

Tested using FSLTL
ND does not display traffic that is on the ground while airborne 
ND does not display traffic Taxing/on the ground while parked (only showing airborne aircraft)
TCAS RA/TAs work under and over 10000
All TCAS settings work correctly above 10000
Disobeying RA instructions at first then obeying the direction, and observing that RA dismisses correctly when the conflict is cleared does work.

unfortunately, my recording software didn't capture the TCAS RA above 10k, However here is a few clips from the ones I did manage to record.
(Side Note, it was really difficult to get RAs due to FSLTL but there is 0 traffic on vatsim either way at FAOR)

TA then a RA disobeying the direction, then obeying with Conflict clear: 

https://user-images.githubusercontent.com/67420304/199499861-58bd19df-b711-46bb-b8fa-18eccf3a8249.mp4

TA:

https://user-images.githubusercontent.com/67420304/199499887-019669d2-761d-4a83-a707-56ac7d56ae92.mp4

RA:

https://user-images.githubusercontent.com/67420304/199499905-ab49bcf0-4f56-4235-80ed-636b65aed197.mov





Testing Results: 
Passed

2022-11-13 10:15 UTC, merged