feat(atsu): coupled atsu to DATALINK STATUS page
flybywiresim/a32nx pull request #7656
Opened 2022-12-18 11:19 UTC by StenAfMARS

Fixes #[issue_no]

## Summary of Changes

Coupled the DATALINK STATUS page on to the atsu, per request of @svengcz.
Added new functions to atsu to let the DATALINK STATUS page retrieve data directly from the atsu.

Functions added:
DatalinkStatus and DatalinkMode, for both VHF3, HF and SATCOM.

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub): space_viking#0186

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2022-12-19 08:02 UTC, svengcz requested changes

2022-12-19 08:02 UTC, svengcz commented on src/atsu/src/ATSU.ts
> +    public vhfDatalinkStatus() {
I would suggest to put these functions in the Datalink.ts.
The Datalink.ts is responsible to simulate the communication.

It is planned that it switches between SATCOM, HF and VHF.
So maybe proxies in the ATSU.ts are better (like isRemoteStationAvailable).
The logic is handled in the Datalink, but not all datalink-functions are exposed to components outside the ATSU.

2022-12-19 12:48 UTC, StenAfMARS commented on src/atsu/src/DatalinkStatusCodes.ts
> +export enum DatalinkModeCode {
Enum's changed from string to ints

2022-12-19 20:36 UTC, svengcz approved these changes

2022-12-29 15:28 UTC, svengcz approved these changes

2023-01-11 20:18 UTC, mico975 commented
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #7656
Tier of Testing  : 1
Date             : 11/01/2023

Testing Process: 
There really isn't too much to test in this as there visually shouldn't be any difference. 
2nd line of VHF should read ATC/AOC if hoppie is enabled and AOC ONLY if disabled. - **OK**
SATCOM should read "NOT INSTALLED" if satcom is disabled in the EFB - **OK**
and "DLK NOT AVAIL" if satcom is enabled. - **OK**

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

2023-01-11 21:53 UTC, merged