feat(hyd): randomization of brake accumulator
flybywiresim/a32nx pull request #7693
Opened 2023-01-07 12:31 UTC by crocket63

Fixes #[issue_no]

## Summary of Changes

This PR brings a realistic starting state for yellow brake accumulator.

It might start empty in really rare case (plane out of maintenance), in most of cases it will start close to max pressure, according to plane shutdown time.

If empty.... Do not try to remove the chocks.... Just saying....

## Screenshots (if necessary)

## References

## Additional context

Discord username (if different from GitHub):

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2023-01-07 12:36 UTC, tracernz commented
I don't think we should ever spawn the aircraft in a non-airthworthy state unless the user has selected something to that effect in the flyPad.

2023-01-07 12:52 UTC, crocket63 commented
> I don't think we should ever spawn the aircraft in a non-airthworthy state unless the user has selected something to that effect in the flyPad.

Nothing non-airworthy here, checking accumulator state and refilling it if needed is part of standard cold start check list.

2023-01-13 15:06 UTC, crocket63 commented
Last version is broken somehow :(

2023-01-22 17:27 UTC, Gurgel100 requested changes
Great work as always.

2023-01-22 17:27 UTC, Gurgel100 commented on src/systems/systems/src/hydraulic/brake_circuit.rs
> +        }
Could write it like this:
```suggestion
        self.accumulator
            .as_ref()
            .map_or(Volume::default(), |acc| acc.fluid_volume())
```
or like this:
```suggestion
        self.accumulator
            .as_ref()
            .map_or(Volume::default(), Accumulator::fluid_volume)
```

2023-01-22 17:27 UTC, Gurgel100 commented on src/systems/systems/src/hydraulic/brake_circuit.rs
> +        }
```suggestion
        self.accumulator
            .as_ref()
            .map_or(Volume::default(), |acc| acc.total_volume())
```

2023-01-22 17:27 UTC, Gurgel100 commented on src/systems/systems/src/hydraulic/brake_circuit.rs
> +        }
```suggestion
       self.accumulator
            .as_ref()
            .map_or(Volume::default(), |acc| acc.gas_volume())
```

2023-01-22 17:27 UTC, Gurgel100 commented on src/systems/systems/src/hydraulic/brake_circuit.rs
> +            total_volume - (actual_gas_precharge_randomized * total_volume) / target_pressure;
If you change the order of the multiplication and division you get higher precision with the same performance.

2023-01-22 17:27 UTC, Gurgel100 commented on src/systems/systems/src/hydraulic/brake_circuit.rs
> +            test_bed.query_element(|e| e.accumulator_fluid_volume() == Volume::new::<gallon>(0.0))
```suggestion
            test_bed.query_element(|e| e.accumulator_fluid_volume() == Volume::default())
```

2023-01-23 21:05 UTC, Gurgel100 requested changes
Sorry. Somehow this suggestion got lost in my last review.

2023-01-23 21:05 UTC, Gurgel100 commented on src/systems/systems/src/hydraulic/brake_circuit.rs
> +            {
```suggestion
            } else if self.accu_gas_precharge_failure_active_previous_state {
```
The else branch is only executed when the failure is not active so it's not necessary to test that again.

2023-01-25 16:36 UTC, Gurgel100 approved these changes
LGTM

2023-02-03 16:59 UTC, marcman86 commented
Quality Assurance Report

Discord: marcman86#4907
Object of testing: #7693
Tier of Testing: 1
Date: 3/02/2023

Testing Process:
- Spawned at gate at EDDP
- Turned on bat. and ext. power
- Checked state of brake accumulator level > about 60%
- Start  yellow epump > brake accu goes green
- Restart
- Checked state of brake accumulator level > about 70%
- Start  yellow epump > brake accu goes green
- Restart
- Checked state of brake accumulator level > about 70%
- Start  yellow epump > brake accu goes green
- Restart over main menu
- Checked state of brake accumulator level > about 70%
- Did this a few more times
- Tested accumulator gas leak failture > brake accu gets empty
- Tested brake leaks failture > yellow circuit fails

Negatives: Randomness works only one time. Stays at level shown in image 1.

Testing Results: Failed
Conclusions: -

Hope this helps :-)

Media:

![42](https://user-images.githubusercontent.com/78707844/216662062-f8887ac8-4a09-4736-8319-2bc4c99e86b3.png)
image 1

2023-02-04 17:59 UTC, crocket63 commented
> Quality Assurance Report
> 
> Discord: marcman86#4907 Object of testing: #7693 Tier of Testing: 1 Date: 3/02/2023
> 
> Testing Process:
> 
> * Spawned at gate at EDDP
> * Turned on bat. and ext. power
> * Checked state of brake accumulator level > about 60%
> * Start  yellow epump > brake accu goes green
> * Restart
> * Checked state of brake accumulator level > about 70%
> * Start  yellow epump > brake accu goes green
> * Restart
> * Checked state of brake accumulator level > about 70%
> * Start  yellow epump > brake accu goes green
> * Restart over main menu
> * Checked state of brake accumulator level > about 70%
> * Did this a few more times
> * Tested accumulator gas leak failture > brake accu gets empty
> * Tested brake leaks failture > yellow circuit fails
> 
> Negatives: Randomness works only one time. Stays at level shown in image 1.
> 
> Testing Results: Failed Conclusions: -
> 
> Hope this helps :-)
> 
> Media:
> 
> ![42](https://user-images.githubusercontent.com/78707844/216662062-f8887ac8-4a09-4736-8319-2bc4c99e86b3.png) image 1

What do you exactly mean by randomness only works once?

2023-02-04 22:37 UTC, marcman86 commented
Test instruction: "Check brake accumulator gauge is different on various flight restarts."

On first spawn gauge shows about 60% (the top one). Then raspawn and gauge shows about 70% like in the image (the top one was the only one who showed a different value). Then respawn again and again 70%. That made me curious. So i tryed a few more respawns. Here it shows every time the same 70%. 

From your test instruction (maybe not precise enough, so i maybe dont understand it the right way) i expeceted the gauge to change on every respawn.

2023-02-09 16:34 UTC, crocket63 commented
> Test instruction: "Check brake accumulator gauge is different on various flight restarts."
> 
> On first spawn gauge shows about 60% (the top one). Then raspawn and gauge shows about 70% like in the image (the top one was the only one who showed a different value). Then respawn again and again 70%. That made me curious. So i tryed a few more respawns. Here it shows every time the same 70%.
> 
> From your test instruction (maybe not precise enough, so i maybe dont understand it the right way) i expeceted the gauge to change on every respawn.

Looked into this and while the accumulator init is as expected, unwanted brake application on spawn is indeed messing the result.

Could you do another test pass with added checks please?
Check hydraulic quantities in reservoir are ok on multiple restarts and multiple start point (runway/gate...)
Check brakes work as expected in various spawning positions

2023-02-09 20:29 UTC, Gurgel100 commented on .github/CHANGELOG.md
> +1. [HYD] Realistic randomized yellow accumulator starting state - @Crocket63 (crocket)
Move to end of changelog

2023-02-12 10:43 UTC, 2hwk commented
Quality Assurance Report

Discord: 2Cas#1022
Object of testing: https://github.com/flybywiresim/a32nx/pull/7693
Tier of Testing : 1
Date : 12/02/2023

Testing Process:
-[x] Check brake accumulator gauge is different on various flight restarts. - Took many tries but determined this was working after some bad luck getting similar % a few times in a row. 
-[x] Check gauge needle goes in the middle of green band when accumulator is fully loaded

-[x] Test new brake leaks failure and accumulator gas leak failure.

![image](https://user-images.githubusercontent.com/15316958/218306280-4481cb1d-7c9e-4248-90a9-b649dfeff57b.png)
![image](https://user-images.githubusercontent.com/15316958/218306286-fa008a67-4c9e-4cc7-9b79-5628c9453228.png)


-[x] Check hydraulic quantities in reservoir are ok on multiple restarts and multiple start point (runway/gate...)
-[x] Check brakes work as expected in various spawning positions

Negatives:
N/A

Testing Results:
Passed

Conclusions:
LGTM

2023-02-12 13:27 UTC, merged