Ewd2
flybywiresim/a32nx pull request #7698
Opened 2023-01-08 20:26 UTC by Eearslya

## Summary of Changes

Ported the EWD from React over to MSFS avionics. This framework uses a (mostly) fixed DOM, allowing for better performance.

## Screenshots (if necessary)

Left: Original React EWD
Right: New MSFS Avionics EWD
![image](https://user-images.githubusercontent.com/2270586/211217168-9374e473-2617-4afa-8edd-3eb0e9412ecf.png)

## References

All references were taken from the existing EWD code.

## Additional context

Discord username (if different from GitHub): Eearslya#7831

## Testing instructions

Given that the EWD is a critical instrument with a lot of information, there are many things to be tested, and no single way of how to test them.
Things to test include:

- [ ] Engine status readouts (N1, EGT, N2, FF)
- [ ] Packs/Anti-Ice readouts
- [ ] N1 Limiter readout
- [ ] FOB readout
- [ ] Slats/Flaps indicator
- [ ] FWC Messages

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2023-01-09 08:05 UTC, auroraisluna commented
do a ghost commit for title action to be resolved,  can I just add LOOKING FANCY. Have you measured the perf diff? Might be interesting to know

2023-01-09 08:09 UTC, Eearslya commented
I've not done any measuring, no, but this seems to be the framework the team wants to move all of the instruments to!

2023-01-15 06:31 UTC, Benjozork requested changes
Not a complete review yet, but thought I'd leave some early comments

2023-01-15 06:52 UTC, Eearslya commented on src/instruments/src/EWD2/EWD.tsx
> +export class EWDComponent extends DisplayComponent<EWDProps> {
Should PFD be updated to follow this too?

2023-01-17 04:01 UTC, Benjozork commented on src/instruments/src/EWD2/EWD.tsx
> +export class EWDComponent extends DisplayComponent<EWDProps> {
In a separate PR, if you want.

2023-02-11 23:17 UTC, Benjozork approved these changes

2023-02-13 12:45 UTC, mico975 commented
Quality Assurance Tester Report

Discord          : mico#3145
Object of testing: #7698
Tier of Testing  : 2
Date             : 13/02/2023

Testing Process: 
Things to test include:

 Engine status readouts (N1, EGT, N2, FF) - **OK**
 Packs/Anti-Ice readouts - **OK**
 N1 Limiter readout - **OK**
 FOB readout - **OK**
 Slats/Flaps indicator - **OK**
 FWC Messages - **OK**, didn't test all because that would be too much

Negatives:       
N/A

Testing Results: 
Passed

Conclusions: 
LGTM

Media:       
![image](https://user-images.githubusercontent.com/78908672/218460042-a86e5215-9b1d-4e73-a7d8-9a5bcc69f619.png)

2023-02-13 13:21 UTC, merged