feat: Fix a bug in MSFS Checklists
flybywiresim/a32nx pull request #7789
Opened 2023-02-11 14:34 UTC by Chryssie

## Summary of Changes

Adds a separate package that fixes a bug for rendering the Asobo checklists with nested blocks.

## Screenshots (if necessary)

Without the fix nested `Block` elements in checklists are rendered incorrectly (the alignment is wrong) and contain phantom (duplicate) items:
![broken nested blocks example](https://user-images.githubusercontent.com/10442662/211322530-9b1946a9-c360-4218-ad5a-225c130d45a0.png)

The fix improves the indentation and prevents the phantom items from being generated.
![working nested blocks example](https://user-images.githubusercontent.com/10442662/211322762-6ea92b0a-41ec-4106-b6ad-d6788bdd4336.png)

## References

## Additional context

This was originally a part of #7627, however, I have split it out to this pull request.

⚠ This change does impact the entire game and other aircraft as it overrides (in the virtual file system, no files on disk are changed) some core game files.

However, it has now been updated so that the override in it's own package that can be uninstalled (or not installed in the first place) in the unlikely event that it causes a conflict with another addon.

Discord username (if different from GitHub): Chryssie#1984

## Testing instructions

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2023-02-12 11:17 UTC, frankkopp requested changes
Can you take a look at the gitignore? the rest is good.

2023-02-12 11:17 UTC, frankkopp commented on .gitignore
> +/fbw-msfs-checklist-fix/out
Can you add - this makes sure the structure within these folders is identical:

/fbw-msfs-checklist-fix/*

!/fbw-msfs-checklist-fix/README.md

!/fbw-msfs-checklist-fix/docs/

!/fbw-msfs-checklist-fix/docs/**

!/fbw-msfs-checklist-fix/src/

!/fbw-msfs-checklist-fix/src/**

/fbw-msfs-checklist-fix/out

Also can't hurt to write a README.md to describe what this folder is for.

2023-02-12 11:25 UTC, frankkopp requested changes

2023-02-12 11:25 UTC, frankkopp commented on .github/workflows/msfs-checklist-fix.yml
> +      - 'package-lock.json'
```suggestion
```

Remove this

2023-02-12 11:50 UTC, frankkopp approved these changes

2023-02-12 14:30 UTC, Benjozork requested changes
The output package name does not follow the convention set by the MSFS documentation - this convention is useful for understanding what a package does.

![image](https://user-images.githubusercontent.com/4503241/218317067-2a28b977-bc3a-4126-930a-543d502a697a.png)

I suggesst `flybywire-ingamepanels-checklist-fix`. The official package name, for reference, is `fs-base-ingamepanels-checklist`.

2023-02-13 11:18 UTC, Chryssie commented
Thanks @Benjozork, I've updated the package name (along with all of the folders) to `flybywire-ingamepanels-checklist-fix` (except the root folder which is `fbw-ingamepanels-checklist-fix` in line with the other packages).

2023-02-13 18:00 UTC, Benjozork approved these changes

2023-02-13 21:40 UTC, merged