Interior lights rework, new glass textures and improved exterior winglights
flybywiresim/a32nx pull request #7947
Opened 2023-04-04 00:40 UTC by FinalLightNL

Fixes #6108 

## Summary of Changes
My previous PR caused a couple issues looking very unrealistic in some conditions based on time of day and weather.
I have removed every single light within the cockpit and redid everything from scratch.
Including the emissive decals which has a little surprise.

List of changes :

- Removed all soft lights from all .fx files which results in proper reflections on all materials without dulling them out, this also makes textures look better imo.
- All flood types now cast ambient lights giving a ray tracing ish feel.
- Flood lights are enhanced, also now has the correct 2800K temp color according to ref data.
- Dome lights has been enhanced as well, and the first step is less bright as it should be.
- Emissive decals now have integ bulb wear below the diffusers, went of by a 7 year old NEO so didn't make it too prominent.
- The clock now powers on bus and has a blue ish background glow as per panel type, it was on @ C&D before which isn't normal behavior.
- Winglights have been changed according to references, and also cast slightly within the pod and blades (inner outside more)
- New glass textures added thanks to @MoreRightRudder for the wonderful work.
- The box shadow css related to homecockpit has been fully commented out, makes homecockpit mode useless atm (needs to be removed in another pr)
This was a necessary step to make the glass textures look as they are.
- Fault decals were yellow, changed to amber per references as well.

## Screenshots (if necessary)
![NewGlass](https://user-images.githubusercontent.com/72287598/229654761-f95896da-7908-441b-b76e-6f491b95f3ca.png)
![Floods_Main1](https://user-images.githubusercontent.com/72287598/229656090-8cac71c4-4f17-4455-83b6-d4039c832206.png)
![FloodPed1](https://user-images.githubusercontent.com/72287598/229655792-be9a6e29-8d22-4356-9f37-057652e814fa.png)
![NewIntegs_1](https://user-images.githubusercontent.com/72287598/229653821-490298e6-98f1-4be1-8a6a-dff2d18da1f7.png)
![Ambiance1](https://user-images.githubusercontent.com/72287598/229653883-5afdf582-7156-4b94-b5ad-cfe3d1c283a1.png)
![Ambiance2](https://user-images.githubusercontent.com/72287598/229653896-1d5f417d-5018-4954-89c4-b1b9dffd8307.png)
![Console](https://user-images.githubusercontent.com/72287598/229653919-b7679bb9-c6aa-4408-817f-568b9a25dbcb.png)
![Dome1](https://user-images.githubusercontent.com/72287598/229654396-169f0828-04d5-46f5-878d-9321e4837b8a.png)
![Dome3](https://user-images.githubusercontent.com/72287598/229654497-4acca9d3-2ce1-46eb-8df8-034f033227c3.png)
![Dome2](https://user-images.githubusercontent.com/72287598/229654517-bba5376a-2595-4e84-8791-cd6db42f1640.png)
![Dome4](https://user-images.githubusercontent.com/72287598/229654528-ffed4b5e-473a-49b8-b0e1-00fdc4c14a34.png)
![winglight_2png](https://user-images.githubusercontent.com/72287598/229654555-3d18e2d4-93ed-42d4-a8f2-98d99326cbd5.png)
![ClockOnBus](https://user-images.githubusercontent.com/72287598/229654578-31d76646-dfe1-4e0d-af09-79ebdfe09aa7.png)
![Ambiance3](https://user-images.githubusercontent.com/72287598/229654603-6f053469-f30a-4e27-9b7a-c82b717b5d17.png)
![Ambiance2](https://user-images.githubusercontent.com/72287598/229654609-5f18405e-2156-412d-a43e-0def5894ffcd.png)
![IntegBreakers](https://user-images.githubusercontent.com/72287598/229654936-7eaf7074-be99-46b8-974d-4ee2e672b60f.png)

## References

## Additional context
There are quite a few changes in here, but it improves the whole feel of the cockpit.
Feel free to DM me on discord or comment below when you encounter issues or see something that is off.

Discord username (if different from GitHub): FinalLight#2113

## Testing instructions
Please spawn in several different time of day, fly through clouds as well.
Play with weather presets in all conditions including fog and see if all looks fine.
check if the clock display is off when plane is in C&D and turns on when both batteries are pressed with bus power.
Check if integ lights redshift or not, this was the biggest issue in my previous PR.
They should stay between Amber Orange and yellow~ish.
Dome lights should be dim on the first position and quite bright in the second as well.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2023-04-04 02:09 UTC, tracernz commented on fbw-a32nx/src/base/flybywire-aircraft-a320-neo/effects/A32NX_Cockpit_ConsoleMid.fx
> +ScatDir=1
Missing newline.

2023-04-04 02:09 UTC, tracernz commented on fbw-a32nx/src/base/flybywire-aircraft-a320-neo/effects/A32NX_Cockpit_DomeLightAmbient1.fx
> +ScatDir=0
Missing newline.

2023-04-04 02:09 UTC, tracernz commented on fbw-a32nx/src/base/flybywire-aircraft-a320-neo/effects/A32NX_Cockpit_DomeLightAmbient2.fx
> +ScatDir=0
Missing newline.

2023-04-04 02:09 UTC, tracernz commented on fbw-a32nx/src/base/flybywire-aircraft-a320-neo/effects/A32NX_Cockpit_MainPanelFlood.fx
> +ScatDir=0
Missing newline.

2023-04-04 02:09 UTC, tracernz commented on fbw-a32nx/src/base/flybywire-aircraft-a320-neo/effects/A32NX_Cockpit_MainPanelFloodCenter.fx
> +ScatDir=0.0
Missing linefeed.

2023-04-04 02:09 UTC, tracernz commented on fbw-a32nx/src/systems/instruments/src/Clock/Clock.tsx
> +            const svgElement = this.gElementRef.instance.closest('svg');
Why not just add a ref to the element you need?

2023-04-04 02:09 UTC, tracernz commented on fbw-a32nx/src/systems/instruments/src/Common/pixels.scss
> +*/
Missing linefeed.

2023-04-04 02:09 UTC, tracernz commented on fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/pixels.scss
> +*/
Missing linefeed.

2023-04-04 02:56 UTC, 2hwk requested changes

2023-04-04 02:56 UTC, 2hwk commented on fbw-a32nx/src/systems/instruments/src/Common/pixels.scss
> +/* TO BE REMOVED TOGETHER WITH HOME COCKPIT MODE
```suggestion
/* TODO FIXME: TO BE REMOVED TOGETHER WITH HOME COCKPIT MODE
```

prefix with TODO FIXME:

2023-04-04 02:56 UTC, 2hwk commented on fbw-a32nx/src/systems/instruments/src/MsfsAvionicsCommon/pixels.scss
> +/* TO BE REMOVED TOGETHER WITH HOME COCKPIT MODE
```suggestion
/*  TODO FIXME: TO BE REMOVED TOGETHER WITH HOME COCKPIT MODE
```
prefix with TODO FIXME:

2023-04-04 06:58 UTC, tracernz commented on fbw-a32nx/src/systems/instruments/src/Clock/Clock.tsx
>          });
Could be simplified if you like, up to you.
```ts
        sub.on('dcEssIsPowered').whenChanged().handle((dccEssIsPowered) => {
            this.svgElementRef.instance.classList.toggle('powered', dccEssIsPowered);
            this.svgElementRef.instance.classList.toggle('unpowered', !dccEssIsPowered);
        });
```

2023-04-04 12:16 UTC, 2hwk commented
Lint is failing (Line 15 Clock.tsx)

2023-04-05 03:27 UTC, 2hwk approved these changes

2023-04-05 04:02 UTC, 2hwk commented
I've run through the testing instructions once but I feel this needs also more testing with wider hardware and software configurations at various resolutions. Definitely candidate for EXP for wider testing and feedback.

2023-04-05 04:20 UTC, 2hwk commented
QA Report

Testing:
- [x] Please spawn in several different time of day, fly through clouds as well.
- [x] Play with weather presets in all conditions including fog and see if all looks fine.
- [x] Check if the clock display is off when plane is in C&D and turns on when both batteries are pressed with bus power.
- [x] Check if integ lights redshift or not, this was the biggest issue in my previous PR. They should stay between Amber Orange and yellow~ish.
- [x] Dome lights should be dim on the first position and quite bright in the second as well.

Note:
* This run was done on proton experimental with DXVK as such, testing is possibly only valid for functionality and not visuals, as there are quite substantial differences in visuals between DXVK and DX11 on windows.

Settings were custom/Ultra at 1440p (No 10-bit or HDR). Unknown how visuals would be affected at lower resolutions (1080p). 

Negatives:
- May need adjustment from previously set user lighting presets, generally would need to be set darker. This should be communicated.

Result:
QA Pass, but see note

Conclusions:
LGTM but push to experimental for wider public testing.

2023-04-05 09:14 UTC, Ker1010 commented
hello I'm testing light new at exp mode 24d7452 version then when look at external found a strange light above the cockpit
![image](https://user-images.githubusercontent.com/42411469/230036360-361675c9-c3f2-4c3a-8d73-7e65b7cad2d3.png)

turn on wing light
![image](https://user-images.githubusercontent.com/42411469/230035731-c0cb8eb3-e084-4b89-9b17-a3b5ea8a6be2.png)

turn off wing light
![image](https://user-images.githubusercontent.com/42411469/230035852-3ca4ac49-667b-45db-9a92-9008df076ff1.png)


https://user-images.githubusercontent.com/42411469/230036874-2dee8318-c62c-420f-a221-b387522e5639.mp4

Great work!

2023-04-05 11:14 UTC, FinalLightNL commented
if anyone else spots floating tiny orbs let me know, i fixed the one Ker reported and found 2 more which i fixed.

2023-04-07 19:14 UTC, alexr4339 commented
Quality Assurance Tester Report

Discord          : Alex R#6663
Object of testing: #PR 7947
Tier of Testing  : 2
Date             : 06/04/2023

Testing Process: 
Testing process as described in testing instruction. Simulator is running on DX11.

Negatives:       
No negatives found. The flood light (the flood light coming from the bottom of the glareshield which illuminates the area around the displays) at full brightness during night seemed a bit bright to me. That may be due to my system. Additionally I dont have a personal reference of how bright the flood light is at night and full brightness. As a result this statement should be taken as a personal preference only.

Testing Results: 
Passed

Conclusions: 
This PR improves the lighting greatly and improves the feeling of the lighting.

2023-04-08 02:26 UTC, merged

2023-04-09 13:51 UTC, Watsi01 commented
Again we have to discuss the glass texturing (imho). It was the same about 1 year ago or so - and got reverted back because of user feedback.
Maybe the reflections are fine. But if changes in the glass textures result in strange coloring of the displays (again > imho), I would assume users wouldn't appreciate it. 

See this cyan coloring on top of the FO ND?
![glass](https://user-images.githubusercontent.com/72334392/230776281-9a51052e-9995-49ff-b837-14876804a19f.jpg)

Have the same on top of the CPT PFD. Regardless which angle/position I look on it.

If this is not done yet, forget what I wrote and I'll wait. 

I just think we have to be cautious to have the coloring pretty accurate, regardless the angle or outside light effecting it. This may be more unrealistic according to the real look in a real cockpit, but this way it is kind of disturbing in the sim (imho :-) )

2023-04-09 14:49 UTC, MoreRightRudder commented
> 

Hi the display coloring is carefully made and are accurate to displays like these. The display fades over time and the pixels don't output the same as they used to. This leads to a color degradation which I have depicted here. Feel free to make transparent the glass texture in your file using paint.net or delete the file from your texture folder. This will get rid of the glass texture. 

Additionally I made these textures more than one year ago. Now they are finally merged. I do not plan to address any more a320 textures until a new model is worked on, thank you.

2023-04-09 19:27 UTC, Watsi01 commented
> > 
> 
> Hi the display coloring is carefully made and are accurate to displays like these. The display fades over time and the pixels don't output the same as they used to. This leads to a color degradation which I have depicted here. Feel free to make transparent the glass texture in your file using paint.net or delete the file from your texture folder. This will get rid of the glass texture.
> 
> Additionally I made these textures more than one year ago. Now they are finally merged. I do not plan to address any more a320 textures until a new model is worked on, thank you.

Hi Mike,
I'm really sorry, if I hurt your feelings. That was not my intention. Nore was it to critisize your excelent work. My intention was to discuss, how real it should get / can get in a sim. And if really everything that may look, sound or feel like the real thing is appropriate to port it to a simulation. Are there limits? Or maybe not?
I had a similar discussion some while ago regarding sounds. Some things can sound horrible (or disturbing) in a real cockpit. Is it indispensable to port them into a sim and let the sim-pilot hear that disturbing sound all the time and in real loudness? Or should one decide to make a compromise between reality and ear candy?