Fix/ecam sts delay
flybywiresim/a32nx pull request #8048
Opened 2023-05-28 10:31 UTC by pluce

Fixes #8046 

## Summary of Changes
The Status Page page of lower ECAM / System Display should appear only 3s if no failures are to be shown. This PR adds this timer before coming back to previous page.
Also replaces hardcoded values by constants to improve readability in the PageContainer component.

## References
[FCOM](http://repo.poltekbangsby.ac.id/571/1/A318_A319_A320_A321%20%28%20PDFDrive%20%29.pdf) (page 1190)
<img width="508" alt="STS_button" src="https://github.com/flybywiresim/a32nx/assets/2952153/93edd5d0-f4c2-4ab9-ac55-22bd0f4a28cf">

## Additional context
First PR 👀 

## Testing instructions
Should not change behaviour of lower ECAM beside returning to previous page after 3s if no failure. I couldn't make Status page to be filled by anything, but after a discussion on Discord it may be normal.

## How to download the PR for QA

Every new commit to this PR will cause a new A32NX artifact to be created, built, and uploaded.

1. Make sure you are signed in to GitHub
1. Click on the **Checks** tab on the PR
1. On the left side, click on the bottom **PR** tab
1. Click on the **A32NX** download link at the bottom of the page

2023-05-28 11:12 UTC, pluce commented
- [ ] Change the constants list for pages to an Enum

2023-06-04 02:57 UTC, 2hwk commented
Lint is failing, please fix
https://github.com/flybywiresim/a32nx/actions/runs/5125901688/jobs/9223580234?pr=8048
<img width="580" alt="image" src="https://github.com/flybywiresim/a32nx/assets/15316958/36807ea2-2af2-4d9d-a334-474bb9730f56">

2023-06-04 02:58 UTC, 2hwk requested changes

2023-06-04 02:58 UTC, 2hwk commented on fbw-a32nx/src/systems/instruments/src/SD/PagesContainer.tsx
> +                SimVar.SetSimVarValue(`L:A32NX_ECAM_SD_CURRENT_PAGE_INDEX`, "number", stsPrevPage);
```suggestion
                SimVar.SetSimVarValue(`L:A32NX_ECAM_SD_CURRENT_PAGE_INDEX`, 'number', stsPrevPage);
```

2023-06-04 03:01 UTC, 2hwk requested changes

2023-06-04 03:01 UTC, 2hwk commented on fbw-a32nx/src/systems/instruments/src/SD/PagesContainer.tsx
> +            setStsPressedTimer(STS_DISPLAY_TIMER_DURATION)
```suggestion
            setStsPressedTimer(STS_DISPLAY_TIMER_DURATION);
```

2023-06-04 03:01 UTC, 2hwk commented on fbw-a32nx/src/systems/instruments/src/SD/PagesContainer.tsx
> +                setStsPressedTimer(STS_DISPLAY_TIMER_DURATION)
```suggestion
                setStsPressedTimer(STS_DISPLAY_TIMER_DURATION);
```

2023-06-04 03:01 UTC, 2hwk commented on fbw-a32nx/src/systems/instruments/src/SD/PagesContainer.tsx
> +    const [normalStatusLine] = useSimVar(`L:A32NX_STATUS_LEFT_LINE_8`, 'number', 100);
```suggestion
    const [normalStatusLine] = useSimVar('L:A32NX_STATUS_LEFT_LINE_8', 'number', 100);
```

2023-06-04 12:27 UTC, pluce commented
should be good @2hwk thanks !

2023-06-11 02:39 UTC, Benjozork approved these changes

2023-06-11 10:09 UTC, 2hwk approved these changes

2023-06-30 16:01 UTC, Mack674 commented
Quality Assurance Tester Report

Discord: Mack674#2274
Object of testing: #8048
Tier of Testing: 1
Date: 30/06/2023

Testing Process:
- Spawned C&D at the gate
- Turned on Batteries 1&2 and external power
- Checked behaviour of STS ecam page

Negatives: N/A       

Testing Results: Passed 

Conclusions: Works as intended. Great job!

Media:

https://github.com/flybywiresim/a32nx/assets/62873705/634234cd-3153-4d68-8e95-4f91bf128f4c

2023-06-30 19:43 UTC, merged