[CDU] Init Page Revisions
flybywiresim/a32nx pull request #888
Opened 2020-09-26 09:27 UTC by Lucky38i

Sorry I was having issues rebasing so had to re-create the PR

Fixes #823
Progression to complete #689

**Summary of Changes**
- Colors changed to represent real-world aircraft
- Initial states for INIT A and INIT B revamped
- Introduced split colouring for INIT B (thanks Externo)
- Introduced small fonts on particular areas for INIT B
- LAT and LON now it proper format (thanks Externo)
- Prevented auto computation of ZFW and ZFWCG
- Created parser for entering Trip wind, ZFW and ZFWCG, so you can enter in the various ways supported

If QA Testers could check this and let me know what is missing or needs to be changed

**Things left to do**
- allow skewing for LAT LON on INIT A
- Finish fuel computations #689 so INIT B and FUEL PRED are properly populated
- Add fuel planning in INIT B

**Screenshots (if necessary)**
![image](https://imgur.com/qltGxmF.png)
![image](https://imgur.com/qHR1r2h.png)
![image](https://imgur.com/zKB14Tz.png)
![image](https://imgur.com/kLcSJCx.png)

**Additional context**
Honeywell FMC Manual
A320DP

Discord username: Lucky38#3550

2020-09-26 15:55 UTC, Ares1378 commented
Definitions:
LSK - LINE SELECT KEY on the MCDU
EXAMPLE : LSK 1L = LINE SELECT KEY 1 LEFT
________________________________________________________

There following items need to be corrected:
INIT A nothing entered real MCDU:
![image](https://user-images.githubusercontent.com/70821584/94344198-48aa4980-ffe3-11ea-9b4d-285aee78629e.png)
Changes that need to be made:
-INIT REQUEST:  this should be displayed next to LSK R2
-IRS INIT>: this should be displayed next to LSK R3
-LAT and LON data needs to be deleted this is never displayed on the MCDU INIT A page.
-LSK R6 Font is too big under TROPO

INIT A after FLT NBR and FROM/TO entered:
![image](https://user-images.githubusercontent.com/70821584/94344361-5a402100-ffe4-11ea-90b3-d7aa5b30487a.png)
-CO RTE should be blank and not display NONE
-LAT and LON needs to be deleted 
-INIT REQUEST:  disappears from LSK R2
- IRS INIT> still displayed at LSK R3 

INIT A after being fully initialized:
![image](https://user-images.githubusercontent.com/70821584/94344459-33ceb580-ffe5-11ea-9c34-2f5b48ff490f.png)

INIT B nothing entered:
-trip wind should display HD000
![image](https://user-images.githubusercontent.com/70821584/94344650-5ad9b700-ffe6-11ea-876f-40e1d17ca987.png)


INIT B ONCE ZFW/ZFWCG entered
-FUEL PLANNING --> in amber should appear next to LSK R3
![image](https://user-images.githubusercontent.com/70821584/94344543-c3746400-ffe5-11ea-9012-d19afe94dcb6.png)

INIT B when block fuel is entered:
-FUEL PLANNING --> disappears from LSK R3
![image](https://user-images.githubusercontent.com/70821584/94344572-f61e5c80-ffe5-11ea-9168-fbf241ba50d6.png)

INIT B after ZFW/ZFWCG and block fuel entered should look like the following:
![image](https://user-images.githubusercontent.com/70821584/94344676-8eb4dc80-ffe6-11ea-8741-06179ecd7cae.png)

Please let me know if you need anymore info.

Thanks,

Ares

2020-09-27 01:27 UTC, Benjozork commented
Hello, please take note that we have started including a CHANGELOG.md file that requires every PR to add a change-log line that describes its changes. As your PR is not merged yet, we kindly ask that you add this information following the included directives in the file.

Disclaimer: This is a copy-and-pasted message.

2020-09-27 13:07 UTC, Lucky38i commented
> 
> 
Hi Ares please see 39450a9 and below picture which shows the amended pages as you suggested
> There following items need to be corrected:
> INIT A nothing entered real MCDU:
> -LAT and LON data needs to be deleted this is never displayed on the MCDU INIT A page.
> -LSK R6 Font is too big under TROPO

![image](https://imgur.com/gYSIHJa.png)

> Changes that need to be made:
> -INIT REQUEST: this should be displayed next to LSK R2
> -IRS INIT>: this should be displayed next to LSK R3

This is being done here #677

> 
> WHEN FROM/TO ENTERED the page should auto appear and look like the following:

![image](https://imgur.com/tR0Bwz9.png)

> INIT A after FLT NBR and FROM/TO entered:
> 
> -CO RTE should be blank and not display NONE
> -LAT and LON needs to be deleted

![image](https://imgur.com/Ne7waxc.png)

> -INIT REQUEST: disappears from LSK R2
> 
>     * IRS INIT> still displayed at LSK R3

This is being done here #677

> INIT A after being fully initialized:

![image](https://imgur.com/5fSCkAx.png)
 
> INIT B nothing entered:
> -trip wind should display HD000

![image](https://imgur.com/6yTWbhJ.png)

> INIT B ONCE ZFW/ZFWCG entered
> -FUEL PLANNING --> in amber should appear next to LSK R3

![image](https://user-images.githubusercontent.com/26572019/94365655-9188fd80-00ca-11eb-9a1b-d91ac99b4ff5.png)
 
> INIT B when block fuel is entered:
> -FUEL PLANNING --> disappears from LSK R3
> INIT B after ZFW/ZFWCG and block fuel entered should look like the following:

![image](https://user-images.githubusercontent.com/26572019/94365672-bd0be800-00ca-11eb-8b70-45d08c8990b5.png)


Thanks for the corrections Ares, really appreciate it. If there's anything else astray please let me know!

2020-09-29 07:25 UTC, lousybyte requested changes
Also remove `layout.json` and `manifest.json` please.

2020-09-29 07:25 UTC, lousybyte commented on A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/CDU/A320_Neo_CDU_MainDisplay.js
> +    tryParseZeroFuelWeightZFWCG(s) {
You can modify the `trySetZeroFuelWeightZFWCG` function directly if you include the needed file, https://github.com/flybywiresim/a32nx/pull/871/commits/a83295cabfec06054a220166378a8377f324a0f3 is exactly that, you can copy that commit to this PR.
Same goes for the custom `trySetAverageWind()` as well.

If you need to modify something that's in a shared file, follow the procedure from that commit to add the file to the mod.

2020-09-29 10:14 UTC, lousybyte approved these changes

2020-09-30 11:56 UTC, Lucky38i commented
@AdenFlorian checked and tested

2020-10-01 20:13 UTC, AdenFlorian commented
Please dont format entire files, it looks like you ran a formatter on FMCMainDispaly so now its heard to see what you changed. Please redo your changes to that file so that you only touch the lines that need to be touched for your changes, and double check that you started with the 1.9.3 version of that file, thanks!

2020-10-02 10:15 UTC, Lucky38i commented
> Please dont format entire files, it looks like you ran a formatter on FMCMainDispaly so now its heard to see what you changed. Please redo your changes to that file so that you only touch the lines that need to be touched for your changes, and double check that you started with the 1.9.3 version of that file, thanks!

Fixed here ef5cb2d, as for FMCMainDisplay, I've grabbed the 1.9.3 changes and pasted it in the the file then added my changes. The file doesn't exist in master hence why it's hard to see the actual changes I made. Take a look here https://github.com/flybywiresim/a32nx/blob/ef5cb2d6880c6a5f69752d475cd7f33c789a1c92/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js#L1363-L1426

and here 
https://github.com/flybywiresim/a32nx/blob/ef5cb2d6880c6a5f69752d475cd7f33c789a1c92/A32NX/html_ui/Pages/VCockpit/Instruments/Airliners/A320_Neo/FMC/A32NX_FMCMainDisplay.js#L1250-L1289

for the changes I made

2020-10-02 13:54 UTC, camilo625 commented
Name: Camilo625 #5575
Date of testing: Current date 02/10/2020
Version of the sim: 1.9.3.0
PR Tested: #888 

Testing technique: Sawn C&D and check Init Page
Steps you've made to test the Pull Request:
1. Spawn C%B
2. Load a FPL
3. Check everything its working

Overall Rating: Good
Conclusions of the testing: Seems to work fine, probably an IRL pilot should look at it to verify the correct behavior, other than that it looks good.

2020-10-02 21:37 UTC, lousybyte commented
Inserting a value in the TAXI field seems to not update the displayed value, but the TOW is updated. Other than that, looks good!

2020-10-03 08:11 UTC, Pheome commented
Tested with a short LHBP - LOWW route,C&D, simbrief generated FP added manualy.Everything worked fine.
Taxi is not updated as @lousybyte said,I don't know it's intended or not.Anyway it looks realy nice.

2020-10-03 15:00 UTC, Lucky38i commented
@lousybyte @Pheome taxi issue has been resolved, thanks for spotting that.

2020-10-03 17:32 UTC, lousybyte commented
Seems if the `ZFW/ZFWCG` is empty and you try to input just one of them, you get a `FORMAT ERROR`, not sure if that's intended or not, iirc is working fine w.o the PR.

2020-10-03 19:46 UTC, NathanInnes commented on .github/CHANGELOG.md
> +1. [CDU] Revised INIT B Page - @lucky38i (lucky38i)
Remove dupe & change to current month

2020-10-03 20:17 UTC, Lucky38i commented
> Seems if the `ZFW/ZFWCG` is empty and you try to input just one of them, you get a `FORMAT ERROR`, not sure if that's intended or not, iirc `ZFW` only is working fine w.o the PR.

This is intended and confirmed by @Ares1378. zfw and zfwcg must first be entered before you can try entering either on its own

2020-10-03 20:26 UTC, lousybyte commented
Please merge master again and correct the changelog to current month and will be good to merge!

2020-10-03 20:59 UTC, Ares1378 commented
FMS Pegasus Step 1A Pre-flight 4-23:
After initial entry, the zero fuel weight and zero fuel weight center of gravity are modified together or separately. When both values are entered, the values are separated by a slash ( / ).When only the zero fuel weight center of gravity is modified, the entry is preceded by a slash. Once ZFW and ZFWCG are entered, the values cannot be manually cleared. When the FMS transitions to the done phase, the ZFW and ZFWCG values are cleared automatically.

2020-10-04 12:25 UTC, Lucky38i commented
> 
> 
> Please merge master again and correct the changelog to current month and will be good to merge!

All done!

2020-10-04 16:42 UTC, Lucky38i commented
will #648 be closed if this is pulled btw?

2020-10-04 17:09 UTC, NathanInnes commented
> will #648 be closed if this is pulled btw?

Already is closed

2020-10-04 21:37 UTC, wuperguy approved these changes

2020-10-05 21:07 UTC, AdenFlorian commented
please resolve the initpagejs merge conflicts

2020-10-06 09:16 UTC, Lucky38i commented
> 
> 
> please resolve the initpagejs merge conflicts

fixed conflicts and tested integration with #677. Working as intended

2020-10-06 17:44 UTC, Noxleee commented
Name: Noxlee #7727
Date of testing: Current date 06/10/2020
Version of the sim: 1.9.3.0
PR Tested: #888 

Testing technique: Loaded up ac at gate EDDF. testing the MCDU Pages:
Checks I made:
1. Colours: Same as on the original screenshots, but effecting the whole MCDU

2. Init A: 
          - Lat and Lon are not displayed, see attached screenshot Init A
          - Co RTE is empty after inserting Airports, see attached screenshot Init A

3. Init B: 
          - Looks the same as the original screenshots when empty
          - When filled with data looks like attached screenshot Init B
          - TOW/LW -> the / is at TOW but should be at LW -> TOW      /LW


Overall Rating: to be improved
Conclusions of the testing: All in all its working, but a few things are misaligned and missing.


Init A
![grafik](https://user-images.githubusercontent.com/71323011/95237583-b2f39300-0808-11eb-8cd1-7c85f8b89734.png)

Init B
![grafik](https://user-images.githubusercontent.com/71323011/95237848-ff3ed300-0808-11eb-9c69-5152a7d4e24a.png)

2020-10-07 05:29 UTC, tareksabet commented
To confirm did you follow the Honeywell MCDU model which it should look like that ![image](https://user-images.githubusercontent.com/70240330/95290939-be79a500-086e-11eb-9a09-329daed81f38.jpeg) ![image](https://user-images.githubusercontent.com/70240330/95290964-ccc7c100-086e-11eb-8449-aeb858c2fd69.jpeg)

2020-10-07 05:57 UTC, Noxleee commented
Yes it's looking like the honeywell MCDU , the original Screenshots of the PR are just old.

2020-10-07 23:59 UTC, AdenFlorian commented
LGTM!

2020-10-07 23:59 UTC, merged